### ISSUE TITLE
Script failure when you have public and private zones named the same in Route53

### ISSUE THREAD

**Issue by spaceygithub** [rmbolger/Posh-ACME#100]
Hello,
I've found a problem that when you run a public and private zone under route53. In terms of Route53 it obviously has the same name for the private and public records.  This causes problems when the Posh-ACME code tries to find the matching zone ID as it currently finds multiple ID's
```
if (!($zoneID = Get-R53ZoneId $RecordName $credParam)) {
        throw "Unable to find Route53 hosted zone for $RecordName"
    } 
Get-R53ZoneId uses the Get-R53HostedZoneList which returns a list like this:

Id                     : /hostedzone/ZY3NSS0L345VC
Name                   : domain1.com.
CallerReference        : SNIPPED
Config                 : Amazon.Route53.Model.HostedZoneConfig
ResourceRecordSetCount : 16
LinkedService          :

Id                     : /hostedzone/Z2OX3COWRF3456
Name                   : domain1.com.
CallerReference        : SNIPPED
Config                 : Amazon.Route53.Model.HostedZoneConfig
ResourceRecordSetCount : 3
LinkedService          :
```

The first one is the public and the second record is the private. Unfortunately the Get-R53HostedZoneList function doesn’t look to pull back the Boolean value that you can see through simular tools like the cli aws route53 list-hosted-zones  `"PrivateZone": true`. I've asked on the AWS forums if there is an alternative function or combination of cmdlets that could be used to track this but at this time it doesn’t look like there is. 

Best workaround I can come up with currently would be to allow a Param of the 'HostedZoneId' so users can specify it. 

Current error that's produced 
```
Get-R53ResourceRecordSet : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'HostedZoneId'. Specified method is not supported.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\DnsPlugins\Route53.ps1:43 char:42
+     $response = Get-R53ResourceRecordSet $zoneID $RecordName 'TXT' @c ...
+                                          ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-R53ResourceRecordSet], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Amazon.PowerShell.Cmdlets.R53.GetR53ResourceRecordSetCmdlet
```

Welcome any suggestions that you might have.

**Comment by spaceygithub** [comment]
Think I've found a fix / workaround for this but will defer to your expertise 
I suggest changing line 242
From
`$zoneID = ($zones | Where-Object { $_.Name -eq $zoneTest }).Id`
To
`$zoneID = ($zones | Where-Object { $_.Name -eq $zoneTest -and $_.config.PrivateZone -eq "False"}).Id
`

**Comment by rmbolger** [comment]
Awesome! I didn't even realize private zones were a thing, but of course they are. And great find on that `PrivateZone` property. That will definitely be the fix.

**Comment by spaceygithub** [comment]
Thanks for getting this turned around so quickly. I was wondering when its likely to show up on the PowerShell Gallery?

**Comment by rmbolger** [comment]
There’s a pull request I’m working on right now to add a new feature that I was hoping to finish before pushing a new release. But if I don’t finish by this afternoon, I’ll probably just release a 2.9.1 version with this and a few other fixes in it.

**Comment by spaceygithub** [comment]
Thanks very much, appreciate all the time and effort this must take you. I'll hold fire implementing a local workaround and wait for your next release.  Thanks again.
