### ISSUE TITLE
Change Output path

### ISSUE THREAD

**Issue by LuchoRP** [rmbolger/Posh-ACME#105]
Hello @rmbolger, is it possible to change the output path where the certificate files are exported (.key, .crt, etc.)?
Thanks again

**Comment by rmbolger** [comment]
At the moment, no. And some of the code currently depends on those files staying where they are for later renewals. However, there's nothing stopping you from copying them elsewhere. The output object from `New-PACertificate` and `Get-PACertificate` contains all of the file paths and could be used to fairly easily copy the ones you care about somewhere else. Something like this:

```
$cert = Get-PACertificate
Copy-Item -Path $cert.CertFile -Destination C:\temp
```

To see all of the properties of an object, I like to pipe it to `Format-List` like this:

```
$cert | fl
```

**Comment by LuchoRP** [comment]
Yes, I did, but I think in the supposed case that the user deletes the folder unknown to him or even the complete profile that run the script. Well, then I will try to protect the folder.
Thanks for the quick reply.

**Comment by rmbolger** [comment]
While you can't customize the output path for a given order, you can currently change the root config location using the `POSHACME_HOME` environment variable. More info here: https://poshac.me/docs/v4/Guides/Using-an-Alternate-Config-Location/

**Comment by TiloGit** [comment]
here how to copy the entire folder:

```powershell
$vfcert = New-PACertificate 'dev1.mydom.com','myurl2.mydom.com' -Plugin WebSelfHost -PluginArgs @{} -AcceptTOS -Contact 'tilo@mydom.com'

$vfcertPath = Split-Path -Path $vfcert.CertFile -Parent

Copy-Item -R -Path $vfcertPath  -Destination C:\SSL-Certs\
```
