### ISSUE TITLE
Revoking a Cert

### ISSUE THREAD

**Issue by centuryx476** [rmbolger/Posh-ACME#11]
Hello,
I installed the module and it worked perfectly. I got my cert

How can I revoke the cert on the letsEncrypt servers ?
Is it possible ?
If so what commands do I type ?

Thanks

**Comment by rmbolger** [comment]
There are two options for revoking a cert. Both of these examples assume you already have the cert/order selected that you're going to revoke.  As in, running `Get-PAOrder` by itself returns the details for the cert to be revoked.

If you plan on re-issuing the cert at some point in the future and want to keep the order reference around, you can use:

```powershell
Set-PAOrder -RevokeCert
```

You can also remove the order entirely while also revoking the cert like this:

```powershell
Get-PAOrder | Remove-PAOrder -RevokeCert
```

Both of these should prompt for confirmation unless you also include the `-Force` switch.

**Comment by centuryx476** [comment]
Perfect
That did the trick...
