### ISSUE TITLE
Exception calling "GetInstance" with "1" argument(s)

### ISSUE THREAD

**Issue by NutellaDragon** [rmbolger/Posh-ACME#119]
When trying to run "New-PACertificate $auths.fqdn" I am met with this error. I have successfully requested the new cert, created the HTTP challenge file and get no errors on the previous line "$auths.HTTP01Url | Send-ChallengeAck".
This seems to be hit and miss on different Windows Server 2012R2 and 2016 and different certificate subject names. I cannot see an obvious common link. 

POSH-acme module is installed and "imported" and .NET 4.7.2 is installed.

Exception calling "GetInstance" with "1" argument(s): "unknown object in GetInstance"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\POSH-acme\Private\Import-Pem.ps1:50 char:9
+         $seq = [Org.BouncyCastle.Asn1.Asn1Sequence]::GetInstance($key ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

Any help would be much appreciated.

**Comment by rmbolger** [comment]
Hi there, @NutellaDragon. Sorry to hear you're having odd errors. Just wanted to let you know I started looking into this, but got side tracked a bit. I have a theory that revolves around how PowerShell presents the `$auths.fqdn` array to the function, specifically the order the names are in. 

My HTTP guide assumes (incorrectly) that the order of `$auths.fqdn` will match the order of the names you originally gave to `New-PAOrder`. But in order for the final `New-PACertificate` call to recognize and use the original order, the first name in `$auths.fqdn` also needs to be the first (primary) name you gave to `New-PAOrder` as well. If not, I think things might get wonky right now. But I need to find time to test it out.

**Comment by NutellaDragon** [comment]
I was only issuing a certificate to a single domain which I stored in $subject

New-PAOrder $subject -Install

If I run New-PACertificate $subject or New-PACertificate "url.domain.com", it throws the same error.

**Comment by rmbolger** [comment]
A single name certificate definitely throws my theory out (though I do need to update the guide now that I realize that's a problem). I may need to get a copy of some of the files in a cert order that's failing to test this further. I'll let you know.

Do the names that fail do so consistently? Or does this failure seem temporary such that if you start the process over with the same details, it may work the next time? Also, do any of the domains have unicode characters that would need translating to punycode?

**Comment by rmbolger** [comment]
So I'm pretty sure the error is happening when it tries to read the private key in order to generate the cert request file. Would you be willing to send me a copy of the private key from an order that's failing? I need to be able to reproduce the problem on my end.

It shouldn't be a security issue in this case because a cert was never successfully generated using it. And you can make sure it stays that way by deleting the order before trying again (which will generate a new key for the new order). To be clear, I need the `cert.key` file from the order folder in `%LOCALAPPDATA%\Posh-ACME\<server>\<account>\<order>`

**Comment by NutellaDragon** [comment]
There's no characters in the domain its all english words / characters separated by .

I can get you a cert.key file on Monday when I am back in the office. The one I am generating is for an IIS site. I'll try and grab another couple in the same state for an RDP server and VPN server. What is the best way to get them to you?

**Comment by NutellaDragon** [comment]
I have just send you 3 files from failures

**Comment by rmbolger** [comment]
I got them. Thanks. And unfortunately, I can't make them fail in the same way on any of my systems. The `Import-Pem` function has no trouble reading those keys. Can you try something for me on the systems that failed to see if we can reproduce the error at least on your side?

```powershell
# import the module to make sure the BouncyCastle library is loaded
Import-Module Posh-ACME

# dot source the Import-Pem function so we can use it directly
$mPath = (Get-Module Posh-ACME).Path
. (Join-Path $mPath.Substring(0,$mPath.LastIndexOf('\')) '\Private\Import-Pem.ps1')

# try importing the bad key file for that system
Import-Pem <path to key file>
```

I'm hoping you get the same error as before just so we can reproduce this. But if it works, you'll get output like this instead.

```
Public                                              Private
------                                              -------
Org.BouncyCastle.Crypto.Parameters.RsaKeyParameters Org.BouncyCastle.Crypto.Parameters.RsaPrivateCrtKeyParameters
```

If you do get the error, could you repeat the process with that same key file but on another system that doesn't seem to have the problem?

**Comment by NutellaDragon** [comment]
I am getting the same as you; if I copy the .key file to my machine and run Import-Pem against it, it returns what you specified. If I run the same on the problem servers, it fails in the same way :(

I have been doing some comparisons of working servers and non-working and I think I have found the issue. It appears to only affect servers where Sage 50 Accounts is installed. We have v24 so don't know if earlier versions affect in the same way or if the newer v25 fixes it.

I tested this by running posh-acme on a server which had a cert applied to it in December with no issues. Since then, Sage 50 has been installed. I ran it today and got the "Exception calling "GetInstance" with "1" argument(s)" failure. Removed Sage and re-ran New-Certificate $auths.fqdn - worked! The only change made was Sage being removed.

I have only tested the removal of Sage on 1 of the affected servers but the other failing servers do have Sage on them.

I am going to test (probably next week) if stopping the Sage services is enough to get around this.

I know this is not your area, but are you able to comment on why Sage might be affecting the BouncyCastle module?

**Comment by rmbolger** [comment]
I’ve never heard of that software before, but some quick googling indicates they might be using Bouncy Castle for crypto like Posh-ACME does. But they appear to be using a much older version of the library and if they install it into the system-wide GAC, PowerShell might choose to load that version instead of the copy included with the module. That’s my best guess at least.

The page I was reading indicated the library might only be used as part of the Sage Advisor Update component. So you might be able to remove just that and get things working again without removing the whole package.

**Comment by rmbolger** [comment]
That's not as old a version as I thought it would be. I'm surprised the difference in such a minor version change would even be causing this error.

In any case, I'm not really sure what to do about it. Posh-ACME's manifest file references a relative path to its own copy of BouncyCastle here:

https://github.com/rmbolger/Posh-ACME/blob/fb0f063675d5f8d4c73ba34ce5adf17d80632c5f/Posh-ACME/Posh-ACME.psd1#L28-L29

So if PowerShell is ignoring that and using a different copy somewhere else on the system, I'm not sure I have any way to fix that.

Can you verify whether Sage's copy is in the GAC or not? I think you can do something like this to check:

```powershell
cd C:\Windows\assembly
gci -recurse | ?{ $_.Name -like '*BouncyCastle*' }
cd C:\Windows\Microsoft.NET\assembly
gci -recurse | ?{ $_.Name -like '*BouncyCastle*' }
```

**Comment by NutellaDragon** [comment]
The dll's do not exist in the GAC so looks like posh-acme is not using the version specified or the Sage version is interfering somewhere. I did find a Sage BouncyCastle (it has 4) which is version 1.3.

**Comment by rmbolger** [comment]
I'm going to close this (with frustration) as cantfix because I'm not sure what I can do other than remove the BouncyCastle dependency entirely which probably won't happen for a while.
