### ISSUE TITLE
Allow specifying certificate Friendly Name

### ISSUE THREAD

**Issue by centuryx476** [rmbolger/Posh-ACME#12]
Hello,
Not really an issue but wanted to ask. 
Ive read the docs and which parameter can I use to name the Cert that is created. 
Currently when the cert gets outputted to the folder it is named "Cert" and when I import it into the certificate store its name is like a string of numbers. 
IS their a way to name the certificate ? 

Thanks

**Comment by rmbolger** [comment]
At the moment, no. 

The internal function that generates the PFX file does have a parameter to set the certificate "alias" which is what Windows turns into the Friendly Name field when you import it. But it's not currently exposed by `New-PACertificate` and as you noticed, just sets the alias to a random GUID value instead. That said, it wouldn't be terribly hard to add. So I'll take this as a feature request.

It's unlikely that you'll be able to set the name of the output files though. The intent there is that if you need to do something with those files like add a custom name or move them somewhere for an app/service to use, you copy them out of that folder and rename at the destination.

**Comment by centuryx476** [comment]
OK
Awesome...

Thank You

**Comment by rmbolger** [comment]
This is now merged into master pending release with v1.2
