### ISSUE TITLE
New-PACertificate BouncyCastle Error

### ISSUE THREAD

**Issue by atrandem** [rmbolger/Posh-ACME#121]
Getting the error when running New-PACertificate '*.domain.com' -AcceptTOS -Contact contact@.domain.com -DNSPlugin Manual

It got us through to do the TXT record, applied it and waited the default 2 minutes. Once it started again, the following error(s) was given.

Error: New-Object : Cannot find type [Org.BouncyCastle.Security.SecureRandom]: verify that the assembly containing this type is loaded.

![image](https://user-images.githubusercontent.com/44038114/51713671-5df1f800-1ff8-11e9-91c8-da20e8d16a6d.png)

We are using Windows 2016 x64

**Comment by atrandem** [comment]
I needed to use a computer/server with .Net 4.7.2 and this is resolved.

**Comment by rmbolger** [comment]
Technically, 4.7.1 would work as well. Glad you solved it.
