### ISSUE TITLE
Install flag doesn't properly import private key in some environments

### ISSUE THREAD

**Issue by thetrav** [rmbolger/Posh-ACME#122]
As per: https://github.com/MicrosoftDocs/windows-powershell-docs/issues/295

I seem to be able to use the imported certificate for IIS but not for RDS, not really sure what's up with that.

If I manually import fullchain from the GUI I can use it for RDS, but GUI is no fun

**Comment by rmbolger** [comment]
Are you using the native installation method (via the `-Install` parameter in the module) or manually via Import-PfxCertificate? Ultimately the native method is using that function under the hood so it shouldn't matter either way.

However, just to verify if you are doing it manually, are you giving it the PFX password in addition to the path to the file? That would be necessary in order for it to extract and import the private key.

```powershell
$mycert = Get-PACertificate

Import-PfxCertificate $mycert.PfxFullChain -Password $mycert.PfxPass
```

**Comment by thetrav** [comment]
I'm using the -Install parameter in the module.

Once I noticed the issues I played around with invoking Import-PfxCertificate myself with a few variations including specifying the password, finally I was able to get past it using the certutil program mentioned in the linked bug report:

```
certutil -f -p $certPassword -ImportPfx -enterprise $fullChainPath
```

Which is a bit gross, but at least it works.  So yes, this isn't really a blocker for me, I just thought I'd give you the heads up

**Comment by thetrav** [comment]
Oh sorry, forgot to mention, I'm using an azure 2019 server

**Comment by rmbolger** [comment]
Quick followup. You said you were able to use the cert for IIS but not RDS. How were you attempting to import into RDS? And is this a full fledged RDS setup or just remote admin mode?

**Comment by rmbolger** [comment]
Nevermind on the previous questions. I managed to reproduce this fairly reliably. I still can't figure out when MS broke `Import-PfxCertificate` or whether it's always been that way and I just never noticed.

In any case, the code I was using for downlevel OSes works just fine and doesn't exhibit the same problem. So I think I'm just going to change the internal function to use that everywhere.

**Comment by thetrav** [comment]
I know you said never mind, but it's a full fledged RDS setup, and I've been using powershell https://docs.microsoft.com/en-us/powershell/module/remotedesktop/set-rdcertificate?view=win10-ps
