### ISSUE TITLE
Add plugin system for HTTP challenges

### ISSUE THREAD

**Issue by ravensorb** [rmbolger/Posh-ACME#124]
Any thought to adding support for a single command for the HTTP Challenge like there is for the DNS challenge?

Maybe something like this?
```
New-PACertificate domain.com -AcceptTOS -Install -ChallengeType HTTP -HttpArgs @{Path="c:\inetserv\domain.com"}
```

**Comment by rmbolger** [comment]
Yes. Though it will likely take the form of a plugin system similar to the DNS plugins. In my head, I picture your example working with something like a FileCopy plugin where the plugin arguments are basically just a file path to copy the challenge files to and assumes a web server is already configured properly to route port 80 requests there.

Honestly not sure when I'll get around to it though.

**Comment by ravensorb** [comment]
I'd be ok with an either/or type scenario to start with.  Another idea might be to change from a "dns" model to a "challengeprovider" model and use one plugin framework with the idea that the plugin provide determines if it is meant for HTTP or DNS?

Related question -- I am attempting to use this process (https://github.com/rmbolger/Posh-ACME/wiki/%28Advanced%29-Manual-HTTP-Challenge-Validation) to do an HTTP challenge response and it is failing wit ha "no text record found" after the call to New-PACertificate 

Here is a gist with the script if you curious as to what I am doing -- https://gist.github.com/ravensorb/609bac4a14e864901661900f5eb39d0a

**Comment by ravensorb** [comment]
@rmbolger  any thoughts on the error for the HTTP challenge?

**Comment by rmbolger** [comment]
Apologies, I'm on vacation at the moment and not checking in with tech stuff much.

At first glance the error makes it seem like you ran the `Send-ChallengeAck` step against the DNS01Url property rather than the HTTP01Url property because the error from the ACME server is complaining about TXT records which it normally wouldn't for an HTTP challenge.

I'll see if I can look into it a bit more when I get back.

**Comment by rmbolger** [comment]
If you still have the failed order handy, can you post the output of `(Get-PAOrder | Get-PAAuthorizations).challenges.error | fl`? I'm curious if there are additional error details for the other challenge types.

**Comment by ravensorb** [comment]
It comes back with the same thing I had in the comment above -- 

```
type   : urn:ietf:params:acme:error:unauthorized
detail : No TXT record found at _acme-challenge.<FQDN>
status : 403
```

If it helps. here is the output from both Get-PAOrder

```
MainDomain       status  KeyLength SANs OCSPMustStaple CertExpires
----------       ------  --------- ---- -------------- -----------
<FQDN> pending 2048           False
```

Get-PAAuthorizations
```
identifier   : @{type=dns; value=<FQDN>}
status       : pending
expires      : 2019-03-02T16:23:03Z
challenges   : {@{type=dns-01; status=pending; url=https://acme-staging-v02.api.letsencrypt.org/acme/challenge/lpFiYoRwcJVtidU7rujxVjWQL2VgheXFf8JTTtDv3C8/252592893;
               token=jR-4QbfiaBVUBhfAdfhqgNmu0duzdVvUc_wzcbLIA_Y}, @{type=http-01; status=pending;
               url=https://acme-staging-v02.api.letsencrypt.org/acme/challenge/lpFiYoRwcJVtidU7rujxVjWQL2VgheXFf8JTTtDv3C8/252592894;
               token=n1YiB3-c0jxAsVkTlPqQ8c3gQG1SR4AqlYAUKqHrBvI}, @{type=tls-alpn-01; status=pending;
               url=https://acme-staging-v02.api.letsencrypt.org/acme/challenge/lpFiYoRwcJVtidU7rujxVjWQL2VgheXFf8JTTtDv3C8/252592895;
               token=bzpm8BE22J_Wj_5d-2KFXGBWPzkzzHN3rM-Ga8xds6k}}
DNSId        : <FQDN>
fqdn         : <FQDN>
location     : https://acme-staging-v02.api.letsencrypt.org/acme/authz/lpFiYoRwcJVtidU7rujxVjWQL2VgheXFf8JTTtDv3C8
DNS01Status  : pending
DNS01Url     : https://acme-staging-v02.api.letsencrypt.org/acme/challenge/lpFiYoRwcJVtidU7rujxVjWQL2VgheXFf8JTTtDv3C8/252592893
DNS01Token   : jR-4QbfiaBVUBhfAdfhqgNmu0duzdVvUc_wzcbLIA_Y
HTTP01Status : pending
HTTP01Url    : https://acme-staging-v02.api.letsencrypt.org/acme/challenge/lpFiYoRwcJVtidU7rujxVjWQL2VgheXFf8JTTtDv3C8/252592894
HTTP01Token  : n1YiB3-c0jxAsVkTlPqQ8c3gQG1SR4AqlYAUKqHrBvI
```
Custom object to write token out to a file
```
Url   : http://<FQDN>/.well-known/acme-challenge/n1YiB3-c0jxAsVkTlPqQ8c3gQG1SR4AqlYAUKqHrBvI
Token : n1YiB3-c0jxAsVkTlPqQ8c3gQG1SR4AqlYAUKqHrBvI
Body  : n1YiB3-c0jxAsVkTlPqQ8c3gQG1SR4AqlYAUKqHrBvI.z7aq_ohA3lPu_W_H3-_QP6ZVTYsaKE0TqCiftTO_LM0
```

**Comment by rmbolger** [comment]
I'm stumped. For that specific order, the ACME server is definitely indicating that it tried (and failed) to check the dns-01 challenge rather than the http-01 challenge. When a particular challenge fails for a name, it invalidates all challenges for that name on that order. But there's generally only error details on the challenge that actually failed. It also means you can't retry validating a different challenge type without first creating a new order. You can sort of see more clearly which challenge failed by just showing the output of `$auths.challenges`. I'm guessing there will only be an error property among the set for the dns-01 challenge. I'd be floored if it was in the set for http-01.

So moving on from this particular order. Can we try from scratch with a new order? You might want to change a couple things in your gist/script to deal with a previously failed order first.

On line 56, you can skip the `Where-Object` clause and just check for the domain in the `Get-PAOrder` command. You'll also want to add a `-Refresh` so you get updated details from the server like this:

```powershell
$order = Get-PAOrder $domainName -Refresh
```

On line 57, you'll want to add an invalid status check to the condition like this:

```powershell
if ($order -eq $null -or $order.status -eq 'invalid') {
```

**Comment by ravensorb** [comment]
That's the interesting part - I can reproduce this order and order.  I can do a remove-paorder and then run the script again with the exact same result.  The output above was from doing exactly that this morning.

Sanity check -- I am running this script against Lets Encrypt's stage env, would that make a difference? 

Note: Thanks for the tips - I just posted a few changes in the script.

**Comment by rmbolger** [comment]
Bleh, that's even more weird. And staging vs prod shouldn't make a difference unless something is really broken in staging. Just to verify I'm not crazy, can you post the output of `(Get-PAOrder -Refresh | Get-PAAuthorizations).challenges` or just verify whether the error message is associated with the dns-01 or http-01 challenge?

I'm also gonna go try again to repro this on my end.

**Comment by rmbolger** [comment]
It doesn't explain the DNS TXT related error you're getting, but one thing that might be causing issues is the Unicode encoding PowerShell uses by default with `Out-File`. In my own test, I had to add `-Encoding ascii` to your line 99 with the `Out-File`. I was getting "Invalid response from <blah>" errors until I fixed it.

But after that, everything works for me.

**Comment by ravensorb** [comment]
Here is the result

```
type   : http-01
status : invalid
url    : https://acme-staging-v02.api.letsencrypt.org/acme/challenge/GUSp0WJPTKYoG0JCSP2pQt9K-0zJLaDEdIjoPVZb0Yc/252656730
token  : lWpE_Hul6BY350kBv2h5hG3MddSBu1dlpQG-GvBq-II

type   : tls-alpn-01
status : invalid
url    : https://acme-staging-v02.api.letsencrypt.org/acme/challenge/GUSp0WJPTKYoG0JCSP2pQt9K-0zJLaDEdIjoPVZb0Yc/252656731
token  : l2xyS4BmHJW3xUzQpxi98XJYHkoR4LpujT6o5hutxU8

type   : dns-01
status : invalid
error  : @{type=urn:ietf:params:acme:error:unauthorized; detail=No TXT record found at _acme-challenge.<FQDN>; status=403}
url    : https://acme-staging-v02.api.letsencrypt.org/acme/challenge/GUSp0WJPTKYoG0JCSP2pQt9K-0zJLaDEdIjoPVZb0Yc/252656732
token  : E7plDVrLwUXea5X7VDOe7am8iiNTB9MUPE6G3y0liPQ

```

Question -- I just realized I am running 1 or 2 versions behind on Posh-ACME and am going to update just to make sure we are testing with the same version.

**Comment by ravensorb** [comment]
Ok, I should have upgraded to the latest build sooner :-/  Sorry about all of this.  When I did the Update-Module this morning and then just re-ran the script as is everything just worked.  I am guess there was a bug fixed at somepoint recently?

Question -- is there an easy way to get the version number of the currently installed Posh-ACME?

**Comment by rmbolger** [comment]
Glad to hear things are working now. There were definitely changes I had made within the past few versions to make doing manual HTTP challenges easier. But none I can think of should have caused something like this if they weren't applied. /shrug

Quickest way to get the version of a module I know of is like this:

```powershell
Get-Module -List Posh-ACME
```

**Comment by rmbolger** [comment]
The initial draft implementation is now done in the 4x branch.
