### ISSUE TITLE
Azure DNS Plugin: Unhelpful error when there are two public DNS Zones of the same name

### ISSUE THREAD

**Issue by crawfs** [rmbolger/Posh-ACME#125]
This is a similar issue to #112 except in this case it's when you have two Azure DNS zones of the same type that are both public. We ran into this issue when migrating our dev environment to a new resource group and received the following error:

`Add-DnsTxtAzure : Cannot process argument transformation on parameter 'ZoneId'. Cannot convert value to type System.String.`

I eventually figured out where the error was and $ZoneId had both the resoruceID of both dns zones @ 

`$rec = Get-AZTxtRecord $RecordName $zoneID`

As the "Get-AZTxtRecord" function expects a string but in this case $ZoneId had formatted as an array

I understand if you don't want to support the exceptionally arbitrary use case we experienced in this scenario but could the error message please be more descriptive. Thanks.

If you need any additional information please let me know

**Comment by rmbolger** [comment]
Oh wow, I didn't even realize Azure would let you create identical zones in different resource groups. How does it choose which copy is the "live" one? I might be able to use that to automatically pick the right one if it finds multiple.

In any case, I can definitely fix things to more gracefully deal with this. Short of being able to automatically pick the right copy, I might also be able to add an optional param that would let you specify the resource group.

**Comment by rmbolger** [comment]
> How does it choose which copy is the "live" one?

Nevermind. Looks like they just use different NS records which means you choose which one is live by updating the records at the registrar level.

I suppose it might be possible to query the authoritative NS records for the zone and check them against each of the copies in Azure (only when it finds a duplicate like this). Though that might be more trouble than it's worth for such an edge case.

As a short term workaround, it might also be possible to just tweak permissions so whatever account is being used to make the changes can only see the live one's resource group.

**Comment by rmbolger** [comment]
Ooh, what about applying a custom [tag](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags) to the live zone? That'd be way easier to deal with since I'm already getting the tag data while querying the zones for the ID lookup.

**Comment by rmbolger** [comment]
Ok, quick fix for better error handling is in. I also verified that removing service account permissions on the non-live zone's resource group is a valid workaround. I'll try to play around later this week with an alternate work around involving tags.

**Comment by crawfs** [comment]
You're a champion, thanks for the quick fix. Hopefully the next person to encounter this won't have to spend an hour reading through the module's code to determine what the problem is. Also I'd say if you're intent on allowing the script to resolve the issue a tag is the most hassle free way to go.

**Comment by rmbolger** [comment]
Ok, tag based workaround is in and I added a section to the usage guide about how to use it. I'll likely push a new module release later today.
