### ISSUE TITLE
Cloudflare - Invalid format for X-Auth-Key

### ISSUE THREAD

**Issue by chriscolden** [rmbolger/Posh-ACME#126]
Hi,

I've followed the simple instructions on the cloudflare documentation and get the following error.

Invoke-RestMethod : {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}

Powershell v6

If i run in Powershell v5 i get

invoke-restmethod : The remote server returned an error: (400) Bad Request.

Both running Posh-ACME v3.2.1

Many Thanks
Chris

**Comment by rmbolger** [comment]
Are you sure you entered your `CFAuthKey` value correctly? I just tested the plugin against my own account and it appears to be working. But I can reproduce that error by changing the key value to something like "asdf". For reference, my own key appears to be 37 characters comprised of numbers and lowercase letters.

**Comment by chriscolden** [comment]
Ok i feel dumb now. I have 38 chars. there was one on extra on the end. please close this.

**Comment by rmbolger** [comment]
Not a problem. Glad it was an easy fix. =)

**Comment by speedy76400** [comment]
Bonsoir,

J'ai un soucis voila le message d'erreur ==> 

[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6102,"message":"Invalid format for X-Auth-Email header"},{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}]

CFAuthKey : 37 chiffres, lettres j'ai comment faire svp ? 

Cordialement

**Comment by rmbolger** [comment]
Pouvez-vous poster un exemple du code que vous avez utilisé pour générer vos arguments de plugin? Avez-vous lu le [guide d'utilisation de Cloudflare](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Cloudflare-Readme.md)?

**Comment by speedy76400** [comment]
Bonjour,

C une intégration d'un add-on sur un forum de débrideur de liens. Quel code voulez vous ? 

Cordialement

**Comment by rmbolger** [comment]
Le code que vous avez utilisé pour obtenir ce message d'erreur.

**Comment by speedy76400** [comment]
Bonjour,

C n'est pas un code mais un add-ons pour un forum CMS XenForo voici le lien ==> 

https://le-paradis-du-net.fr/resources/cloudflare-for-xenforo.598/

Je vous les héberger si vous voulez bien jeter un coup d’œil svp : 

[https://www.mediafire.com/file/u3mnven4hd6lt4q/foro.agency-cloudflare-for-xenforo-v2.0.2.zip/file](url) 

Cordialement
