### ISSUE TITLE
Make it possible to configure the data storage folder for Posh-ACME

### ISSUE THREAD

**Issue by akunaatrium** [rmbolger/Posh-ACME#132]
Currently the data storage folder is hardcoded. When running Posh-ACME commands from a Docker container, the data is lost when the container is restarted. I would like the data to be persistent across container restarts and the way to do it would be to use bind mounts, so that the data is actually stored on the host.

The problem is that it is cumbersome and error prone to get the default locations to be included in the mapping.

A much preferred and cleaner approach IMO would be to somehow be able to specify a folder where Posh-ACME stores all its data, (like "C:\Data" or "/Data"), then the mapping would become very straightforward.

I would imagine the default locations be as they are but allow a method to override the location, using a separate command, e.g. `Set-PAStorageLocation -path <whatever>`.

**Comment by rmbolger** [comment]
You’re in luck. This is already supported as of version 3.2.0 by using the [POSHACME_HOME environment variable](https://github.com/rmbolger/Posh-ACME/wiki/%28Advanced%29-Using-an-Alternate-Config-Location).

**Comment by akunaatrium** [comment]
Oh, great, didn't notice that page. Thanks!
