### ISSUE TITLE
Add ZoneScope support to Windows plugin

### ISSUE THREAD

**Issue by dawe78** [rmbolger/Posh-ACME#134]
Is there a chance to add Split-Brain-DNS-Support in Posh-Acme for Windows DNS?

It should be easily possible by adding Parameter  -ZoneScope $splitBrainZone in windows.ps1 (Line 38, Add-DnsServerResourceRecord call) and set a parameter in New-PACertificate for $splitBrainZone.

Greets...

**Comment by rmbolger** [comment]
Hey @dawe78. Thanks for the request. It does sound like a fairly simple thing to add. I don't have an environment where I can test it though. So as long as you can test it for me, I'm happy to try and whip something up.

**Comment by rmbolger** [comment]
Here you go. Download this copy of the Windows plugin, and see if that works for you. Basically, just add the `WinZoneScope='blah'` to your existing plugin parameters.

https://raw.githubusercontent.com/rmbolger/Posh-ACME/win-zonescope/Posh-ACME/DnsPlugins/Windows.ps1

**Comment by dawe78** [comment]
Works great for me, thanks for this quick solution!!!

**Comment by rmbolger** [comment]
The change is now in the master branch pending a new release.
