### ISSUE TITLE
Route53 plugin not working with PowerShell Core

### ISSUE THREAD

**Issue by akunaatrium** [rmbolger/Posh-ACME#144]
When executing `Submit-ChallengeValidation -Order $order -DnsPlugin "Route53" -PluginArgs $route53arguments` (with correct values) the following error is output in the console:

```
Invoke-RestMethod : The format of value 'AWS4-HMAC-SHA256 Credential=blablahiddenblabla/20190520/us-east-1/route53/aws4_request, SignedHeaders=host;x-amz-date, Signature=a948b39d301795d50350eb8e812f62e314b31843402a00f5a2e90bcd95239958' is invalid.
At C:\ACME\Posh-ACME\DnsPlugins\Route53.ps1:494 char:25
```

It works correctly with regular PowerShell (version 5.1).

**Comment by akunaatrium** [comment]
The same error happens both on Windows (Server 2016) and on Linux (Ubuntu 16.04). On WIndows, the workaround is to use the desktop edition of PowerShell (not Core), but on Linux there is only Core available.

**Comment by akunaatrium** [comment]
This is talking about a similar error: https://github.com/PowerShell/PowerShell/issues/5818
Perhaps it gives some hints on how to fix it (like using -SkipHeaderValidation switch on Invoke-RestMethod but not sure, just shooting from the hips).

**Comment by rmbolger** [comment]
Oh man, sorry for the delay on responding to this. I totally thought I had and just not gotten around to fixing it yet. I actually ran into a similar issue with another of my modules. And yes, the `SkipHeaderValidation` switch is likely what's needed unless I can figure out why Core doesn't like the headers it's getting.

**Comment by rmbolger** [comment]
Until I get a long term fix, it looks like you can workaround the problem by installing the AwsPowerShell.NetCore module. The plugin will use that instead of raw Invoke-RestMethod calls which seems to work on my Ubuntu PowerShell 6.2.0 box.

**Comment by rmbolger** [comment]
Dev/master branch now has the fix. It'll be included in the next release.

**Comment by akunaatrium** [comment]
The fix works, thanks!
