### ISSUE TITLE
Rework Get-DnsPluginHelp to be more useful

### ISSUE THREAD

**Issue by rmbolger** [rmbolger/Posh-ACME#151]
I've never really liked how Get-DnsPluginHelp works. It's functional but awkward and I find myself just going to the plugin's nicely formatted usage guide rather than visually parsing the help output. Most of the time, I'm just looking for a quick reference on the plugin specific parameters.

I'm not sure where I really want to go with this though. A way to query those plugin specific parameters would be great. Even better would be a way to generate a sample hashtable with the parameters that the user could just set values on. A quick way to open a browser to the usage guide would also be nice.

**Comment by jhendricks123** [comment]
Maybe Get-DnsPlugins could return a list of hashtables like

@{
  Name='GoDaddy';
  ArgsTemplate=@{SomeArg='xxxx';}
}

Not sure about the help docs though. Maybe if the existing readme's were renamed and put side by side with the about_Posh-ACME.help.txt? Then you could do get-help *GoDaddy*? Or maybe you can already do that as-is, I'm on mobile at the moment.

**Comment by rmbolger** [comment]
The about* file is an interesting idea I hadn't thought of that and I'll definitely look into it more.

The ArgsTemplate is definitely something I want to do in some form. The trick is actually figuring out how to do it and account for the parameter sets most plugins have.

**Comment by rmbolger** [comment]
Progress! Been doing some work in the [4x branch](/rmbolger/Posh-ACME/tree/4x).

At the moment, `Get-DnsPlugins` and `Get-DnsPluginHelp` are gone and have been replaced by a new `Get-PAPlugin`.

* With no parameters, lists all plugins and the challenge types they support
* With just a plugin name, shows the details for that plugin
* With plugin name and `-Help`, shows the native help for the Add command
* With plugin name and `-Guide`, attempts to open the online guide in the default browser
* With plugin name and `-Params`, shows the plugin-specific parameter sets in a way that should be easy to consume programmatically but display nicely using a ps1xml based formatting.

The default `-Params` output currently looks like this.

```
PS > Get-PAPlugin Azure -Params


    Set Name: Credential (Default)


Parameter        Type         IsMandatory
---------        ----         -----------
AZSubscriptionId String       True
AZTenantId       String       True
AZAppCred        PSCredential True


    Set Name: CredentialInsecure


Parameter             Type   IsMandatory
---------             ----   -----------
AZSubscriptionId      String True
AZTenantId            String True
AZAppUsername         String True
AZAppPasswordInsecure String True


    Set Name: Token


Parameter        Type   IsMandatory
---------        ----   -----------
AZSubscriptionId String True
AZAccessToken    String True


    Set Name: IMDS


Parameter        Type            IsMandatory
---------        ----            -----------
AZSubscriptionId String          True
AZUseIMDS        SwitchParameter True
```

**Comment by rmbolger** [comment]
I think I'm gonna call this done for now based on how it's currently working in the 4x branch. I may revisit once I get closer to a release.
