### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mikemadeja** [rmbolger/Posh-ACME#155]
Wondering if this is possible..

For example, I don't see Verizon DNS plugin but I have a PowerShell module to update DNS for it.

```
$Object= New-PACertificate le-03.domain.xyz -AcceptTOS -Contact mike@domain.xyz -Install -Verbose

Write-Output $Object would result in below.

```

| TxtRecord        			| Value           	|
| ------------- 			|:-------------:	|
| _acme-challenge.le-03.madeja.xyz      | xVALUEofTXTRECORD 	| 

Then you can issue command like Get-PACertificateTxtRecordStatus $Object and get some result back and then Commit it?

Sorry if I missed this capability but I did not see it.

Thoughts?

**Comment by rmbolger** [comment]
I don’t quite understand what you’re asking. Are you saying you already have a PowerShell module to update Verizon DNS and you want to make a Posh-ACME plugin using it? Or just that you’d like someone to make a plugin for Verizon DNS?

There is no plugin currently available for Verizon DNS that I know of.
