### ISSUE TITLE
Feature Request: Install-PACertificate

### ISSUE THREAD

**Issue by jhendricks123** [rmbolger/Posh-ACME#159]
The New-PACertificate cmdlet with -Install is great, but if you're manually running the commands and forget the -Install switch, you have to either find/install the pfx manually on Windows, or rerun New-PACertificate.

I'd like to be able to call Install-PACertificate and if I supply no parameters, it takes the output of Get-PACertificate and installs the PFX accordingly, or be able to take pacertificate objects from the pipeline.

**Comment by rmbolger** [comment]
I like the idea and I get where the request comes from. The *only* problem I have with this is that it feels weird to include a function that will only work on Windows. On non Windows machines, I'm trying to decide whether it should throw an error or just a warning and be effectively a no-op.

Would it make sense to include a parameter set that would enable a file copy type install for non-Windows OSes? And in that case, should the option somehow be included with New-PACertificate as well? It's probably easier to stick with the simple case for now.

**Comment by jhendricks123** [comment]
I'm not very familiar with non-Windows OS's and the different ways certificates might be handled there. I can understand the hesitancy. In my opinion, the -Install switch already breaks that strict cross-platform approach, but in a way that is really useful for probably most of the user base and unobtrusive for non-Windows users.

Likewise, I think having Install-PACertificate be a no-op with a Write-Warning would be informative to curious non-Windows users, but if there's some work that command could do which makes sense in a non-Windows environment, that'd be even better.

**Comment by rmbolger** [comment]
I agree. Just wanted to roll the idea around in my head to see if it made sense to include more functionality into this.

**Comment by rmbolger** [comment]
Ok, `Install-PACertificate` has been added in the master dev branch. `New-PACertificate` has also been updated to use it internally as well. Give it a go and see how it works for you. Everything seems to be happy in my tests so far.

**Comment by jhendricks123** [comment]
That's awesome, thanks! Hopefully there's a logical way to make that cmdlet cross platform but I'll definitely make use of this on Windows.
