### ISSUE TITLE
Feature Self-hosted HTTP challenge

### ISSUE THREAD

**Issue by Soltroy** [rmbolger/Posh-ACME#160]
I've stumbled across this module  and did some testing to see if it fits me needs.
Output of this is a function that
- accepts data from either a present (Get-PAAccount) or as parameters/pipe,

for every domain
- starts a httpListener with challenge data
- after every response, status of challange ist checked. If valid, listener stops
- if nothing happens listener stops automaticly after a given time (default 120 seconds)

Not perfect ATM but technically working.
Let me know if this would be worth a pull - if so I'll do refining and future improvements with module integration in mind.

**Comment by rmbolger** [comment]
I can definitely see this being useful once I get a model for HTTP challenge plugins going which is on the road map for 4.x. Would this work cross platform on Linux/Mac as well?

**Comment by Soltroy** [comment]
Guess so, all testing by far is done within Linux docker containers running ps core stable - therefore mac will work. too. ARM/Rasperry will be testet in final stage. Cross Platform is definitely a must for a pull, need this by myself.

**Comment by rmbolger** [comment]
Perfect. Love it.

**Comment by rmbolger** [comment]
Conversation continues in PR #161

**Comment by rmbolger** [comment]
`Invoke-HttpChallengeListener` is now live in 3.6.0
