### ISSUE TITLE
Support ClouDNS is-updated API call instead of timeout

### ISSUE THREAD

**Issue by kmccormick** [rmbolger/Posh-ACME#166]
ClouDNS has an API endpoint that will return true once all its servers have been updated (https://www.cloudns.net/wiki/article/54/). I'd rather poll that every 5 seconds than wait 120 (or any other number) seconds, especially since the time to fully update can sometimes vary quite a bit.

I took a quick look but it seems the countdown/timeout happens outside the individual DNS plugin. I'm happy to work on a pull request but I'd appreciate if you can point me in the right direction.

**Comment by rmbolger** [comment]
The sleep timer does indeed happen outside the plugin's purview. However, you could probably hack something into the `Save-DnsTxtClouDNS` function that does the polling. The sleep doesn't start until the Save function finishes (following the Add function for each name in the cert order). Then, you can just set your DnsSleep value for that order to 0 or something small.

I was actually hoping to add some sort of best-effort DNS based check that would work across all plugins in 4.x. But obviously something like this that's supported at the API level is likely way more reliable.

**Comment by rmbolger** [comment]
ClouDNS was nice enough to give me a new 30-day trial so I could try implementing this request myself. Things appear to be working on my end.

See the updated usage guide for details, but the gist of how it works is that you add `CDPollPropagation=$true` to your pluginargs. If ClouDNS is the only plugin you're using the cert, you can then also add `-DnsSleep 0` to your `New-PACertificate` command.

I'm hoping to get a new release out with this and a bunch of other stuff that's been piling up in the next few days.
