### ISSUE TITLE
Multiple Wildcard Certs

### ISSUE THREAD

**Issue by darkvirus** [rmbolger/Posh-ACME#169]
Hello, im trying to request a single certificate with 10 SAN names and 10 Wildcard names, but i am getting the error below

New-PACertificate -Domain '*.test.nz, *.test1.nz -AcceptTOS -Contact admin@test.nz -DnsPlugin Windows -PluginArgs @{WinServer='dns.test.nz'} -Verbose -Force

Error creating new order :: Cannot issue for "*.test.nz, *.test1.nz": DNS name had more than one 
wildcard

According to LetsEncrypt they support up to 100 names of which all or none of them can be wildcards.

Am i missing a flag of some sort or am i doing it wrong?

**Comment by rmbolger** [comment]
No worries. It sounds like you accidentally specified the Domain parameter as a single comma delimited string instead of an array of strings.

```powershell
# This is wrong
-Domain '*.test.nz, *.test1.nz'

# This is right
-Domain '*.test.nz','*.test1.nz'

# This is a more verbose way that may also make it more clear
$domains = @( '*.test.nz', '*.test1.nz' )
-Domain $domains
```

**Comment by darkvirus** [comment]
Yes, it turns out after making it work on the first run i changed the syntax i was using.

PEBKAC
