### ISSUE TITLE
Fix Azure documentation

### ISSUE THREAD

**Issue by Leon99** [rmbolger/Posh-ACME#177]
From https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Azure-Readme.md:
> Note: Specifying the username/password in plain text is required on non-Windows OSes due to this bug in PowerShell Core.

It looks like https://github.com/PowerShell/PowerShell/issues/1654 has already been fixed.

**Comment by rmbolger** [comment]
Indeed. There are a bunch of these that need to be updated. But thanks for the heads up! This one's fixed now.
