### ISSUE TITLE
PFX is exported with wrong password via New-PACertificate

### ISSUE THREAD

**Issue by arestarh** [rmbolger/Posh-ACME#178]
Hi,

Thanks for the great module!

_Powershell version_: **5.1**
_Module version_: **3.7.0**
_OS version_: **Windows 10**
_.NET version_: **4.8**

**Note**:

1. Seems like with Module version **3.6.0** I didn't experience issue described below.
2. Seems like if I use **New-PACertificate** and explicitly specify password that match default 'poshacme' or use default 'poshacme' one I don't experience issue described below.
3. Seems like error message specified below refer to wrong password.

I've tried to issue certificate and export PFX via **New-PACertificate** with custom password and experienced an issue"**Exception calling "Import" with "3" argument(s): "The specified network password is not correct.**.

Next script to issue certificate was finished **OK** (via using **New-PAOrder** to specify custom password):

```powershell
#Option 1 (PFX Password set via New-PAOrder cmdlet)
[string]$LetsEncryptServerType = "LE_STAGE"
[string]$domain = "domain1.example.com"
[string]$EmailAddress = "username@example.com"

# Explicitly set how PowerShell responds to a non-terminating error
$ErrorActionPreference = 'Stop'

# Let's Encrypt Server Selection
Set-PAServer -DirectoryUrl $LetsEncryptServerType

# Let's Encrypt Account Setup (including checking if among email address(es) we have empty strings, and omit them)
New-PAAccount -AcceptTOS -Contact $EmailAddress -KeyLength 2048 -Force

# Let's Encrypt Create an Order
$CertificatePassword = [System.Web.Security.Membership]::GeneratePassword(15,10)
New-PAOrder -Domain $domain -PfxPass $CertificatePassword

# Let's Encrypt Authorizations and Challenges
$auths = Get-PAOrder -Refresh -MainDomain $domain | Get-PAAuthorizations

<#
Publish Challenge somewhere LetsEncrypt servers can access
#>

# Let's Encrypt Notify the ACME Server
$auths.HTTP01Url | Send-ChallengeAck

$IssuedCertInfo = New-PACertificate -Domain $domain

# Get certificate info
$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
$cert.Import($IssuedCertInfo.PfxFullChain,$CertificatePassword,'DefaultKeySet')
$cert | Format-List -Property *
```

Next script to issue certificate was finished **with error** specified above (via using **New-PACertificate** to specify custom password):

```powershell
#Option 2 (PFX Password set via New-PACertificate cmdlet)
[string]$LetsEncryptServerType = "LE_STAGE"
[string]$domain = "domain1.example.com"
[string]$EmailAddress = "username@example.com"

# Explicitly set how PowerShell responds to a non-terminating error
$ErrorActionPreference = 'Stop'

# Let's Encrypt Server Selection
Set-PAServer -DirectoryUrl $LetsEncryptServerType

# Let's Encrypt Account Setup (including checking if among email address(es) we have empty strings, and omit them)
New-PAAccount -AcceptTOS -Contact $EmailAddress -KeyLength 2048 -Force

# Let's Encrypt Create an Order
New-PAOrder -Domain $domain

# Let's Encrypt Authorizations and Challenges
$auths = Get-PAOrder -Refresh -MainDomain $domain | Get-PAAuthorizations

<#
Publish Challenge somewhere LetsEncrypt servers can access
#>

# Let's Encrypt Notify the ACME Server
$auths.HTTP01Url | Send-ChallengeAck

$CertificatePassword = [System.Web.Security.Membership]::GeneratePassword(15,10)
$IssuedCertInfo = New-PACertificate -Domain $domain -PfxPass $CertificatePassword

# Get certificate info
$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
$cert.Import($IssuedCertInfo.PfxFullChain,$CertificatePassword,'DefaultKeySet')
$cert | Format-List -Property *
```

**Comment by rmbolger** [comment]
Hi @arestarh. Thanks so much for the detailed report. I think I've tracked down the problem and it looks like this is a new bug that was caused by a fix (3c3d245) in 3.7.0.

Prior to the fix, the internal function that generates the Pfx files was accidentally using some of the parameters originally passed to New-PACertificate rather than the parameters from the order. When I fixed that, it caused this new bug when you use New-PACertificate with an existing order because it's not properly setting those parameters on the order.

I've got a pretty good idea what I need to do, but I'm out of town this weekend. So I may not be able to push a fix until next week.

**Comment by rmbolger** [comment]
Yay, got the fix in just before I've gotta run. Feel free to test the dev/master version and see if this fixes your problem. It seems to be working as expected now on my end.

**Comment by arestarh** [comment]
@rmbolger Thanks for the quick fix.
Is it OK if I test next release build once it arrived ?

**Comment by rmbolger** [comment]
You can actually test right now either downloading a zip of the master branch from github or using the Development install instructions from the readme.

**Comment by j81blog** [comment]
I experienced the issue as well, tried the changed version from github and I can verify that the issue is solved. When will the new version be available on  the powershellgallery?

**Comment by rmbolger** [comment]
@j81blog Just pushed 3.8.0 to the gallery. Glad to hear the fix is working.

**Comment by j81blog** [comment]
@rmbolger thank you for al your work!

**Comment by Cedric-Bravo** [comment]
Seem the bug is coming back with the latest version.
The password i get into the order file does not work.

**Comment by Cedric-Bravo** [comment]
Seem that if you didn't provide password, the default password is "poshacme"... even if you see a password set into the order file.

**Comment by rmbolger** [comment]
Hey @Cedric-Bravo. Thanks for report. What version of Posh-ACME is this happening with? If it's in 4.0.0, can you post this in a new issue to make it easier to track?
