### ISSUE TITLE
GoDaddy plugin fails to find associated zone when domains on the account exceed 100

### ISSUE THREAD

**Issue by nemchik** [rmbolger/Posh-ACME#179]
I'm having issues trying to get a cert created. I've set my system to use `Set-PAServer LE_STAGE` while confirming the issue. Here's what I'm trying to do and the output I'm seeing.

---

C:\WINDOWS\system32> `Get-Module -ListAvailable -Name Posh-ACME`
```

    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.7.0      Posh-ACME                           {Get-DnsPluginHelp, Get-DnsPlugins, Get-KeyAuthorization, ...

```
C:\WINDOWS\system32> `$email = 'me@mymail.com'`
C:\WINDOWS\system32>
C:\WINDOWS\system32> `$domains = 'mydomain.com', '*.mydomain.com'`
C:\WINDOWS\system32> `$pArgs = @{GDKey='filled out';GDSecret='filled out'}`
C:\WINDOWS\system32> `$certOutput = (New-PACertificate $domains -DnsPlugin GoDaddy -PluginArgs $pArgs -Install -AcceptTOS -Contact $email -verbose *>&1)`
```
Invoke-RestMethod : {"code":"NOT_FOUND","message":"Not Found : The requested resource was not found"}
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.7.0\DnsPlugins\GoDaddy.ps1:30 char:17
+ ...     $recs = Invoke-RestMethod "$apiRoot/$zone/records/TXT/$recShort"  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```
C:\WINDOWS\system32> `$certOutput`
C:\WINDOWS\system32>

---

I've removed POSH-Acme and reinstalled using `Uninstall-Module Posh-ACME -AllVersions` and `Install-Module Posh-ACME`

I'm not sure what's going on with this?

**Comment by nemchik** [comment]
P.S. I read through https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/GoDaddy.ps1 as much as I could and tried to write out the command that I think is failing with all the variables inline and came up with `Invoke-RestMethod "https://api.godaddy.com/v1/domains/mydomain.com/records/TXT/mydomain.com" -Headers @{Authorization = "sso-key key:secret"} -UseBasicParsing -EA Stop` which did work for me, but I may not be piecing that together the right way.

**Comment by rmbolger** [comment]
Hi @nemchik. Thanks for the report. I may not be able to look into it until next week as I'm out of town this weekend. But didn't want to leave you hanging with no response.

**Comment by rmbolger** [comment]
Ok, so I reviewed the GoDaddy plugin's code and ran some tests on my own account after picking up a new cheap domain. While it seems to be working for me as-is, I did find some ways to improve the code with better error handling and changing how the zone search is done a tiny bit.

Ultimately though, the error you got indicates the plugin couldn't find a domain in the API results to match list of domains you sent. Here's an easy way to test just the plugin functionality without messing around with the certificate stuff.

```powershell
# Turn on debug output
$DebugPreference = 'Continue'

$pArgs = @{GDKey='filled out';GDSecret='filled out'}
Publish-DnsChallenge mydomain.com (Get-PAAccount) faketoken GoDaddy $pArgs -Verbose
```

Among the DEBUG output in the current dev version should now be a line that looks like `ACTIVE Zones found: domain1.com, domain2.com, domain3.com, etc`. If you don't see your `mydomain.com` in the list, it means GoDaddy doesn't consider it an "active" domain on the account associated with the Key/Secret you provided. If you see it listed in your dashboard and can manipulate DNS records for it from the web UI, it's possible the domain has a status value that the plugin is ignoring by mistake. If so, see if you can get the full list of domains and statuses like this.

```powershell
$h = @{Authorization = "sso-key key:secret"}
$url = 'https://api.godaddy.com/v1/domains'
Invoke-RestMethod $url -Headers $h | %{ $_ } | select domain,status
```

**Comment by nemchik** [comment]
I may have found the issue. Using the instructions at the end of your comment (`Invoke-RestMethod $url -Headers $h | %{ $_ } | select domain,status`) I found only the first 100 domains on my account are returned. I have more than double that. The domain I'm trying to get a cert for must have been returning in the top 100 prior to purchasing new domains recently.

Their API documentation does mention a limit that can be specified https://developer.godaddy.com/doc/endpoint/domains#/v1/list

I have tested this and get all of my domains:

```powershell
$h = @{Authorization = "sso-key key:secret"}
$url = 'https://api.godaddy.com/v1/domains?limit=1000'
Invoke-RestMethod $url -Headers $h | %{ $_ } | select domain,status
```

And in that list the domain I'm trying to get a cert for is listed as ACTIVE.

I don't think I am an outlier with the number of domains managed by this account, but I also don't think just throwing in a hard coded higher limit is necessarily the right answer. I found https://developer.godaddy.com/doc/endpoint/subscriptions#/v1/productGroups which to returns:

```json
[
  {
    "productGroupKey": "domains",
    "subscriptionCount": 3765
  },
  {
    "productGroupKey": "hosting",
    "subscriptionCount": 175
  },
  {
    "productGroupKey": "wordpress",
    "subscriptionCount": 657
  }
]
```

But I don't know where those numbers are coming from, I don't have anywhere near that volume of any of those products.

**Comment by rmbolger** [comment]
Hah, yep. That would do it. Check out this comment in the plugin source:

https://github.com/rmbolger/Posh-ACME/blob/8ebfa4ff61ecee974881b291f3fff648f9ca6990/Posh-ACME/DnsPlugins/GoDaddy.ps1#L238-L241

Unfortunately, my own account is quite small so I (and probably the original author of the plugin) couldn't test what happens with large accounts or how to work around the issue. Based on your research, it seems like the default limit is 100 results, but it will allow you to request more which seems like an odd design choice.

The annoying thing is that the response doesn't give any indication that there are more results to get or how many pages there might be.

Let me see if I can work around this problem by making the zone finding function work more like some other plugins where instead of getting a list of all zones and searching through it, it just tries to get the details for a specific zone and handles whatever errors happen if it's not found. It's a few more server API round trips (particularly for a name that contains multiple sub-zones). But it tends to be far more reliable and doesn't suffer from account size limitations like the current method does.

**Comment by rmbolger** [comment]
Ok, the fix is in master. Give it a try when you have a chance.

**Comment by nemchik** [comment]
Seems to have worked.

**Comment by rmbolger** [comment]
Nice. I'm not exactly sure when the next release will go out. But this will definitely be in it.
