### ISSUE TITLE
The property 'CFToken' cannot be found on this object

### ISSUE THREAD

**Issue by Jackbennett** [rmbolger/Posh-ACME#182]
```powershell
New-PACertificate -Contact 'email@example.com' -Domain @('example.com') `
    -CertKeyLength 'ec-384' -AcceptTOS -DirectoryURL 'LE_STAGE' -DNSPlugin 'CloudFlare' -PluginArgs @{ 'CFToken' = $token_key }


The property 'CFToken' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\posh-acme\3.8.0\Private\Export-PluginArgs.ps1:94 char:9
+         $pData.$key = $PluginArgs.$key
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
```

I must be doing something stupid but I can't see why this is throwing a problem. $Token_key is most definitely set.

doesn't work splatting either;

![image](https://user-images.githubusercontent.com/791134/66660766-b415d280-ec3d-11e9-8497-3dd7205c1985.png)

Any thoughts what else I could check?

**Comment by rmbolger** [comment]
Hey @Jackbennett. Thanks for the report. If I'm reading the error message correctly, I think the object it's referring to is the $pData variable on the left rather than the $PluginArgs variable on the right. But that variable is supposed to be a hashtable which normally allows you to assign new values to keys that don't exist. The only time it wouldn't if it was actually null.

I have a theory about what might be happening. Let me see if I can reproduce it on my end.

**Comment by rmbolger** [comment]
So I think what happened is that the plugindata.xml file in your account profile got corrupted somehow. Either it was an empty file or the data in it ultimately imported as null or something other than the hashtable the code was expecting.

I've added a fix that should better handle unexpected input from the plugindata file and seems to fix this issue on my end. If you can confirm it fixes the problem on your end, I'll push a quick bug fix release.

**Comment by Jackbennett** [comment]
I will try for you on monday when I get back to that server.

Now you mention that, the xml file got corrupted then when I first tried this over a ps remote session and the command failed at Export-clixml talking about account delegation issues. I didn't feel like fixing that so hopped onto RDS instead.

I'll see if that error is in my logs too if you want, it should be I'm fairly sure that's all turned on.

**Comment by Jackbennett** [comment]
Yeh I just looked, the plugindata.xml was

```xml
<?xml version="1.0"?>
<Objs xmlns="http://schemas.microsoft.com/powershell/2004/04" Version="1.1.0.1">
    <Nil>
</Objs>
```
