### ISSUE TITLE
New-PACertificate attempting to use Manual plugin when it should be completing an order.

### ISSUE THREAD

**Issue by mregni** [rmbolger/Posh-ACME#187]
Hi,

Thanks for your implementation of ACME in for powershell! 
I'm currently trying to use it in an Azure Automation Account Runbook and had a question about the popups. Is there a way to disable them or suppress them?

This because Runbooks can't handle any user interaction. When my scripts gets to this command `New-PAAccount -AcceptTOS -Contact $EmailAddress`, it will crash the run with following error:
```Read-Host : A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: At C:\Modules\User\Posh-ACME\DnsPlugins\Manual.ps1:98 char:9 + Read-Host -Prompt "Press any key to continue." ```

I'm using the manual mode, the Runbook will upload the challenge file to a blob storage and  save the pfx file received from the `New-PACertificate` call to an Azure Application Gateway. All this is working already, just need to disable the user interaction.

Any idea how I can do that?

**Comment by mregni** [comment]
I was wrong, it's not a popup (looks like you can suppress them with -Force) but it's just about the "Press any key to continue." message :)

**Comment by mregni** [comment]
Sorry for being confusing :) I'm kind of new in the whole ACME story.

I'll just include my script so you can see what I'm trying to do

```
Set-PAServer LE_STAGE
New-PAAccount -AcceptTOS -Contact $EmailAddress -KeyLength 2048 -Force
New-PAOrder $domain -Force

$auths = Get-PAOrder | Get-PAAuthorizations
$authData = $auths | Select @{L='Body';E={Get-KeyAuthorization $_.HTTP01Token (Get-PAAccount)}},
                            @{L='FileName';E={$($_.HTTP01Token)}}

$filePath = $env:TEMP + "\" + $authData.FileName
Set-Content -Value $authData.Body -Path $filePath

$storageAccount = Get-AzureRmStorageAccount -ResourceGroupName $STResourceGroupName -Name $storageName
$blobName = ".well-known\acme-challenge\" + $authData.FileName
$ctx = $storageAccount.Context

set-azurestorageblobcontent -File $filePath -Container $containerName -Context $ctx -Blob $blobName

$auths.HTTP01Url | Send-ChallengeAck
$cert = New-PACertificate $domain

Remove-AzureStorageBlob -Container $containerName -Context $ctx -Blob $blobName

$appgw = Get-AzureRmApplicationGateway -ResourceGroupName $AGResourceGroupName -Name $AGName
$password = ConvertTo-SecureString -String $CertificatePassword -Force -AsPlainText
set-azureRmApplicationGatewaySSLCertificate -Name $AGOldCertName -ApplicationGateway $appgw -CertificateFile $cert.PfxFullChain -Password $cert.PfxPass
Set-AzureRmApplicationGateway -ApplicationGateway $appgw
```
I indeed tried to follow the Manual HTTP Challenge Validation wiki page. 
Could the -NewKey maybe help me? I'll have a look asap.

**Comment by rmbolger** [comment]
This looks pretty good and I think you're really close. The problem may be that you're not waiting long enough after the `Send-ChallengeAck` call. There's going to be a non-zero amount of time (depending on the number of authorizations and server load) before the ACME server is able to validate the challenges and update the order status to "ready" (or "invalid" if something went wrong). So when you call `New-PACertificate` too soon, it checks the order state, sees it has work to do, and starts trying to use the Manual DNS plugin.

You can either just insert a simple `Start-Sleep` for some amount of time that seems reasonable or start a polling loop where you periodically check the status of the order or authorizations every few seconds (which is what the module does internally when you're using a DNS plugin). In retrospect, it would probably be nice to make the internal function that does this public so people could just use it in their scripts. Until I can get around to doing that, here's the code in case you want to make your own version.
https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/Private/Wait-AuthValidation.ps1

But essentially, you need to add a bit of code that prevents the `New-PACertificate` call from running until the order status equals "ready". I should probably update the guide to mention this as well.

**Comment by mregni** [comment]
Just had a look at your code and I changed my script a bit so I could use the Wait-AuthValidation mechanism. It's all running nicely now on my Azure Automation Account 😄

Thanks for the help!!

**Comment by rmbolger** [comment]
Excellent. Happy to help. I'll work on clarifying the guide as well and look into making that wait function public.

**Comment by rdvansloten** [comment]
> Just had a look at your code and I changed my script a bit so I could use the Wait-AuthValidation mechanism. It's all running nicely now on my Azure Automation Account 😄
> 
> Thanks for the help!!

Running into the same issue with my Runbook, any chance you'd be willing to share your revised, working code? 🙂 Adding a simple Start-Sleep in my Runbook doesn't seem to work that well.
