### ISSUE TITLE
Update Azure documentation to use Az Module

### ISSUE THREAD

**Issue by mikes-gh** [rmbolger/Posh-ACME#189]
https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Azure-Readme.md

Here AzureRM module is used.
However this is no longer developed

See

https://docs.microsoft.com/en-us/powershell/azure/azurerm/install-azurerm-ps?view=azurermps-6.13.0

Suggesting to use Az module instead which is what I use.

do you think it is worth changing the docs?

**Comment by rmbolger** [comment]
Hi @mikes-gh. Yes here too. It's another thing I'd been meaning to get around to doing and I'll definitely update the docs with the addition of the cert based principal auth in #190.

**Comment by rmbolger** [comment]
This is complete.
