### ISSUE TITLE
Certificate authentication for Azure plugin

### ISSUE THREAD

**Issue by mikes-gh** [rmbolger/Posh-ACME#190]
Would you consider adding cert auth for service principles

https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell

I have a few on prem servers I need to request certificates for and it seems the best option

**Comment by rmbolger** [comment]
Hi @mikes-gh. Yes. I'd been meaning to get around to this so I'm glad someone asked for it. Cert based service principals didn't exist when I originally wrote the plugin.

**Comment by rmbolger** [comment]
Ok @mikes-gh, preliminary support for cert auth is now in the dev/master branch. Feel free to give it a try. The [user guide](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Azure-Readme.md) has details on setting things up. There are some particulars regarding how the certificate is created that can cause errors if you're not careful like the cryptographic storage provider selection. The process is also different whether you're on Windows or non-Windows.
