### ISSUE TITLE
Unable to connect to the remote server error

### ISSUE THREAD

**Issue by Z-Iain** [rmbolger/Posh-ACME#191]
Just installed Posh-ACME for the first time on a 2008 R2 server.  Confirmed .Net 4.7.2 and powershell 5.1 both installed.  When I run "New-PACertificate www.domain.com" I get the following:

```
Invoke-WebRequest : Unable to connect to the remote server
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.9.0\Private\Update-PAServer.ps1:47 char:29
+ ... $response = Invoke-WebRequest $DirectoryUrl -EA Stop -Verbose:$false
```

Have I missed something?

**Comment by rmbolger** [comment]
That error indicates a network problem between your host and the Let's Encrypt servers. Do you have any firewalls that block outbound traffic to the Internet? Are there any proxy servers in place that the Let's Encrypt servers would need to be white listed on?

It's also possible (though unlikely) the Let's Encrypt servers were down when you made the attempt. You can check the [status page](https://letsencrypt.status.io/) the next time you try to make sure.

If you want an easy test to try without getting the module involved, try this.

```powershell
Invoke-RestMethod https://acme-v02.api.letsencrypt.org/directory
```

The output should look something like this and shouldn't generate an error message.

```
OH1hx4ILkAA : https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417
keyChange   : https://acme-v02.api.letsencrypt.org/acme/key-change
meta        : @{caaIdentities=System.Object[];
              termsOfService=https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf;
              website=https://letsencrypt.org}
newAccount  : https://acme-v02.api.letsencrypt.org/acme/new-acct
newNonce    : https://acme-v02.api.letsencrypt.org/acme/new-nonce
newOrder    : https://acme-v02.api.letsencrypt.org/acme/new-order
revokeCert  : https://acme-v02.api.letsencrypt.org/acme/revoke-cert
```

**Comment by Z-Iain** [comment]
Thanks for the pointer.  It looks like it is a network issue, the server can't reach that address for some reason, although other websites are fine.  Now i know where it's referring to I will liaise with the ISP.

And thanks about the EOL for Server 2012 R2, we do have a project in place, just haven't got to that point yet.
