### ISSUE TITLE
Share PAAccount

### ISSUE THREAD

**Issue by mikes-gh** [rmbolger/Posh-ACME#194]
Can I share an PAAccount between installations?
Maybe by copying the acct.json

**Comment by mikes-gh** [comment]
See https://letsencrypt.org/docs/integration-guide/

> One Account or Many?
In ACME, it’s possible to create one account and use it for all authorizations and issuances, or create one account per customer. This flexibility may be valuable. For instance, some hosting providers may want to use one account per customer, and store the account keys in different contexts, so that an account key compromise doesn’t allow issuance for all of their customers.
However, for most larger hosting providers we recommend using a single account and guarding the corresponding account key well. This makes it easier to identify certificates belonging to the same entity, easier to keep contact information up-to-date, and easier to provide rate limits adjustments if needed. We will be unable to effectively adjust rate limits if many different accounts are used

**Comment by rmbolger** [comment]
Yes. The only thing to be wary of is the plugindata.xml file if you're on Windows and using any plugin parameters that are a PSCredential or SecureString value. Those values are encrypted using keys tied to both the user and computer they were saved on.

If you need to reset those values in the new location, there's currently no easy way to do it at the moment without having to create a new order either via `Submit-Renewal -PluginArgs <blah>` or `New-PAOrder` followed by `Submit-ChallengeValidation -DnsPlugin <blah> -PluginArgs <blah>`. I should definitely add some better ways to deal with this. Technically, it's just a PowerShell hashtable exported via `Export-CliXml`, so you could just re-create it manually as well.

**Comment by mikes-gh** [comment]
Thanks.  So given I just want to reuse the account what the minimum file structure required.  I sort of lookimng for a template directory/file structure to place in POSH_HOME form where I can start a New-PACeretificate.

**Comment by rmbolger** [comment]
Bare minimum that should enable immediate use of `New-PACertificate` without any saved plugin arguments should look like this.

```
current-server.txt
acme-v02.api.letsencrypt.org\
    current-account.txt
    dir.json
    <account id>\
        acct.json
```

If you wanted to pre-populate plugin arguments as well, just create a hashtable just like the one you'd use with `-PluginArgs` and use `Export-CliXml` to output the file in the same folder as `acct.json`. It might look something like this.

```powershell
@{MyUser='asdf'; MyPass='qwer'} | Export-CliXml .\plugindata.xml
```

**Comment by mikes-gh** [comment]
Just wondered why do you use xml for the param storage.
Why not
`ConvertTo-json ConvertfFrom-json`

**Comment by mikes-gh** [comment]
https://jdhitsolutions.com/blog/powershell/5396/storing-powershell-credentials-in-json/

**Comment by rmbolger** [comment]
I would have, but the built-in JSON converters can't handle "secure" parameters like PSCredential and SecureString without manual intervention (as described in the article you linked). And at the time, it didn't seem worth the effort to roll my own implementation.

However, I may end up doing this for 4.x due to the continued (and likely forever) lack of DPAPI-equivalent encryption in PowerShell Core. More info in issue #150.
