### ISSUE TITLE
special char & in the password saved as  \U+0026 in property PfxPass of order.json

### ISSUE THREAD

**Issue by eissko** [rmbolger/Posh-ACME#195]
Hello Community,

not sure it this is expected behavior or issue. But definitely, it caused me issue when I wanted manually to import  the cert.pfx into the windows certificate store and when I copied password from order.json it wasn't working due to incorrect password.

Thanks

Peter

**Comment by MetUys** [comment]
Hi,
I can confirm I am seeing this too, and is not related to a new build (I see it in old orders, on an old account, which was generated from an old version of POSH-ACME).
I havent ever used the file to copy the password from, however renewals etc work just fine, so its probably handled correctly within the module, and not designed for copy paste direct from the order file.

**Comment by eissko** [comment]
Thanks for answer. Correct, I used 3.8.0 version of POSH-ACME module.

**Comment by rmbolger** [comment]
Hadn't noticed this before, but you're right. It appears to be a standard thing with some JSON encoders that some characters get converted to their unicode code point to prevent issues with HTML encoding. Angle brackets (`<` and `>`) also get converted. Interestingly, while Windows PowerShell 5.1 does this, the newer PowerShell Core 6 does not, but offers a parameter to re-enable the behavior.

Windows PowerShell 5.1
```
PS C:\>'<&>' | ConvertTo-Json
"\u003c\u0026\u003e"
```

PowerShell Core 6.2.3
```
PS C:\>'<&>' | ConvertTo-Json
"<&>"

PS C:\>'<&>' | ConvertTo-Json -EscapeHandling EscapeHtml
"\u003c\u0026\u003e"
```

In any case, you shouldn't need to read the raw JSON file directly to get the PfxPass. It's part of the order object you can get via `Get-PAOrder` like this:

```powershell
(Get-PAOrder).PfxPass
```

But if for some reason you're consuming the file from outside PowerShell, any standard JSON decoder should be able to interpret the file without issue.
