### ISSUE TITLE
HurricaneElectric Plugin Documentation

### ISSUE THREAD

**Issue by NonstopStatic** [rmbolger/Posh-ACME#199]
Thank you for adding support for Hurricane Electric.

I believe references in _HurricaneElectric-Readme.md_ to FDCredential, FDUsername, and FDPassword should be updated to HECredential, HEUsername, and HEPassword. (I suppose the documentation was adapted from the FreeDNS plugin documentation.)

**Comment by rmbolger** [comment]
Whoops, yes. You are totally correct.

**Comment by rmbolger** [comment]
Fixed in f1e1800
