### ISSUE TITLE
PluginArgs for DNS Plugin

### ISSUE THREAD

**Issue by norjen** [rmbolger/Posh-ACME#20]
When testing with both Digital Ocean and CloudFlare DNS plugin, I get prompted for the arguments in PluginArgs , even though I passed the args like shown in the examples.

Running Posh-ACME v2 from PowerShell Gallery

**Comment by juliansiebert** [comment]
Hi,
I added the following to line 144 in "C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.0\Public\Get-PACertificate.ps1" on my machine to get it working:

```
        [...]
            $chalParams.ValidationTimeout = $oldOrder.ValidationTimeout
        }

# From here
        if ('PluginArgs' -in $PSBoundParameters.Keys) {
            $chalParams.PluginArgs = $PluginArgs
        }
# to here

        Submit-ChallengeValidation @chalParams
```

Interestingly the sources here on github already seem to be fixed.

Best regards
Julian
