### ISSUE TITLE
Unable to renew, then unable to create new

### ISSUE THREAD

**Issue by dlmorgan999** [rmbolger/Posh-ACME#200]
This is my first renewal using Posh-ACME.  When I tried doing Submit-Renewal with the noskipmanualdns parameter, I got this error:

cannot validate argument on parameter 'dnsplugin'

The first thing I did was to update the module to the latest version, but I still got this error.

Then I then tried doing a New-PACertificate using the same parameters as my original.  I created the TXT record and continued the process.  Then I got this error:

Error finalizing order
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\Invoke-ACME.ps1:159 char:9
+         throw [AcmeException]::new($acmeError.detail,$acmeError)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AcmeException
    + FullyQualifiedErrorId : Error finalizing order

I tried a couple of times but I keep getting this error.  Any advice?

**Comment by rmbolger** [comment]
That's an odd error from the ACME server. Usually it would have more of an explanation about what the error was. There appears to be some sort of outage with Let's Encrypt at the moment based on their status page:

https://letsencrypt.status.io/

I'll still try and reproduce this on my end, but you may also want to try again after the status page says everything is resolved.

**Comment by rmbolger** [comment]
So I was able to create a new cert using the manual plugin on my end without error. But the [community forums](https://community.letsencrypt.org/) show a bunch of threads from people who seem to be having the same issue you are with other clients. So it might be account specific.

I'd definitely try again once the status page shows everything is back to normal.

**Comment by dlmorgan999** [comment]
That makes sense.   Based on some of what I was seeing, I was beginning to wonder if it might be an LE issue, but I didn't think to check if they had a status page.  Thanks for the pointer!
