### ISSUE TITLE
BouncyCastle errors due to other versions installed in the GAC by other software

### ISSUE THREAD

**Issue by DannyBroadhurst** [rmbolger/Posh-ACME#201]
Hey,

Loving the Posh-ACMe module so far much better then the previous ACMESharp Module I used to use.

I am having issues with a script I created, it seems to work fine on my PC, when I run it on a Windows 2019 Server I am getting a lot of errors, I have been searching and can see they normally relate to .Net 4.7.1+ not being installed.

I have checked and this is installed fine. Wondered if you had any ideas?

Exception calling "GetInstance" with "1" argument(s): "unknown object in GetInstance"
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\Import-Pem.ps1:50 char:9
+         $seq = [Org.BouncyCastle.Asn1.Asn1Sequence]::GetInstance($key ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
 
Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\Import-Pem.ps1:53 char:13
+         if ($seq[0] -eq 0 -and
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
New-Object : Exception calling ".ctor" with "2" argument(s): "Object reference not set to an 
instance of an object."
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\Import-Pem.ps1:112 
char:19
+ ...   $newKey = New-Object Org.BouncyCastle.Crypto.AsymmetricCipherKeyPai ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.Ne 
   wObjectCommand
 
New-Object : Cannot find an overload for "ExtendedKeyUsage" and the argument count: "2".
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\New-Csr.ps1:88 char:129
+ ... OctetString(New-Object Org.BouncyCastle.Asn1.X509.ExtendedKeyUsage([O ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.Ne 
   wObjectCommand
 
New-Object : Cannot convert argument "0", with value: "System.Object[]", for "GeneralNames" to 
type "Org.BouncyCastle.Asn1.X509.GeneralName": "Cannot convert the "System.Object[]" value of 
type "System.Object[]" to type "Org.BouncyCastle.Asn1.X509.GeneralName"."
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\New-Csr.ps1:92 char:122
+ ... OctetString(New-Object Org.BouncyCastle.Asn1.X509.GeneralNames(@(,$ge ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.Ne 
   wObjectCommand
 
New-Object : A constructor was not found. Cannot find an appropriate constructor for type 
Org.BouncyCastle.X509.Extension.SubjectKeyIdentifierStructure.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\New-Csr.ps1:93 char:121
+ ... OctetString(New-Object Org.BouncyCastle.X509.Extension.SubjectKeyIden ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObject 
   Command
 
New-Object : Exception calling ".ctor" with "5" argument(s): "Value cannot be null.
Parameter name: publicKey"
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\New-Csr.ps1:114 char:12
+     $req = New-Object Org.BouncyCastle.Pkcs.Pkcs10CertificationReques ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.Ne 
   wObjectCommand
 
Export-Pem : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\New-Csr.ps1:117 char:16
+     Export-Pem $req $reqFile
+                ~~~~
    + CategoryInfo          : InvalidData: (:) [Export-Pem], ParameterBindingValidationExceptio 
   n
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Export-Pem
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\New-Csr.ps1:120 char:12
+     return (ConvertTo-Base64Url $req.GetEncoded())
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Error parsing certificate request: asn1: syntax error: sequence truncated
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Private\Invoke-ACME.ps1:159 
char:9
+         throw [AcmeException]::new($acmeError.detail,$acmeError)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AcmeException
    + FullyQualifiedErrorId : Error parsing certificate request: asn1: syntax error: sequence t 
   runcated

**Comment by DannyBroadhurst** [comment]
Just an update this seems to be on any VM in Azure

**Comment by DannyBroadhurst** [comment]
So an update. 
I have found the issue. It appears the Azure servers have an old version of Bouncy Castle installed in their GAC.

The script will refer to the GAC first before using the dll included.

I have used this bit of code to update the one in the GAC

`$dllpath = "C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\lib\BouncyCastle.Crypto.dll"
[System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")            
$publish = New-Object System.EnterpriseServices.Internal.Publish            
$publish.GacInstall($dllpath)`

**Comment by rmbolger** [comment]
Bleh. This is the second time in less than 6 months that Microsoft has broken a PowerShell module I use due to installing third party open source libraries into the GAC. Even more annoying that I’m the author of this one.

Great find though. That would’ve taken me a bit for sure. And I’m glad you seem to have found a workaround. I wonder if there’s a way I can at least detect and warn about other copies in the GAC when the module is imported.

**Comment by DannyBroadhurst** [comment]
Very annoying! You would've though Microsoft would include at least the latest version if they need the Bouncy Castle assembly for what ever reason.

**Comment by rmbolger** [comment]
Yet another reason to up the minimum required .NET version so I can try to get rid of the BouncyCastle dependency. Though that would break Azure Automation folks which are seemingly stuck on .NET 4.6 forever.

**Comment by DannyBroadhurst** [comment]
If it helps you put some kind of detection in place this is the command I ran after receiving the errors
`[System.AppDomain]::CurrentDomain.GetAssemblies()`

Once you run this command it will show you all loaded assemblies, it returned Bouncy Castle 1.3.0

It does seem to be only servers which have RDS roles installed, can't tell you which ones as of yet.
Just tried it on another server with no RDS roles and it works fine.

**Comment by rmbolger** [comment]
Also, if you want to future proof your workaround a bit, change the line that gets the DLL path to this:

```powershell
$dllpath = Join-Path (Get-Module Posh-ACME).ModuleBase "lib\BouncyCastle.Crypto.dll"
```

**Comment by DannyBroadhurst** [comment]
Cheers Ryan,

Already got this but done as well! Great minds think alike.

Been doing some research, it may not be azure that has caused it but webroot which we install may be the culprit. Will need to do some more testing to confirm.

Best Regards,
Danny

Danny Broadhurst
Senior Project Engineer
Tel: +44 (0)1733 577055

On 19 Nov 2019, at 22:01, Ryan Bolger <notifications@github.com> wrote:

﻿
[EXTERNAL]

Also, if you want to future proof your workaround a bit, change the line that gets the DLL path to this:

$dllpath = Join-Path (Get-Module Posh-ACME).ModuleBase "lib\BouncyCastle.Crypto.dll"

**Comment by rmbolger** [comment]
The other thing I may end up doing is just renaming the module's copy of the DLL. I think that's what the other module that was affected by this sort of situation ended up doing.

**Comment by rmbolger** [comment]
Forgot to tag this issue in the commit message, but 4209273 is now in the dev/master branch and upgrades and renames the BouncyCastle DLL file in the module so there should no longer be any GAC conflicts.
