### ISSUE TITLE
Submit renewal with cloudflare using CFAuthEmail and CFAuthKey

### ISSUE THREAD

**Issue by Bagu** [rmbolger/Posh-ACME#206]
Hello,

With Posh-ACME 3.11.0,
`Submit-Renewal -PluginArgs @{CFAuthEmail='myemail@mydomain.org'; CFAuthKey='mysecretcloudflarekey'}`

Give me : 

> Export-PluginArgs : Impossible de lier l'argument au paramètre « DnsPlugin », car il a la valeur Null.
> Au caractère C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Public\Submit-Renewal.ps1:80 : 51
> + ...                Export-PluginArgs $PluginArgs $order.DnsPlugin (Get-PA ...
> +                                                  ~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData : (:) [Export-PluginArgs], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Export-PluginArgs
> 
> New-PACertificate : Impossible de valider l'argument sur le paramètre «DnsPlugin». L'argument est null, vide ou un
> élément de la collection d'arguments contient une valeur Null. Indiquez une collection qui ne contient pas de valeur
> Null et réessayez.
> Au caractère C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Public\Submit-Renewal.ps1:90 : 35
> +                 New-PACertificate @certParams
> +                                   ~~~~~~~~~~~
>     + CategoryInfo          : InvalidData : (:) [New-PACertificate], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationError,New-PACertificate

I see there are some problems with cloudflare, but it was with the api key wich is not in use here...
So, can you help me to find a solution ?

Thanks

**Comment by rmbolger** [comment]
The error appears to be caused by the original call to `New-PACertificate` missing the `DnsPlugin` parameter. Did you create the TXT records manually the first time?

The easiest way to fix it will be to run `New-PACertificate` again with the original order parameters including `-DnsPlugin Cloudflare` and `-PluginArgs @{CFAuthEmail='myemail@mydomain.org'; CFAuthKey='mysecretcloudflarekey'}`

**Comment by Bagu** [comment]
Thanks for you answer.

I see this discussion : https://github.com/rmbolger/Posh-ACME/issues/184
So i re-create entries througt the two token method

Can i update later with : 
Submit-Renewal -PluginArgs @{CFAuthEmail='myemail@mydomain.org'; CFAuthKey='mysecretcloudflarekey'}

Or may i use an other method ? (because i don't see how i can update if i use api token)

**Comment by rmbolger** [comment]
Yes, switching between CFAuthEmail method and the CFToken methods should work as long as the original order was created with `-DnsPlugin Cloudflare`.

**Comment by Bagu** [comment]
Ok, many thanks ;)
