### ISSUE TITLE
PfxPass as SecureString instead of string

### ISSUE THREAD

**Issue by nebula-it** [rmbolger/Posh-ACME#207]
Hey @rmbolger ,
I'm working on a script to get multiple certs and push those to respective servers. And I do not want to save Private Key for all our certs in plain text. For now I implemented another function that converts  SecureString (Read from a file) to plain text and pass that to -PfxPass. Is there a possibility for this be implemented as a SecureString or does that cause other issues on other platforms?

**Comment by rmbolger** [comment]
There are two problems with changing the `PfxPass` property to a SecureString value at the moment. 

The first is that it would break anyone's code who is currently using it as a normal string. So I can't do that without making a major version change (3.x to 4.x) where breaking changes are generally allowed. I could add an additional `PfxPassSecure` property, but that doesn't prevent the old property from being serialized to disk as plain text.

The other problem with having any SecureString values in the order object right now is that it's serialized using the native JSON converter functions which don't handle SecureString objects. So I'd have to add custom pre/post processing on the value before writing it to disk and after reading it from disk. It would also have the same DPAPI limitations as described in #150.

Generally I agree that it would be nice avoid serializing the PfxPass as plain text. But realistically, I don't think I'm going to be able to change it until 4.x when I sort out how I'm going to generally deal with doing encryption cross platform.

**Comment by rmbolger** [comment]
Another thing to consider with regards to the security implications of having the PFX password stored in plain text is that the unencrypted cert/key files are also sitting on disk right next to the JSON file with the PFX password. This is something that almost all clients do because a ton of apps use those unencrypted PEM files directly, particularly on non-Windows. So it could be argued that being able to read the PFX password from the JSON file is irrelevant since they can just read the cert/key files without it.

**Comment by rmbolger** [comment]
Hey @nebula-it. I realize I may have misunderstood what you were asking for when you submitted this issue.

Originally, I thought you were concerned that the PfxPass value associated with an order gets saved as plain text on disk. From that perspective, I've actually started implementing a fix in the 4x branch to address it. It's not full encryption, but it's at least obfuscation for the value on disk.

Re-reading what you wrote, I think you're actually asking about how you can pass the `-PfxPass` parameter to the various functions that accept it. In 3.x, the PfxPass function parameters are all normal string values that you are having to convert from SecureString values you read from elsewhere and you'd like to be able to just pass them as SecureString values to the functions, is that right?  If so, I think I can make that work without too much trouble in 4.x. I'm thinking it will just be an additional parameter called `PfxPassSecure` and each function will take one or the other and use it appropriately. Will that work?

**Comment by rmbolger** [comment]
I'm going to call this done for now unless there are further comments from anyone.
