### ISSUE TITLE
Servers to whitelist on DNS filter

### ISSUE THREAD

**Issue by Z-Iain** [rmbolger/Posh-ACME#211]
I have an issue with a server that is using is an outbound DNS filtering service, it is currently blocking the letsencrypt staging and production server. However, I can easily whitelist them, but could you advise on which top level domains i should whitelist please?

Thanks

**Comment by rmbolger** [comment]
Of course. If you just need the top level domain, both staging and production API endpoints live under letsencrypt.org. If you want more specific FQDNs, they are:

acme-v02.letsencrypt.org
acme-staging-v02.api.letsencrypt.org



From: Z-Iain notifications-at-github.com |GitHub/Allow Normal| <wpwisqsv9t@sneakemail.com>
Sent: Saturday, February 1, 2020 2:00 AM
To: Ryan Bolger <rmbolger@dvolve.net>; rmbolger/Posh-ACME <Posh-ACME@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [rmbolger/Posh-ACME] Servers to whitelist on DNS filter (#211)


I have an issue with a server that is using is an outbound DNS filtering service, it is currently blocking the letsencrypt staging and production server. However, I can easily whitelist them, but could you advise on which top level domains i should whitelist please?

Thanks

**Comment by Z-Iain** [comment]
Thanks, that's just what I needed.
