### ISSUE TITLE
Request DNSPlugin for LoopiaDNS

### ISSUE THREAD

**Issue by iAmYoel** [rmbolger/Posh-ACME#212]
Request to add LoopiaDNS as DNSPlugin.
Loopia has got an API for this purpose.

**Comment by rmbolger** [comment]
I @iAmYoel. I'll do my best. I tried creating an account, but it's currently waiting on approval. Do you know if they offer DNS hosting only or are they just a domain registrar that includes DNS hosting? I can't quite tell from their website whether I can just point one of my existing test domains to them or whether I'd need to actually transfer one to them or buy a new one from them.

**Comment by rmbolger** [comment]
Just an update. I haven't received a response to my account creation request yet. Do they allow customers from the US?

**Comment by Coolhed** [comment]
Hi, I am also interested in getting support for Loopia. I have an account but I do not know anything about Loopias policy for customers outside of the US...

**Comment by rmbolger** [comment]
Hooray! It took a while but I now have a Loopia account and should be able to start working on this plugin.

**Comment by rmbolger** [comment]
Loopia certainly has an...interesting...API for managing DNS records. But it's better than nothing and the plugin seems to work for me. I've merged it into the master/dev branch if you guys want to give it a try.

**Comment by Coolhed** [comment]
Great! I will try it out.

**Comment by Coolhed** [comment]
Hi Ryan, the pluging works perfect! Thank you for a great work!

**Comment by rmbolger** [comment]
Excellent. Hoping to get an official release out as soon as I finish with these other plugin pull requests.
