### ISSUE TITLE
Submit-Renewal -All-Orders filters out expired orders

### ISSUE THREAD

**Issue by thetrav** [rmbolger/Posh-ACME#213]
I have a script on my server to renew all certificates every morning at 1am.

It appears that if I specify each domain name manually, Submit-Renewal has no problem renewing the certificates.

When I check the Get-PAOrders list, the expires column has no value.  The certificates are not expired and due for renewal.  Perhaps the script is assuming that they are expired when it doesn't really know one way or the other?

**Comment by rmbolger** [comment]
Hi @thetrav. Let me make sure I understand correctly. When you say Submit-Renewal has no problem, is that when using the `-Force` parameter, or just a normal renew?

Are you by chance on a non-US locale? I'm wondering if there might be a display formatting bug in the Get-PAOrder output that makes some US-centric assumptions.

Can you post the output of `Get-PAOrder-List`? Feel free to sanitize the domains if you want. Also, just for comparison, show me the output of `Get-PAOrder -List | fl` as well.

**Comment by thetrav** [comment]
Not using -Force

`Submit-Renewal -AllOders -Verbose` = nothing to renew
`Submit-Renewal $fullHostName -Verbose` = renews cert

```
PS> Get-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

```
PS> Get-PAOrder -List

MainDomain       status KeyLength SANs OCSPMustStaple CertExpires
----------       ------ --------- ---- -------------- -----------
REDACTED         valid  2048      {}   False          2/05/2020 6:04:07 AM
```
In the above sample the CertExpires column has a value and the status is valid.  This is because I was able to successfully renew the certificate.
I no longer have a sample of the old output, but I recall that status was pending and CertExpires had no value
```
PS> Get-PAOrder -List | fl
status            : valid
expires           : 2020-02-08T21:01:54Z
identifiers       : {@{value=REDACTED; type=dns}}
authorizations    : {https://acme-v02.api.letsencrypt.org/acme/authz-v3/REDACTED}
finalize          : https://acme-v02.api.letsencrypt.org/acme/finalize/REDACTED/REDACTED
MainDomain        : REDACTED
SANs              : {}
KeyLength         : 2048
CertExpires       : 2020-05-01T20:04:07Z
RenewAfter        : 2020-04-01T20:04:07Z
OCSPMustStaple    : False
DnsPlugin         : {Azure}
DnsAlias          :
DnsSleep          : 120
ValidationTimeout : 60
FriendlyName      : REDACTED
PfxPass           : poshacme
Install           : False
certificate       : https://acme-v02.api.letsencrypt.org/acme/cert/REDACTED
location          : https://acme-v02.api.letsencrypt.org/acme/order/REDACTED/REDACTED
```

**Comment by rmbolger** [comment]
> but I recall that status was pending and CertExpires had no value

This is actually normal when a new order is created. Until the order status reaches the "valid" state, there's no certificate to report an expiration date for.

The same thing happens if a renewal was started but didn't finish. The old cert files get backed up and the old order info gets overwritten by the new one. So until that new order reaches the "valid" state, you'd get the same behavior.

So it sounds like some of the certs may have had a problem renewing at some point and were left in a pending state? But the next time `Submit-Renewal` is run, it should pick up the pending order(s) and try again.
