### ISSUE TITLE
Error on $role = New-AzRoleDefinition $roleDef

### ISSUE THREAD

**Issue by justSteve** [rmbolger/Posh-ACME#222]
In the 'How To Use the Azure DNS Plugin' doc under the '_Create a Custom Role_' section is a script block that concludes with: `$role = New-AzRoleDefinition $roleDef`. That statement tosses: 

```
New-AzRoleDefinition : Scope '/subscriptions' should have even number of parts.
At line:1 char:10
+  $role = New-AzRoleDefinition $roleDef
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleDefinition], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand

```
The error msg is subject of: https://github.com/Azure/azure-powershell/issues/9798 .

Any thoughts from here re: a resolution?

**Comment by rmbolger** [comment]
Hi @justSteve, I'm not sure the error you got actually relates to the issue you linked. The line before New-AzRoleDefinition has you adding a scope to the role definition using `"/subscriptions/$($az.Context.Subscription.Id)"` which assumes the `$az` object from connecting earlier actually has a subscription associated with it.

I was able to reproduce this error when that subscription ID was null.  Can you verify that `$az.Context.Subscription.Id` actually returns a value? If it doesn't, that's your problem. I've had this happen on Azure accounts that were previously using a trial subscription that expired. It will still let you login, but the Subscription related fields are empty.

**Comment by justSteve** [comment]
Thanks much for the response. Seems I'm falling into the 'trial that expired' camp. Any thoughts on a work around? Perhaps create a new subscription now that I'm a pay-as-you-go kinda guy?

**Comment by rmbolger** [comment]
No worries. I'm pretty sure the only solution is either starting a pay-as-you-go subscription or starting a new trial on a different account.
