### ISSUE TITLE
Invalid signature error with OVH plugin

### ISSUE THREAD

**Issue by rampie** [rmbolger/Posh-ACME#228]
Hello,

when trying to create / update certificates i get the following error:

> 
> Invoke-RestMethod : {"message":"Invalid signature","httpCode":"400 Bad Request","errorCode":"INVALID_SIGNATURE"}
> At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.12.0\DnsPlugins\OVH.ps1:311 char:5
> +     Invoke-RestMethod @restArgs @script:UseBasic -EA Stop
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

The code i use for this is:

```
$domain = "alias.mydomain.com"
$contact = "my mail adress"

$appSecret = ConvertTo-SecureString "******" -AsPlainText -Force
$consumerKey = ConvertTo-SecureString "*******" -AsPlainText -Force

$pArgs = @{
    OVHAppKey = '******'
    OVHAppSecret = $appSecret
    OVHConsumerKey = $consumerKey
    OVHRegion = 'ovh-eu'
}

echo "parameters set"
# Due to a Windows bug in which the first certificate imported into the Windows certstore is often incorrectly imported, we will execute the New-PACertificate twice - first against a test/staging server, ignore that certificate, then switch to the production server and run the same command.

Set-PAServer LE_STAGE
echo "set Stage Server"
New-PACertificate $domain -Contact $contact -Install -ErrorAction Stop -DnsPlugin OVH -PluginArgs $pArgs -AcceptTOS -force 
echo "new cert asked"
$stagingCert = Get-PACertificate
Get-ChildItem Cert:\LocalMachine\My | Where-Object Thumbprint -eq $stagingCert.Thumbprint | Remove-Item

echo "set Prod Server"
Set-PAServer LE_PROD
New-PACertificate $domain -Contact $contact -Install -ErrorAction Stop -DnsPlugin OVH -PluginArgs $pArgs -AcceptTOS -force 
#Get-PACertificate | Set-MobileServerCertificate
```

I use this script already for 2 different certificates for the same purpose on different server, however if i try to make the third certificate on a PC where one of the first two work, it gives me the same error.

I alread checked see if it finds my alias under OVH, and it does.
I already checked to see if the date was correct and there is no offset.
Got any Ideas why i keeps giving me this problem?

**Comment by rmbolger** [comment]
This is a really strange problem considering it works sometimes and not others. Can you enable debug output by running `$DebugPreference = 'Continue'` and try running the command for the one that isn't working again also with the `-Verbose` parameter and then post the output here?

Also FYI, you shouldn't need to run the command against the staging server first anymore. I added a workaround for that issue in version 3.7.0 assuming you've got it or a later version installed.

**Comment by rampie** [comment]
> VERBOSE: Using directory https://acme-v02.api.letsencrypt.org/directory
> VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/acct/61286525 with -1-byte payload
> VERBOSE: received 315-byte response of content type application/json
> VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/acct/80707647 with -1-byte payload
> VERBOSE: received 316-byte response of content type application/json
> VERBOSE: Using account 80707647
> VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/order/80707647/2672352377 with -1-byte payload
> VERBOSE: received 342-byte response of content type application/json
> VERBOSE: Creating a new order for alias.mydomain.com
> VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/order/80707647/2672352377 with -1-byte payload
> VERBOSE: received 342-byte response of content type application/json
> VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/new-order with -1-byte payload
> VERBOSE: received 342-byte response of content type application/json
> VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/authz-v3/3386979298 with -1-byte payload
> VERBOSE: received 800-byte response of content type application/json
> VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/authz-v3/3386979298 with -1-byte payload
> VERBOSE: received 800-byte response of content type application/json
> VERBOSE: Publishing DNS challenge for alias.mydomain.com
> VERBOSE: GET https://eu.api.ovh.com/1.0/domain/zone/alias.mydomain.com with 0-byte payload
> Invoke-RestMethod : {"message":"Invalid signature","httpCode":"400 Bad Request","errorCode":"INVALID_SIGNATURE"}
> At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.12.0\DnsPlugins\OVH.ps1:311 char:5
> +     Invoke-RestMethod @restArgs @script:UseBasic -EA Stop
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Here is the log.

PS i removed the staging from the script :)

**Comment by rmbolger** [comment]
The output you posted doesn't seem to be including the Debug output. Make sure you run that `$DebugPreference = 'Continue'` in the same session as the command you run.

Despite the lack of debug logs, I do see some things that might offer a partial explanation of what's happening. In the second working log, it looks like no attempt is made to publish a DNS challenge at all. This is likely because you had already successfully validated a challenge against the name in that certificate and that previous authorization is still valid. Only the first one is currently trying to publish a TXT record. So let's see if we can run some tests to make it reliably fail on just the TXT record publishing and work from there.

Try this and post the output. You can try it with both working and non-working names. But I would guess that either both work or both fail.

```powershell
$DebugPreference = 'Continue'

$appSecret = ConvertTo-SecureString "******" -AsPlainText -Force
$consumerKey = ConvertTo-SecureString "*******" -AsPlainText -Force

$pArgs = @{
    OVHAppKey = '******'
    OVHAppSecret = $appSecret
    OVHConsumerKey = $consumerKey
    OVHRegion = 'ovh-eu'
}

Publish-DNSChallenge alias.mydomain.com (Get-PAAccount) faketoken OVH $pArgs -Verbose

# if it worked, you can remove the record like this
Unpublish-DNSChallenge alias.mydomain.com (Get-PAAccount) faketoken OVH $pArgs -Verbose
```

**Comment by rampie** [comment]
Hello,

i just tried those commands for both names.

Result non-working and working name:

```
DEBUG: Loading PAAccount list from disk
DEBUG: Calling OVH plugin to add _acme-challenge.alias.mydomain.com TXT with value *****
DEBUG: Checking massimo.heynderick.com
VERBOSE: GET https://eu.api.ovh.com/1.0/domain/zone/alias.mydomain.com with 0-byte payload
Invoke-RestMethod : {"message":"Invalid signature","httpCode":"400 Bad Request","errorCode":"INVALID_SIGNATURE"}
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.12.0\DnsPlugins\OVH.ps1:311 char:5
+     Invoke-RestMethod @restArgs @script:UseBasic -EA Stop
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by rmbolger** [comment]
Despite the errors you're now getting on both names, that's actually progress. It means something is likely wrong with your App Secret value. I was able to get the API to give me the same `Invalid signature` error when I purposefully added an extra character to my own App Secret value. You should double check your API credentials or perhaps just create a new one and delete the old one.

Changing a character in the App Key gave a different error about the application key being invalid. Similarly, changing a character in the Consumer Key gave an error about the credential not existing.

**Comment by rampie** [comment]
OK, i found the first problem... apparently there was a character to much in my app-secret.
Now i get the error of This credential does not exist, so i guess this has to do with the ConsumerKey that is not correct...

Now i still have to figure out how to get the consumerkey to work..

**Comment by rmbolger** [comment]
You can probably re-run the `Invoke-OVHSetup` command as described in the [usage guide](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/OVH-Readme.md) to generate a new consumer key. Is it possible your old one was set to expire?

**Comment by rampie** [comment]
That is what i did and it worked.  The script is running smoothly now for all domains.  Thanks for the assistance!
