### ISSUE TITLE
Improvement of CNAME record representation for ACME-DNS

### ISSUE THREAD

**Issue by oregano87** [rmbolger/Posh-ACME#231]
When using the plugin acme-dns, the redirect information for CNAME will be displayed like this:
```
Please create the following CNAME records:
------------------------------------------
_acme-challenge.win.company.test -> abd44bd9-a45d-4053-899d-ed7420019ad5.acme-dns.test
_acme-challenge.posh-acme.company.test -> 6f8c55a5-caa8-44df-a8af-f6e1b676134f.acme-dns.test
------------------------------------------

Press any key to continue.:
```

For better copy-paste handling it would be helpful to have a dot at the end of the URLs. 
```
Please create the following CNAME records:
------------------------------------------
_acme-challenge.win.company.test. -> abd44bd9-a45d-4053-899d-ed7420019ad5.acme-dns.test.
_acme-challenge.posh-acme.company.test. -> 6f8c55a5-caa8-44df-a8af-f6e1b676134f.acme-dns.test.
------------------------------------------

Press any key to continue.:
```

This prevents (maybe) that the dot is missing in the BIND configuration.

**Comment by rmbolger** [comment]
Thanks for the suggestion, @oregano87. While I agree that adding the ending dot is more correct from a DNS protocol standpoint, it's not a commonly known thing from people who don't deal with DNS on a regular basis. I'm guessing most aren't actually touching BIND zone files directly either. And most of the online providers with web UIs don't accept that format. I'm afraid it would just end up shifting the mistakes the other way.

So, noted but politely declined.
