### ISSUE TITLE
Azure DNS Plugin - Subscription permissions and New-AzADServicePrincipal

### ISSUE THREAD

**Issue by miked1313** [rmbolger/Posh-ACME#236]
Thank you for all of your work on this, Posh-ACME is an excellent PowerShell module for Let's Encrypt certs!

When using the code for New-AzADServicePrincipal in [Posh-ACME/DnsPlugins/Azure-Readme.md](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Azure-Readme.md), we found that the Az module 3.5 was adding the PoshACME App Registration as a Contributor to the entire Subscription.  We were able to fix this issue by adding the -SkipAssignment param.  Can you please test and update the Azure-Readme to recommend using -SkipAssignment?

`$sp = New-AzADServicePrincipal -DisplayName PoshACME -StartDate $notBefore -EndDate $notAfter -SkipAssignment`

**Comment by rmbolger** [comment]
Whoops. You're totally right. I must have missed that when I converted the instructions from the old AzureRm modules. I'll fix it shortly.
