### ISSUE TITLE
Documentation on running stateless / how orders are stored

### ISSUE THREAD

**Issue by StephenCleary** [rmbolger/Posh-ACME#242]
It's not really clear how "orders" are stored or how they are related to `New-PACertificate`.

As someone who is unfamiliar with ACME, I read in one of these issues that `New-PACertificate` is pretty much the same as `Renew` if an order exists. It wasn't clear to me that orders apparently only exist locally.

I want to renew my certificate as necessary from a cron-scheduled GitHub Action. However, there is no persisted storage for these. I observe that `New-PACertificate` always attempts to create the certificate, so I assume that orders are stored locally and that the ACME protocol has nothing built-in to prevent early renewals. Specifically, `New-PACertificate` (with no local storage) renewed my cert when it still had 80 days before expiration.

For now, I worked around this by writing a bit of Posh to read the certificate and not call `New-PACertificate` until the cert has less than 30 days to go. This works fine for my use case because the cert is stored in my repository, but in the general case it would be good to have documentation about how Posh-ACME behaves in a GitHub Action (or anywhere without state).

**Comment by rmbolger** [comment]
To a certain extent, it is as you suspect partially a limitation of the ACME protocol. While the spec does support the concept of querying the server for a list of existing orders associated with an account, Let's Encrypt's current implementation does not currently support that feature. It also doesn't seem like they're prioritizing adding it either. So without a locally cached copy of existing order data, the client can't know what has already been created or when things expire. In LE's defense, that portion of the spec was a pretty late addition, but I digress.

Even if Boulder (Let's Encrypt's ACME server implementation) eventually adds the feature, there's also additional order related metadata that Posh-ACME stores to make renewals easier like associated plugin, credentials, etc. It would be hard to support a fully stateless mode without additional custom scripting help like your own workaround is doing today.

I wholeheartedly agree that that having more documentation on how things work under the hood is a good idea. I'll leave this issue open as a reminder to do just that.

**Comment by StephenCleary** [comment]
Actually, if just the file location of the local state was documented (for the PoshCore version), I could whip up a GHA example or possibly a custom action. It would be a bit inefficient, but I'm thinking we could (ab)use GHA cache as a form of local storage.

**Comment by webprofusion-chrisc** [comment]
I'd assume certs used by github actions should be stored as Secrets, so perhaps this needs to be something that does need to maintained outside of Actions? I'm guessing this is a private repo and that's why you can store your cert there.

**Comment by phatmandrake** [comment]
A lot of good information is here: Located here https://github.com/rmbolger/Posh-ACME/wiki/%28Advanced%29-Semi-Manual-DNS-Challenge-Validation

It's a lot of useful information into understanding how this process works, but it's a bit obscured by the name.

**Comment by rmbolger** [comment]
Thanks @phatmandrake. I actually forgot how much protocol level explanation I included in some of those guides. I've actually found some tweaks I should make after re-reading them.

**Comment by mhuebert** [comment]
I'm also interested in setting up certificate renewal in GitHub action run on a schedule.

> What most clients call a renewal is just a new order with the same parameters as last time. So the only thing extra you need to deal with is knowing when to renew.

If expiration-time of the current cert is the only information we need, might it work to read using openssl [something like this](https://gist.github.com/cgmartin/49cd0aefe836932cdc96), and sidestep persisting any of the output from posh-acme?

**Comment by rmbolger** [comment]
Yes, that would definitely work. Any method of gleaning the current cert's expiration would give you the info you need to know when to renew.

**Comment by StephenCleary** [comment]
I use this posh approach in an ubuntu GHA, which reads the existing cert from the repository:

```C#
$currentCert = Get-PfxCertificate backend/localhost.pfx -Password $password
$expires = $currentCert.NotAfter - (Get-Date)
Write-Output "Current cert expires in $expires"
if ($expires -gt (New-TimeSpan -Days 30)) {
  Write-Output "Choosing not to renew certificate yet."
  exit
}
```

This works fine for me, as the cert is only for a `localhost.*` domain.
