### ISSUE TITLE
wildcard certificate for Exchange

### ISSUE THREAD

**Issue by bruce1949** [rmbolger/Posh-ACME#248]
I'd like to apply wildcard certificate for Exchange with this tool,but experiencing some issue.
DNS provider: Aliyun
Path of Script to run 
C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.13.0\DnsPlugins\Aliyun.ps1
I add one line at  the  top of script:
`$aliParams = @{AliKeyId='myid';AliSecretInsecure='mypassword'}`
and run the tools with the following input:

- Please choose from the menu: M
- How shall we determine the domain(s) to include in the certificate?: 2
- Enter comma-separated list of host names, starting with the common name: *.mydomain.com
- Suggested friendly name '[Manual]  *.mydomain.com', press <ENTER> to accept or type an alternative: Exchange
- How would you like prove ownership for the domain(s) in the certificate?: 3
- Path to script that creates DNS records: C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.13.0\DnsPlugins\Aliyun.ps1
- How to delete records after validation: 1
- Input parameters for create script, or enter for default "create {Identifier} {RecordName} {Token}": <Enter>
-  Input parameters for delete script, or enter for default "delete {Identifier} {RecordName} {Token}": <Enter>

- What kind of private key should be used for the certificate?: 2

- How would you like to store the certificate?: <Enter>

- Would you like to store it in another way too?: <Enter>

- Which installation step should run first?: 3

 Full instructions:  https://www.win-acme.com/reference/plugins/installation/script

-  Enter the path to the script that you want to run after renewal: C:\Program Files\WindowsPowerShell\Modules\Scripts\ImportExchange.ps1

-  Enter the parameter format string for the script, e.g. "--hostname {CertCommonName}": <Enter>

Error showed as below

Cached order available but not used with the --force switch.
 First chance error calling into ACME server, retrying with new nonce...
 Authorize identifier mydomain.com
 Authorizing mydomain.com using dns-01 validation (Script)
 Script C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.13.0\DnsPlugins\Aliyun.ps1 starting with parameters create mydomain.com _acme-challenge.mydomain.com P5XH-6-dOKtH0t6SruMwmAXTr-M-HNgwpdga00rNTxU
 Script finished
 Answer should now be available at _acme-challenge.mydomain.com
 Preliminary validation failed: no TXT records found
 Will retry in 30 seconds (retry 1/5)...
 Preliminary validation failed: no TXT records found
 Will retry in 30 seconds (retry 2/5)...
 Preliminary validation failed: no TXT records found
 Will retry in 30 seconds (retry 3/5)...
 Preliminary validation failed: no TXT records found
 Will retry in 30 seconds (retry 4/5)...
 Preliminary validation failed: no TXT records found
 Will retry in 30 seconds (retry 5/5)...
 Preliminary validation failed: no TXT records found
 It looks like validation is going to fail, but we will try now anyway...
 First chance error calling into ACME server, retrying with new nonce...
 {
  "type": "urn:ietf:params:acme:error:dns",
  "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.mydomain.com - check that a DNS record exists for this domain",
  "status": 400
}
 Authorization result: invalid
 Script C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.13.0\DnsPlugins\Aliyun.ps1 starting with parameters delete mydomain.com _acme-challenge.mydomain.com P5XH-6-dOKtH0t6SruMwmAXTr-M-HNgwpdga00rNTxU
 Script finished

 Create certificate failed, retry? (y/n*)  - yes

**Comment by bruce1949** [comment]
Thanks for your help in advance

**Comment by rmbolger** [comment]
Sorry @bruce1949. I think you submitted an issue to the wrong project. It looks like you're trying to use [win-acme](https://github.com/win-acme/win-acme) along with one of my DNS plugins (which appears to be working from your output). You should try submitting this issue over there.

**Comment by bruce1949** [comment]
Sorry for the mistake and I've submitted it on win-acme.
