### ISSUE TITLE
Delete SAN from the certificate

### ISSUE THREAD

**Issue by amrut057** [rmbolger/Posh-ACME#249]
Is there a feature to delete SAN from a certificate generated for azure dns zone?

**Comment by rmbolger** [comment]
The way certificates work doesn't allow them to be modified after they're created. So there's no way to delete a SAN from an existing certificate file. What you would do instead is just request a new certificate with all of the original names except the one you wanted to delete.

In Posh-ACME specifically, you'd just re-run `New-PACertificate` with a different list of domains. Assuming the first one in the list is the same as before, the new certificate would replace the old one. It's ok if the first one is different too. You'll just end up with both the old and new one in separate order folders.

**Comment by amrut057** [comment]
Thanks for such a prompt reply. Just wanted to confirm if I understood correctly. I have a certificate with name abc.com.au and abc1.com.au, abc2.com.au as SAN. If I now want abc1.com.au and abc2.com.au as different certificates, I will submit 3 requests. One each for abc.com.au, abc1.com.au and abc2.com.au

**Comment by rmbolger** [comment]
You are correct. Additionally if it has been less than 30 days since you got the first certificate with all 3 names in it, each one of these new individual certificates should complete very quickly because the names have already been validated by the original order (assuming you're using the same ACME account).

**Comment by amrut057** [comment]
Thanks. Can I also wanted to ask about "Unable to find Azure hosted zone for $RecordName" error. I am not able to find anything on this on he internet. I have a dns zone(abc.com.au) created in azure and dns delegation is also done. when I submit the request for certificate creation I get this error : Unable to find Azure hosted zone for _acme-challenge.abc.com.au

**Comment by rmbolger** [comment]
Can you do me a favor and open a new issue about the other problem. It makes it easier to keep track of things and helps other people find similar problems in the future. It will help if you post the details about which method you're using to authenticate to Azure.
