### ISSUE TITLE
Output to PEM format

### ISSUE THREAD

**Issue by centuryx476** [rmbolger/Posh-ACME#25]
Hello,
How can I output to a PEM format ? 

Thanks

**Comment by rmbolger** [comment]
You're in luck! PEM formatted files are output by default in the certificate order's folder in your local profile. You can get the full path to them like this:

```powershell
Get-PACertificate | Format-List
```

The `CertFile`, `KeyFile`, `ChainFile`, and `FullChainFile` are all PEM formatted files.

**Comment by echodreamz** [comment]
Is there a way to ask for the path of just the pfxfile back?

**Comment by rmbolger** [comment]
You got it. You can do the same with the output directly from `New-PACertificate` and `Submit-Renewal` (assuming they succeed).
