### ISSUE TITLE
WARNING: Unable to resolve package source

### ISSUE THREAD

**Issue by bobt333** [rmbolger/Posh-ACME#251]
Hi

I'm a former sslforfree.com user looking for an alternative, but I have no prior experience dealing with powershell (I'm on Windows 10). When I attempted to install ("Install-Module -Name Posh-ACME -Scope AllUsers"), I got this:

- - -
Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
&Yes  Yes to &All  &No  No to A&ll  &Suspend
N
WARNING: User declined to install module (Posh-ACME).
- - -

I pressed "Enter" to exit to investigate. I decided to just run it again and answer "Yes" to the "Are you sure?" question, but then I got this:

- - -
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'Posh-ACME'. 
Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], 
Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'Posh-ACME'.
Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
- - -

Do you have any suggestions? Perhaps by not accepting the first time it somehow marked the package as untrusted such that it would not appear again?

Thanks!

**Comment by rmbolger** [comment]
Hey @bobt333. No worries, you didn't do anything wrong. The untrusted repository warning is normal. The package source error is ultimately Microsoft's fault for making some changes to the gallery website that broke older versions of their powershell package management stuff. Can you post what version of Windows 10 you're on by running this command?

    (gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').ReleaseId

I'd like to get a test environment up and figure out the exact set of steps needed to fix this and add it to the FAQ. In the mean time, here's the official MS post on the issue and some potential fixes.
https://devblogs.microsoft.com/powershell/powershell-gallery-tls-support/

**Comment by bobt333** [comment]
Hi, thanks for answering so quickly!

PS C:\> (gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').ReleaseId
1803

**Comment by rmbolger** [comment]
So the main stumbling block with using the gallery is the TLS 1.2 requirement. So bare minimum, you need to run this prior to anything else.

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

After that, everything else *should* work with a variety of prompting depending on whether you're running as admin or not. If you're not running as admin and you want to avoid all of the prompting, here's the minimum set of steps I needed to make things work prior to running the `Install-Module` command.

```powershell
Set-ExecutionPolicy RemoteSigned -Force -Scope CurrentUser
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Scope CurrentUser
Set-PSRepository PSGallery -InstallationPolicy Trusted
```

If you're running as admin, the same thing should work except you don't need the `-Scope CurrentUser` params at the end of those first two commands.

**Comment by bobt333** [comment]
Thanks much... I did find that at that powershell gallery support link you sent, and it worked!

I hope I'm not abusing the ticket by following up here with another few questions.

I went through this process and ended up with a certificate that my CPanel says does not match my domain. I think it's because I used the "site1.xxxxx.com" and maybe should have left off that "site1".

Is there a way to revoke that certificate and start over, or would I just repeat the process without the "site1"?

**Comment by rmbolger** [comment]
Yeah, `site1` is usually just for examples. You'd add whatever names people get to your site with. Usually that's just the root domain and a www version such as `example.com` and `www.example.com`.

For the old cert, there's a difference between revoking and just deleting it. You only really need to revoke a cert if the private key was compromised or something. If you're just not going to use it, it's fine to just delete it and let it expire normally. Here are the ways to do those things.

```powershell
# Revoke a cert
Set-PAOrder example.com -RevokeCert

# Delete a cert from your system
Remove-PAOrder example.com

# Or do both at once
Remove-PAOrder example.com -RevokeCert
```
