### ISSUE TITLE
Wild cards do not seem to work

### ISSUE THREAD

**Issue by bobt333** [rmbolger/Posh-ACME#252]
I attempted to create one certificate as a wildcard (*.abc.com). To do this I used the command: 

New-PACertificate *.abc.com -AcceptTOS -Contact xxxxx@xxxxxx.com

The certificate files all created fine, but when I install them to the site in my cpanel I get the ugly "Not secure" notices. Is this the way to do wild cards? Or would I need to make a certificate for each individual subdomain?

Thanks!

**Comment by rmbolger** [comment]
Typically with a wildcard certificate, you would include both the wildcard name `*.example.com` and the root domain name `example.com` because the wildcard name doesn't actually cover the root domain.

**Comment by bobt333** [comment]
AH, OK, that makes sense. Would I need to create two separate certificates, or is there a way to do both together? Maybe this:

New-PACertificate *.abc.com,abc.com -AcceptTOS -Contact xxxxx@xxxxxx.com

(comma separated list)

**Comment by rmbolger** [comment]
You have it exactly right. Comma separated will work just fine to put both names in a single cert. The first name in the list becomes the "MainDomain" which some of the other functions in the module refer to.

If necessary, Let's Encrypt allows up to 100 names per cert. But that's highly unusual outside of service providers and such. They don't even have to be in the same domain as long as you can validate challenges for all of them.

**Comment by bobt333** [comment]
Thanks much, both for the help and for the awesome tool that will rescue us from ZeroSSL.
