### ISSUE TITLE
Support for AWS.Tools?

### ISSUE THREAD

**Issue by ultnrg** [rmbolger/Posh-ACME#255]
Just installed Posh on a new build which I've set up with the newer AWS.Tools module rather than the full AWSPowershell module.

AWS doco: https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-windows.html#ps-installing-awstools

Posh errors out saying it cannot find the supported module, however simply changing line 341 in Route53.ps1 from $modName = 'AwsPowershell' to $modName = 'AWS.Tools.Route53' gets everything functioning correctly.

Wondering if it's possible to check for either AwsPowershell or AWS.Tools.Route53 in the script?

**Comment by rmbolger** [comment]
The fix is now in the dev/master branch. Not sure when I'm going to get a new release out, but it shouldn't be too long.

**Comment by ultnrg** [comment]
Thank you! :-)
