### ISSUE TITLE
Getting an error message, please help whats the problem is ? 

### ISSUE THREAD

**Issue by jgdsh** [rmbolger/Posh-ACME#257]
I am trying to setup the certificate for milestone VMS, but i am getting this error message. What could be the issue here ? 

`Setting Execution Policy to RemoteSigned
Testing certificate request against staging server
Invoke-RestMethod : The underlying connection was closed: A connection that was expected to be kept alive was closed
by the server.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.14.0\DnsPlugins\Dynu.ps1:66 char:13
+             Invoke-RestMethod "$apiBase/dns/$zoneID/record" -Method P ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : `WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand``

**Comment by rmbolger** [comment]
This looks like some sort of network issue between your machine and Dynu.

What happens if you just run a simple query against their API root URL like this?

    Invoke-RestMethod https://api.dynu.com/v2
    $Error[0].Exception.Message

I get a pretty standard 404 error.

**Comment by jgdsh** [comment]
Do you think its the issue with dynu ?

**Comment by rmbolger** [comment]
No, I think it's a problem with your network. Can you post the results of the code I mentioned?

**Comment by jgdsh** [comment]
I get this result

`PS C:\WINDOWS\system32> Invoke-RestMethod https://api.dynu.com/v2
>> $Error[0].Exception.Message
Invoke-RestMethod : {"statusCode":404,"type":"Request Exception","message":"Invalid."}
At line:1 char:1
+ Invoke-RestMethod https://api.dynu.com/v2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
The remote server returned an error: (404) Not Found.`

**Comment by rmbolger** [comment]
Ok, that's good. Maybe try the module again. It may have just been a temporary error with Dynu.

**Comment by jgdsh** [comment]
It went through DNS propagaiton and i see an entry created by letsencrypt but i get this error message 

`Testing certificate request against staging server
Invoke-ACME : You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.14.0\Private\Export-PACertFiles.ps1:40 char:13
+             Invoke-ACME $header ([String]::Empty) $acct -OutFile $ful ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-ACME], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Invoke-ACME`

**Comment by jgdsh** [comment]
I tried again by reopening powershell, it will go through the DNS propagation, i see the DNS entry created and after a while i get this message 

`Testing certificate request against staging server

Please review the Terms of Service here: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Invoke-RestMethod : The underlying connection was closed: A connection that was expected to be kept alive was closed
by the server.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.14.0\DnsPlugins\Dynu.ps1:137 char:13
+             Invoke-RestMethod "$apiBase/dns/$($rec.domainId)/record/$ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by rmbolger** [comment]
That's the same error you had originally. It's not something that I've really seen before though. But the message implies that either Dynu is having intermittent server issues or something between your network or theirs is having issues.
