### ISSUE TITLE
ACME-DNS Plugin; Option to pass in Authentication and Subdomain Parameters

### ISSUE THREAD

**Issue by Somaimo** [rmbolger/Posh-ACME#260]
We are using the acme-dns plugin for certificate validation and have a local installation of a acme-dns server (with an alias domain). We want to fully automate the process for creating the alias entries into the DNS and have a script that creates new subdomains on the acme-dns server and then populates the primary DNS Zone  with the corresponding _acme-challenge CNAME entries.

For this to work with posh-acme we would have to provide the credentials (user-id, password and subdomain) to posh-acme.

Would it make sense for you to be able to pass those additional parameters for the acme-dns plugin?

Love the work you put into posh-acme, thanks so much.

**Comment by rmbolger** [comment]
Hey @Somaimo, thanks for reaching out. I think I might be able to make this work if I understand you correctly. You're essentially prestaging the acme-dns registrations and CNAME creation and just want to pass the resulting registration objects to Posh-ACME to avoid the normal interactive workflow.

It would likely involve passing a hashtable containing each `_acme-challenge` record and its associated registration details. Perhaps something like this.

```powershell
$registrations = @{
    '_acme-challenge.example.com' = @(
        '9aa5ce59-635e-440c-b2ca-12ee3503ddee'                        # subdomain
        '1b5cce3b-255d-4ffb-a81f-a9e27167ac7a'                        # username
        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'                         # password
        '9aa5ce59-635e-440c-b2ca-12ee3503ddee.acmedns.example.com'    # full domain
    )
    '_acme-challenge.www.example.com' = @(
        'ec6ec1f4-836e-462e-b577-b2f4e04d7291'
        'aeb00c77-852b-465e-9b27-984bc6cb12f5'
        'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'
        'ec6ec1f4-836e-462e-b577-b2f4e04d7291.acmedns.example.com'
    )
}

$pluginArgs = @{
    ACMEServer = 'acmedns.example.com'
    ACMERegistrations = $registrations
}

New-PACertificate example.com,www.example.com -DnsPlugin AcmeDns -PluginArgs $pluginArgs
```

Does that look more or less like what you were thinking?

**Comment by Somaimo** [comment]
Hi @rmbolger, that is exactly what I had in mind. This would be awesome and really simplify the complete automation of the process.

Thanks a lot

**Comment by rmbolger** [comment]
I haven't had a chance to update the usage guide yet. But the dev branch now has a `-ACMERegistration` optional parameter that works just like I described above. Give it a try and see how it works for you.

**Comment by Somaimo** [comment]
Works like a charm! I tested it with our own acme-dns server and acme-dns.io and with one domain and multiple domains.
Thank you very much for this!

**Comment by rmbolger** [comment]
Excellent! I'll get the usage guide updated with the details and hopefully have a new release out with it and a bunch of other changes by the end of the week.
