### ISSUE TITLE
Route53 tries to use AWSPowerShell module when it's not installed

### ISSUE THREAD

**Issue by 3apa3a-b-ta3e** [rmbolger/Posh-ACME#263]
On string 360 there is compaction 
`elseif ($null -eq (Get-Module -ListAvailable 'AWSPowerShell')) `

it should be 

`elseif ($null -ne (Get-Module -ListAvailable 'AWSPowerShell'))`

**Comment by 3apa3a-b-ta3e** [comment]
It tries to load **AWSPowerShell** when module is not registered.

**Comment by rmbolger** [comment]
Nice catch, @3apa3a-b-ta3e. Thank you! I'll have this fixed shortly.

**Comment by rmbolger** [comment]
Fixed in 3.15.1 release.
