### ISSUE TITLE
Bluecat DNS Plugin DeployTargets

### ISSUE THREAD

**Issue by NFarris** [rmbolger/Posh-ACME#267]
```
$BlueCatParams = @{
    BlueCatUsername='xxxxxxxx'
    BlueCatPassword='xxxxxxxx'
    BlueCatUri='https://FQDN//Services/API'
    BlueCatConfig='foobar'
    BlueCatView='foobaz'
    BlueCatDeployTargets=@('FQDN1', 'FQDN2', 'FQDN3')
}
New-PACertificate test.example.com -DnsPlugin BlueCat -PluginArgs $BlueCatParams
```

In this block, I am having a hard time understanding what BlueCatDeployTargets are and what they are used for. Can someone help explain this?
@marshallford

**Comment by rmbolger** [comment]
I'd love to help, @NFarris. Unfortunately, I know nothing about BlueCat. Hopefully, @marshallford can chime in.

**Comment by marshallford** [comment]
The param `BlueCatDeployTargets` is expecting an array of server names that you'd like to manually deploy DNS to (as opposed to waiting for a scheduled deploy).

Straight from the BAM API Document:
```
Deploy Server Configuration
Allows you to deploy specific configuration(s) to a particular server.
Output / Response:  Deploys specific configuration(s) to a particular server.
API Call: void deployServerConfig( long serverId, String properties )
```

**Comment by rmbolger** [comment]
Thanks for the help, @marshallford. Hey @NFarris, did that answer your question well enough to close this issue?

**Comment by NFarris** [comment]
Yes, thank you
