### ISSUE TITLE
Importing Posh-ACME fails on initial run with Resource-Unavailable

### ISSUE THREAD

**Issue by harrisonmeister** [rmbolger/Posh-ACME#268]
I have the following powershell script running on a fresh windows server VM (the VM is created new each day)

```powershell
Write-Host "Checking for required modules."

$required_posh_acme_version = 3.12.0
$module_check = Get-Module -ListAvailable -Name Posh-Acme | Where-Object { $_.Version -ge $required_posh_acme_version }

if (-not ($module_check)) {
    Write-Host "Installing Posh-ACME."
    Install-Module -Name Posh-ACME -MinimumVersion 3.12.0 -Scope CurrentUser -Force
}

Import-Module Posh-ACME

# Removed rest of script for simplicity
```
Recently, since running this I get this error:

`ResourceUnavailable: The specified module 'Posh-ACME' was not loaded because no valid module file was found in any module directory.`

On re-running the above script it works fine.

I am doing something wrong, or is there anything I can do to make my script work first time?

To provide some additional context, the script is called through Octopus Deploy, using a run a script step and the service runnig the powershell runs as Local System.

**Comment by rmbolger** [comment]
Hey @harrisonmeister, that looks like a reasonable script to me. The only thing I can think of would be something relating to the `PSModulePath` environment variable. Is there any way to log what its value is between when it doesn't work and when it does work? Or is there anything else that runs between when it fails and when it succeeds?

**Comment by harrisonmeister** [comment]
Hey @rmbolger 

Thanks for confirming it looks ok :) - nothing else runs between then it fails and it succeeds.

The script above is the start of a larger script that fails on the `Import-Module` command first time. I'll spend some time in the next day or so printing out the `PSModulePath` and let you know what I get in the output.

**Comment by harrisonmeister** [comment]
So running the following script:

```powershell
Write-Host "PSModulePath details"
Write-Host "===================="
Write-Host $env:PSModulePath
Write-Host "===================="

Write-Host "Checking for required modules."

$required_posh_acme_version = 3.12.0
$module_check = Get-Module -ListAvailable -Name Posh-Acme | Where-Object { $_.Version -ge $required_posh_acme_version }

if (-not ($module_check)) {
    Write-Host "Installing Posh-ACME."
    Install-Module -Name Posh-ACME -MinimumVersion 3.12.0 -Scope CurrentUser -Force
}

Import-Module Posh-ACME
```

On the **first run** (unsuccessful), I get this:

```text
PSModulePath details 
==================== 
WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules 
==================== 
```

![image](https://user-images.githubusercontent.com/1418993/89389176-02c8b780-d6fd-11ea-9ff3-a18a028cd023.png)

On the **subsequent run** (successful), I get this:

```text
PSModulePath details 
==================== 
C:\windows\system32\config\systemprofile\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules 
==================== 
```

![image](https://user-images.githubusercontent.com/1418993/89389622-8e424880-d6fd-11ea-9342-517b69eb6506.png)


So it looks like after the first failure, its adding `C:\windows\system32\config\systemprofile\Documents\` to the start of the `PSModulePath`.

Which from my basic understanding is where Local System (NT Authority) on windows places its "Documents".

So this situation might be unique to me, but wondering if you have any tips on ways to fix it for my use-case?

Thanks!

**Comment by harrisonmeister** [comment]
Just to follow up on this, I can work around the error which I'm sure is a unique situation to me.

I ended up running two powershell script steps, the first to try to import (knowing it would fail)

By doing this, the `PSModulePath` is set when Posh-Acme is imported in the 2nd script.

**Comment by rmbolger** [comment]
Interesting. It looks like PowerShell tries to add the user specific path when the session is created, but I'm guessing the Documents folder doesn't exist for the SYSTEM account until after the `Install-Module` call, so whatever system call it's using to find the Documents folder ends up being empty and just `WindowsPowerShell\Modules` gets added instead.

Since the deploy task is running as SYSTEM, an easy workaround would be to use `-Scope AllUsers` instead of `-Scope CurrentUser`. This will put the module in the system-wide modules folder in `C:\Program Files\Windows\PowerShell\Modules` and you should be good to go.

**Comment by harrisonmeister** [comment]
Ah nice, thanks I'll take a look at that tomorrow :+1:

**Comment by harrisonmeister** [comment]
@rmbolger - Changing to `-Scope AllUsers` worked for me thanks!

**Comment by rmbolger** [comment]
Not sure if it's possible in your workflow. But the other potential fix for this might be to create the SYSTEM account's Documents folder prior to PowerShell loading the first time.

**Comment by harrisonmeister** [comment]
Is there a known way to do that?

**Comment by rmbolger** [comment]
I'd guess it would have to be done by whatever process is launching PowerShell to begin with. Just some additional logic to create the folder if it doesn't already exist.

**Comment by harrisonmeister** [comment]
Thanks I'll look into it some more. I might give the user the option to choose the scope, so it's an explicit decision too.

**Comment by harrisonmeister** [comment]
@rmbolger - confirmed creating the folder like this:

```powershell
$systemUserPsModuleDirectory = "C:\windows\system32\config\systemprofile\Documents\WindowsPowerShell\Modules"
Write-Host "Creating directory: $systemUserPsModuleDirectory"
New-Item $systemUserPsModuleDirectory -ItemType Directory -Force
```

Before the Posh-Acme step runs works great :+1:

**Comment by aiskrenov** [comment]
Posting this in case someone else stumbles on this. I had similar problem with the module import failing only the first time in a session. After some debugging it turned out that my Posh-ACME config has been somehow compromised (VM hasn't been touched in months, no actual explanation how this happened). I had to delete the folder C:\Users\<ExecutingUser>\AppData\Local\Posh-ACME so it can be recreated with a fresh default config. After that everything went back to normal.
