### ISSUE TITLE
Uninstalling Posh-ACME

### ISSUE THREAD

**Issue by LumitoLuma** [rmbolger/Posh-ACME#274]
I would like to know how can I uninstall Posh-ACME from my Windows 10 system. Thanks for your help!

**Comment by rmbolger** [comment]
Hi @LumitoLuma. The answer is going to depend on how you installed it. If you used `Install-Module`, you should be able to use the corresponding `Uninstall-Module` function. If you installed via a manually downloaded zip file or the `instdev.ps1` script, you just need to delete the module folder wherever it was extracted (likely `Documents\WindowsPowerShell\Modules\Posh-ACME`).

If you want to delete any config/cert data as well, that will be in `%LOCALAPPDATA%\Posh-ACME` unless you set a `POSHACME_HOME` environment variable to somewhere else.

**Comment by LumitoLuma** [comment]
@rmbolger Thanks! I will give it a try.

**Comment by rmbolger** [comment]
If you get any errors about not being able to delete a file, make sure all your PowerShell instances that may have had the module loaded are closed (including editors like ISE, VSCode, etc).

**Comment by LumitoLuma** [comment]
Thanks! It worked perfectly for me!
