### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID This server could not prove that it is mydomain.com; its security certificate is from *.azurewebsites.net.

### ISSUE THREAD

**Issue by sam-wheat** [rmbolger/Posh-ACME#279]
Hi Ryan,

I was able to generate certs for my domains however I have run into a problem with one domain.  It was working prior to the new certs being installed so I thought I would check with you.

I have three domains and I created certs for each exactly the same way.  Each cert specifies mydomain.com and www.mydomain.com.

Two of my domains point to the same website.  When I look at the website in Azure portal / TLS/SSL settings I see four bindings:
primarydomain.com
www.primarydomain.com
altdomain.com
www.altdomain.com

There are two thumbprints, one for each domain.

The DNS configuration for primarydomain and altdomain are identical, save some CNAME records I created for authentication for an email provider I use.

When I open my browser and type primarydomain.com, www.primarydomain.com, or www.altdomain.com everything works.

However when I type altdomain.com I get this error:

> Attackers might be trying to steal your information from altdomain.com (for example, passwords, messages, or credit cards). Learn more
> NET::ERR_CERT_COMMON_NAME_INVALID
> This server could not prove that it is altdomain.com; its security certificate is from *.azurewebsites.net. This may be caused by a misconfiguration or an attacker intercepting your connection.

There is a button that allows me to proceed and when I do I am directed to my site however https is not used.  This error occurs in Chrome, Edge, and Brave.

I generated the cert a second time and I still get the same error.

Is there a chance that there is a problem with the cert?  I don't understand why it is happening with only one domain - which makes me think it is a DNS config error.  Any idea where I should look to try to fix this?

Thank you

**Comment by rmbolger** [comment]
Hey @sam-wheat. It doesn't sound to me like anything is wrong with the cert itself. If the one on www.altdomain.com shows both it and altdomain.com in the Subject Alternative Names field, the cert is fine. It sounds like altdomain.com might be configured to use a different cert (or a default Azure cert because it wasn't configured). But I'm not terribly familiar with how Azure website certs are configured. So I can't really offer much advice there.

**Comment by sam-wheat** [comment]
@rmbolger OK thanks.  Looks like a DNS problem,
