### ISSUE TITLE
DNSMadeEasy (and possibly other providers) does not find the zone id when root domain is specified

### ISSUE THREAD

**Issue by ShaBangBinBash** [rmbolger/Posh-ACME#280]
When we use DNS aliasing, we alias to our root secondary domain for the _acme-challenge check.
For example:
**test.device.domain.com** CNAME to **_acme-challenge.example.com**
So we specify:
New-PACertificate **test.device.domain.com** -DnsAlias **example.com** -DnsPlugin DMEasy -PluginArgs ...

Request is
https://api.dnsmadeeasy.com/V2.0/dns/managed//records?recordName={record name}&type=TXT

Should be
https://api.dnsmadeeasy.com/V2.0/dns/managed/{zone id}/records?recordName={record name}&type=TXT

This can likely be fixed by changing the code https://github.com/rmbolger/Posh-ACME/blob/5b1cefbe60fe6ae3ddb289e5a95cc710c9bdedbb/Posh-ACME/DnsPlugins/DMEasy.ps1#L296
to
`    for ($i=0; $i -lt ($pieces.Count-1); $i++) {`
if the code was structured with $i=1 for optimization, reverse order checking may work better:
`    for ($i=($pieces.Count-1); $i -ge 0; $i--) {`

**Comment by rmbolger** [comment]
Thanks for the report, @ShaBangBinBash. I'm looking into the issue now, but you might also have a minor problem with how you're using the aliases.

If the cert you're requesting is for `test.device.domain.com`, then your CNAME record needs to be for `_acme-challenge.test.device.domain.com` rather than just `test.device.domain.com`. Where you have the CNAME pointing to is fine (`_acme-challenge.example.com`), but you also have to specify that same location in the `New-PACertificate` command rather than the `example.com` domain root.

**Comment by rmbolger** [comment]
You are totally correct that starting with `$i=1` in the for loop was an optimization attempt. But it was based on the assumption that The `$RecordName` value would always be at least 1 label longer than the zone name. In retrospect, this was clearly dumb particularly when considering the alias support. 🤦

The problem with reverse order checking is that it will end up finding the parent zones first. But it really shouldn't be a huge deal to just start at 0 for this and the rest of the plugins that do the same thing. In any case, thanks again for the heads up. I should have a fix out soon.

**Comment by rmbolger** [comment]
Ok, the dev/master branch has a fix that should work. I also fixed a bug with the error handling when a zone wasn't found for the specified RecordName value. Let me know how this works for you. I'm off to go fix the rest of the plugins with the same issue.

**Comment by ShaBangBinBash** [comment]
New code in master branch works, I can:

- create record with Publish-DnsChallenge
- remove record with Unpublish-DnsChallenge
- request a certificate with New-PACertificate (using _acme-challenge.example.com as stated above)

**Comment by rmbolger** [comment]
Excellent. Thanks for the follow up!
