### ISSUE TITLE
Please add support for Rimu Hosting

### ISSUE THREAD

**Issue by jasonblewis** [rmbolger/Posh-ACME#282]
Rimu Hosting is a sister company to zonomi and uses the exact same protocol as the zonomi one. It just requires a different endpoint: https://rimuhosting.com/dns/dyndns.jsp

See https://rimuhosting.com/dns/dyndns.jsp

Please could you add an option to the zonomi plugin to allow customising of the API url?

**Comment by pbkwee** [comment]
And the url to generate the api key (per the readme) for RimuHosting is https://rimuhosting.com/cp/apikeys.jsp

**Comment by rmbolger** [comment]
Thanks guys! This should be no problem. I'll have an update committed shortly.

**Comment by rmbolger** [comment]
This is now live in 3.17.0
