### ISSUE TITLE
OVH Plugin : unable to unpublish-dnsChallenge

### ISSUE THREAD

**Issue by ArnoMLT** [rmbolger/Posh-ACME#283]
Hello,

I followed the readme 'How To Use the OVH DNS Plugin' but I ran into an issue when typing this command :

`PS C:\Windows\system32> Publish-DnsChallenge site1.example.com -Account $acct -Token faketoken -Plugin OVH -PluginArgs $pArgs -Verbose`
`COMMENTAIRES : GET https://eu.api.ovh.com/1.0/domain/zone/site1.example.com/record?fieldType=TXT with 0-byte payload`
`COMMENTAIRES : GET https://eu.api.ovh.com/1.0/domain/zone/example.com/record?fieldType=TXT with 0-byte payload`
`COMMENTAIRES : received 23-byte response of content type application/json; charset=utf-8`
`COMMENTAIRES : GET https://eu.api.ovh.com/1.0/domain/zone/example.com/record?fieldType=TXT&subDomain=_acme-challenge.site1 with 0-byte payload`
`COMMENTAIRES : received 2-byte response of content type application/json; charset=utf-8`
`COMMENTAIRES : Adding a TXT record for _acme-challenge.site1.example.com with value J9fBlkhvalB5QhB5J59rYD1C2Z4ASIE1i4b7xYVoT58`
`COMMENTAIRES : POST https://eu.api.ovh.com/1.0/domain/zone/example.com/record with -1-byte payload`
`COMMENTAIRES : received 155-byte response of content type application/json; charset=utf-8`

`PS C:\Windows\system32> unPublish-DnsChallenge site1.example.com -Account $acct -Token faketoken -Plugin OVH -PluginArgs $pArgs -Verbose`
`COMMENTAIRES : GET https://eu.api.ovh.com/1.0/domain/zone/example.com/record?fieldType=TXT&subDomain=_acme-challenge.site1 with 0-byte payload`
`COMMENTAIRES : received 12-byte response of content type application/json; charset=utf-8`
`COMMENTAIRES : GET https://eu.api.ovh.com/1.0/domain/zone/example.com/record/5143269228 with 0-byte payload`
`COMMENTAIRES : received 155-byte response of content type application/json; charset=utf-8`
`COMMENTAIRES : Removing TXT record for _acme-challenge.site1.example.com with value
J9fBlkhvalB5QhB5J59rYD1C2Z4ASIE1i4b7xYVoT58`
`COMMENTAIRES : DELETE https://eu.api.ovh.com/1.0/domain/zone/example.com/record/ with 0-byte payload`
`Invoke-RestMethod : {"message":"The call does not answer to the DELETE HTTP method"}`
`Au caractère C:\Program Files\WindowsPowerShell\Modules\posh-acme\3.16.0\DnsPlugins\OVH.ps1:417 : 5`
`+     Invoke-RestMethod @restArgs @script:UseBasic -EA Stop`
`+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException`
`    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

The TXT record is not deleted.

Where am I wrong ?

**Comment by rmbolger** [comment]
Hi @ArnoMLT. Sorry about the trouble. Let's see if we can figure it out.

Which method from the guide did you use to generate the consumer key? Write all zones, specific zones, or specific records?

**Comment by ArnoMLT** [comment]
Hi @rmbolger 

Thanks for trying to help me :)

I generated a consumer key for specific zones (2)

I tried to generate it a second time (same appkey) to check assigned rights : 
Access Granted :
    GET on /domain/zone/example.com/record*
    POST on /domain/zone/example.com/record
    DELETE on /domain/zone/example.com/record/*
    POST on /domain/zone/example.com/refresh
    GET on /domain/zone/example2.com/record*
    POST on /domain/zone/example2.com/record
    DELETE on /domain/zone/example2.com/record/*
    POST on /domain/zone/example2.com/refresh

(OvhRegion = ovh-eu)

**Comment by rmbolger** [comment]
Thanks for the detail. The upside is that you did nothing wrong and this is just a silly bug. I've already identified the problem and should be committing a fix shortly.

**Comment by rmbolger** [comment]
The fix is now in the master/dev branch if you want to test it. I probably won't push a new release before I finish up a minor new feature I've been working on. But hoping that will be sometime this weekend.

**Comment by ArnoMLT** [comment]
Hi @rmbolger 

I've just tested. That's ok for me !
Thank you  very much !
