### ISSUE TITLE
Windows DNS Plugin Not Working for Multi-Domain Requests

### ISSUE THREAD

**Issue by smaitlx1** [rmbolger/Posh-ACME#286]
When generating requests for multiple domain names, the Windows DNS plugin errors with "authorization invalid: NXDOMAIN" on one or more of the requested domains.  Looking in the DNS management console reveals that _acme-challenge records are only being created for some of the domains in the request.  The domains that get created are different each time it's attempted.

**Comment by rmbolger** [comment]
Hi @smaitlx1. Sorry to hear you're having some trouble. I'm going to need a bit more information to try and help you work out what's wrong though. The NXDOMAIN error means the ACME server couldn't find the record the plugin was supposed to write on the external DNS servers for that domain. But there could be a number of reasons for that.

My initial guess is that this is just a timing problem. If your DNS servers are replicated via AD and the server you're writing to isn't the server being queried from the Internet, the records may not have been replicated to the external facing server by the time the module asks the ACME server to check them. So you might start by just setting the `-DnsSleep` parameter a few minutes longer than it's set to now. The default is 120 (2 minutes). So if you're not setting something else already, try `-DnsSleep 300` (5 minutes).

If the Windows DNS plugin was having problems actually writing the records to the DNS server, it should have thrown an error and never made it to the point where it asks the ACME server to check the records. When you try again, can you run the command with the `-Verbose` flag and post the (optionally sanitized) results here?

**Comment by smaitlx1** [comment]
As I stated in the original post, looking in the DNS management console reveals that _acme-challenge records are only being created for some of the domains in the request. The domains that get created are different each time it's attempted.

All domains have successfully had _acme-challenge records created in them, but it takes multiple passes of the New-PACertificate command to generate them, and I also see it delete ones from previous passes when it's run again, so multiple passes is not enough to get past the problem.

The zones are indeed AD-integrated, but the cmdlet is being run against a specific nameserver and that's the only one I'm looking at in the DNS MMC snapin for the purposes of identifying whether or not the necessary records are actually created.

Additionally, the nameserver the cmdlet is being run against is configured to provide update notices for record changes to the other two nameservers, so even with AD replication delays, they should be current within the ~60 seconds the cmdlet waits.

**Comment by smaitlx1** [comment]
Here's an example set of attempts.

Pass 1:
Script input:
New-PACertificate "*.nosc.us","*.visionnet.us","*.hypergate.us","*.planarrift.com","*.fistofthevoid.com","*.saturdragons.com" `
	-DnsPlugin Windows -PluginArgs @{WinServer='ns1.hypergate.us'; WinCred=$Cred} `
	-DirectoryUrl LE_PROD `
	-AcceptTOS `
	-PfxPass '<REDACTED>'

Script output:
WARNING: Fewer DnsPlugin values than names in the order. Using Windows for the rest.
Authorization invalid for *.saturdragons.com: During secondary validation: DNS problem: NXDOMAIN looking up TXT for
_acme-challenge.saturdragons.com - check that a DNS record exists for this domain
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.12.0\Private\Wait-AuthValidation.ps1:34 char:17
+ ...             throw "Authorization invalid for $($auth.fqdn): $message" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Authorization i...for this domain:String) [], RuntimeException
    + FullyQualifiedErrorId : Authorization invalid for *.saturdragons.com: During secondary validation: DNS problem:
   NXDOMAIN looking up TXT for _acme-challenge.saturdragons.com - check that a DNS record exists for this domain

Results in MMC:
_acme-challenge.fistofthevoid.com ->PQIDMLEZxcqMgZrv_x96gX_f-MUN4sYlHGjrH6zEB9s
_acme-challenge.hypergate.us -> NXDOMAIN
_acme-challenge.nosc.us -> NXDOMAIN
_acme-challenge.planarrift.com -> AN2ySeRpLYNlosafgEjT1K3FKVITrBN5BXKRHKj8xAo
_acme-challenge.saturdragons.com -> FFgvqHdgc8W88n0oGAFjH6o1z8wCDnNGENKm5NXHhHc
_acme-challenge.visionnet.us -> NXDOMAIN

Pass 2:
Script input:
New-PACertificate "*.nosc.us","*.visionnet.us","*.hypergate.us","*.planarrift.com","*.fistofthevoid.com","*.saturdragons.com" `
	-DnsPlugin Windows -PluginArgs @{WinServer='ns1.hypergate.us'; WinCred=$Cred} `
	-DirectoryUrl LE_PROD `
	-AcceptTOS `
	-PfxPass '<REDACTED>'

Script output:
WARNING: Fewer DnsPlugin values than names in the order. Using Windows for the rest.
(There was no error on this attempt--this was not an omission)

Results in MMC:
_acme-challenge.fistofthevoid.com ->NXDOMAIN
_acme-challenge.hypergate.us -> NXDOMAIN
_acme-challenge.nosc.us -> JRL8HJscSmD6OTMmWITs2CCu1cgFgmXxBpQDDnwvBQvV8x4pdBH5/89oZw1dzKDc2ZeIu+x6V1jM1XlwVsplHQ==
_acme-challenge.planarrift.com -> NXDOMAIN
_acme-challenge.saturdragons.com -> NXDOMAIN
_acme-challenge.visionnet.us -> NXDOMAIN

**Comment by rmbolger** [comment]
I need you to run the command with the `-Verbose` flag and post that output so we can see more of what the module is attempting to do rather than only the warnings and errors. Additionally, if you want to validate just the plugin's ability to publish/unpublish the records, you can run the following for example.

```powershell
# don't include the *. for the wildcards
Publish-DnsChallenge hypergate.us (Get-PAAccount) faketoken Windows @{WinServer='ns1.hypergate.us';WinCred=$Cred} -verbose

# when you want it removed, it's the same arguments with Unpublish-DnsChallenge
Unpublish-DnsChallenge hypergate.us (Get-PAAccount) faketoken Windows @{WinServer='ns1.hypergate.us';WinCred=$Cred} -verbose
```

**Comment by smaitlx1** [comment]
It looks like the pass today was successful as a certificate was actually generated and contained all the domains in it.  I'm thinking the reason today's records are mostly NXDOMAIN is because it was able to successfully validate some of the domains previously.

**Comment by smaitlx1** [comment]
Do you know whether the behavior is to skip creating records for domains that have been verified within the last X days?

**Comment by smaitlx1** [comment]
I don't generally use domain.com itself for anything in my public DNS because Active Directory uses A records domain.com for IPs of all the DCs, so I can't have a matching internal record for the external domain.com.

Good information, though.

**Comment by smaitlx1** [comment]
I have an automation process that calls Submit-Renewal daily against any certs that are 15 days or less from expiration, so if that starts failing I'll reopen this.  For now, I think we have what we're gonna get.  We'll know in ~75 days (sooner if I need new certs) whether it's resolved.

All I can think of is the resource forest that supplies public DNS zones was built out just a couple days before this issue started (Google Cloud DNS used to be where it was at) and perhaps we were running into initialization delays for the zone config or something in the change notices wasn't running yet.

**Comment by rmbolger** [comment]
The way you've got things setup should work just fine. But if you want to simplify, you can just run Submit-Renewal daily and it will ignore any orders that haven't reached their suggested renewal window (1/3 of the cert time remaining or 30 days whichever is lower).
