### ISSUE TITLE
Error: "Get-Content : A parameter cannot be found that matches parameter name 'Raw'" if wrong folder

### ISSUE THREAD

**Issue by mcnahum** [rmbolger/Posh-ACME#287]
I Just want to report an issue who cost me time to identify.

When I was running "Import-Module Posh-ACME" I got the error:

"Get-Content : A parameter cannot be found that matches parameter name 'Raw'"

after looking everywhere ... I noticed it's because I did a "cd Cert:\LocalMachine\My\" before ... and in that path.. of course it was not working...

going to a folder, fixed it..

**Comment by rmbolger** [comment]
That's a weird one for sure. I wouldn't have thought the current directory not being a filesystem path would affect the ability to import modules.

**Comment by mcnahum** [comment]
same. This is why I wanted to have it referenced here...
