### ISSUE TITLE
BouncyCastle Crypto incompatible with Az.KeyVault assembly

### ISSUE THREAD

**Issue by MattiasAng** [rmbolger/Posh-ACME#288]
Version of BouncyCastle Crypto in Posh-ACME causes Az.KeyVault to not load (and vice versa).
Error: 
`Import-Module: Assembly with same name is already loaded`

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.20201
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Get-Module Az.Keyvault | select Version

Version
-------
3.0.0


Get-Module posh-acme | select version

Version
-------
3.18.0
```

I was able to workaround it by copying the assembly from Az.Keyvault module.

**Comment by rmbolger** [comment]
Thanks for the report, @MattiasAng. This will continue to be an annoying problem as more stuff depends on BouncyCastle in PowerShell. Interestingly, it doesn't seem to be a problem in legacy Windows PowerShell...at least, both modules load normally. I haven't had a chance to actually test that they can do individual crypto stuff.

You may have noticed that I renamed the DLL Posh-ACME is using. Ironically, this was to workaround a similar problem I had a while back in Windows PowerShell where some MS App was putting an old version of BouncyCastle in the GAC. I was hoping the name difference would keep it from conflicting with other stuff. But apparently .NET Core loads things in a way that doesn't care about the actual file name.

In any case, Posh-ACME should work just fine with the newer BC version. I'll see about releasing a new version that has BC version parity with keyvault. But it's likely only a temporary solution until I can work out the best way to remove the BC dependency entirely.

**Comment by MattiasAng** [comment]
Thanks for the quick answer.

A workaround you could do is compiling BouncyCastle.Crypto yourself and setting a different strong name.
In that case no code changes will be needed and would be quite easy to include a step in your pipeline to compile new versions.

Let me know if you want to further discuss and/or help with this.

**Comment by rmbolger** [comment]
Perhaps I'm overthinking it, but compiling a custom version of BouncyCastle puts me in a weird trust position I'm not sure I'm comfortable with. Anyone using Posh-ACME would then have to trust my modifications (as benign as they might be) to a critical crypto library. And in order for them to verify the binary included with the module, I'd have to publish the source for my changes somewhere as well?

**Comment by rmbolger** [comment]
Closing this for now as the initial issue has been resolved. But I'll keep mulling over the underlying problem.
