### ISSUE TITLE
Different Azure cloud environments not supported

### ISSUE THREAD

**Issue by InKahootz** [rmbolger/Posh-ACME#293]
The Azure DNS plugin currently only works with the public Azure cloud that most people work with, however there are three more separate clouds: US Government, Germany, and China.

Cross cloud request are not permitted so the API calls fail or just fail to find the subscription in general.
The fix is to have specific endpoint URLs for the cloud you want.

I've gone ahead and implemented this and sent in a PR.

**Comment by rmbolger** [comment]
This is awesome, @InKahootz. Thank you! Give me a bit to test some stuff, but everything looks good at first glance.

**Comment by InKahootz** [comment]
Thanks for the quick response!
I'm testing things as well. 

I've personally tested some of the URL changes
- [ ] Azure Cloud using a service principle
- [ ] Azure US Government with Access Token (this is a Azure Resource Manager service connection in our Devops Server)

I'm trying to hit all the main branches in the `Connect-AzTenant` function under `Azure.ps1`. So I have yet to test IMDS and certificate based.
