### ISSUE TITLE
Issue with the new Simply DNSPlugin

### ISSUE THREAD

**Issue by kaspersmjohansen** [rmbolger/Posh-ACME#294]
I am seeing this error message with the new Simply DNS plugin:
![X7NQJmEx9f](https://user-images.githubusercontent.com/37331486/100085327-336b6300-2e4c-11eb-8916-3a4820355607.jpg)

I am using the the SimplyAPIKeyInsecure, like this:
$Params = @{SimplyAccount = 'accountID'
            SimplyAPIKeyInsecure = 'APIkey'
}

If I use the SimplyAPIKey like this:
$Params = @{SimplyAccount='UE237845'
            SimplyAPIKey = (Read-Host 'Enter Key' -AsSecureString)
}

It looks like the secure string is not "decrypted" or converted to the actual API key value:
![1haXwLEPTB](https://user-images.githubusercontent.com/37331486/100086583-e8524f80-2e4d-11eb-917b-f6bb41335cfc.jpg)

**Comment by rmbolger** [comment]
Sorry about that, @kaspersmjohansen. Looks like I was too hasty in the conversion from UnoEuro trying to add a secure token parameter and forgot a bunch of variable references. I just committed a fix that should fix things. Can you test it for me?

**Comment by kaspersmjohansen** [comment]
How do I test the fix? I have tried copying the Simply.ps1 script to the DNSPlugins folder, getting the same error message.

**Comment by rmbolger** [comment]
Copying the updated file ([this one](https://raw.githubusercontent.com/rmbolger/Posh-ACME/master/Posh-ACME/DnsPlugins/Simply.ps1)) should work as long as you test it from a new PowerShell session or force re-import the module using `Import-Module Posh-ACME -Force`. The other way is to use the `instdev.ps1` script like this which will pull down a fresh copy of the whole module from github into your user profile's module folder.

```powershell
iex (irm https://raw.githubusercontent.com/rmbolger/Posh-ACME/master/instdev.ps1)
```

Also, you should be able to test just the plugin without having to actually request a cert, by running `Publish-DnsChallenge` and `Unpublish-DnsChallenge` by themselves like this:

```powershell
Publish-DnsChallenge example.com (Get-PAAccount) faketoken Simply $Params -verbose
Unpublish-DnsChallenge example.com (Get-PAAccount) faketoken Simply $Params -verbose
```

**Comment by kaspersmjohansen** [comment]
Now it get another error message:
![image](https://user-images.githubusercontent.com/37331486/100140859-d397ab00-2e91-11eb-97cc-7368ea8805c7.png)

**Comment by rmbolger** [comment]
Hmmm...according to the original author who wrote the UnoEuro plugin, the API usually only throws 200 or 400 responses and a 404 means "something is very wrong".

Were you previously using the UnoEuro plugin successfully and are trying to migrate to the Simply plugin? If so, this almost seems like the Simply API doesn't recognize your Account/Key values. I might need to suck it up and register a domain with them in order to test for myself. But can you try something for me first? Let me know what you get running each of the following:

```powershell
# substitue your actual account/key values where appropriate
Invoke-RestMethod 'https://api.simply.com/1/ACCOUNT/KEY/my/products'
Invoke-RestMethod 'https://api.unoeuro.com/1/ACCOUNT/KEY/my/products'
```

If the UnoEuro one shows results and the Simply one doesn't, then my understanding of how the transition from UnoEuro to Simply worked was mistaken.

**Comment by kaspersmjohansen** [comment]
Yes, I have been using the UnoEuro plugin for quite some time. My account information hasn't changed, since UnoEuro became Simply, so same account number and API key.

I have tested both Invoke-RestMethod commands, and they both work. They both return the list of domains I have registered at Simply and a success message and a status of 200.
![image](https://user-images.githubusercontent.com/37331486/100184873-c656dc80-2ee2-11eb-8e42-d6069d830fa5.png)

**Comment by webprofusion-chrisc** [comment]
Out of interest, why would the api call using `_acme-challenge.domain.com` as the API zone parameter? Shouldn't it be just `domain.com`?

**Comment by rmbolger** [comment]
It's part of a function that is searching for the base zone starting with the full record name. It's a pretty common check in most of these plugins to account for providers that allow for sub zone creation or inbound delegation. For a long name like `_acme-challenge.sub1.sub2.example.com` it tries each combination of labels starting with the longest and moving down to the shortest. So:

- _acme-challenge.sub1.sub2.example.com
- sub1.sub2.example.com
- sub2.example.com
- example.com

In any case, I'm probably going to just register a domain with them so I can test for myself what's going on.

**Comment by kaspersmjohansen** [comment]
Thanks Ryan. Let me know if you need any further testing, I am a great guinea pig :P

**Comment by rmbolger** [comment]
OK, I basically re-wrote the plugin from scratch after getting my own Simply account/domain setup. Everything seems to working now in my own tests. Care to give it a try, @kaspersmjohansen?

I'm not exactly sure how the old UnoEuro plugin ever worked for anything other than names that matched the root domain. Maybe it didn't any no one ever noticed? I'm guessing 4e7f6bd also broke it a while back even for root domains unless people were using DNS aliases. In any case, I'm going to leave it as-is until Simply is no longer supporting the old API endpoint and just tell people to migrate to the Simply plugin if they ask about it.

**Comment by kaspersmjohansen** [comment]
@rmbolger it works perfectly now, thank you. I just ordered a new certificate using the Simply DNS plugin, with no issues at all.

**Comment by rmbolger** [comment]
Excellent. I'll try to get a release out with the update in the next day or two.

**Comment by leifnel** [comment]
A stray comment: the acme.sh uses api v1, but the documentation on simply is only for v2. Is v1 inoperative?
v2 doesn't have the account/apikey in the url as v1 does, but as the http username/password which acme.sh doesn't support directly.

**Comment by rmbolger** [comment]
Hey @leifnel. This is the first I've heard of Simply upgrading their API. My guess is the change is relatively recent and both Posh-ACME and acme.sh need an update. But what's weird is that in my tests the v1 API still seems to be responding, but it seems to have changed in subtle ways that can make existing clients break. Most importantly, the endpoint that allowed the actual TXT record creation now just returns "An error occurred" in JSON.

**Comment by rmbolger** [comment]
For what it's worth, the Posh-ACME plugin is now updated to use v2 of the API. The changes were fairly straightforward and I wouldn't think would be very hard to implement in acme.sh.
