### ISSUE TITLE
Documentation issue with semi-manual DNS page

### ISSUE THREAD

**Issue by jordanmills** [rmbolger/Posh-ACME#298]
URL: https://github.com/rmbolger/Posh-ACME/wiki/%28Advanced%29-Semi-Manual-DNS-Challenge-Validation

This 
`@{L='TXTValue';E={Get-KeyAuthorization $_.DNS01Token -ForDNS)}}`
should be 
`@{L='TXTValue';E={(Get-KeyAuthorization $_.DNS01Token -ForDNS)}}`

(i.e. an open parenthesis is missing before Get-KeyAuthorization)

**Comment by rmbolger** [comment]
Great catch, @jordanmills! Thanks. Fixed.
