### ISSUE TITLE
Azure: (Get-AzContext).TokenCache no longer available in latest Az-Module

### ISSUE THREAD

**Issue by cwe1ss** [rmbolger/Posh-ACME#300]
Using AzContext.TokenCache as described in https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Azure-Readme.md#optional-using-an-existing-access-token is no longer possible with Az.Accounts > 1.9.5 as the TokenCache property has been removed.

The new way to get the access token is:

```ps
$accessToken = (Get-AzAccessToken -ResourceUrl "https://management.core.windows.net/" -TenantId $tenantId).Token
````

See for details: https://github.com/Azure/azure-powershell/issues/13337

**Comment by rmbolger** [comment]
Hey @cwe1ss. Thanks for the heads up. I'll update the guide with the clarification between versions.
