### ISSUE TITLE
UnoEuro plugin no longer works because Simply disabled the API endpoint

### ISSUE THREAD

**Issue by OrKarstoft** [rmbolger/Posh-ACME#303]
Hey @rmbolger!

March 2020 the DNS provider Unoeuro changed name to Simply. In the end of 2020 they changed their API so the [Unoeuro plugin](rmbolger/Posh-ACME/blob/main/Posh-ACME/Plugins/UnoEuro.ps1) is not working any more.

I see that there's already a Simply plugin and it works perfectly with minimal changes from the Unoeuro plugin.

**Comment by rmbolger** [comment]
Hey @OrKarstoft. Thanks for the confirmation that Simply disabled the Unoeuro API endpoint. I had already added notes in the user guide and wiki about the deprecation. So I'll probably remove it entirely in the next release.
