### ISSUE TITLE
Domeneshop plugin breaks due to partial string matching

### ISSUE THREAD

**Issue by jhr862** [rmbolger/Posh-ACME#305]
We have two domains like this:
example.com
theexample.com

This breaks the plugin, as the api query returns both domains.
We implemented this workaround on line 278:
Where-Object -FilterScript { $_.Status -ieq 'active' -and $_.services.dns -and $_.domain -eq $zoneTest}

**Comment by rmbolger** [comment]
Good find, @jhr862! And thanks for the suggested fix. I committed the change to the main branch if you want to test it before I push a release.
