### ISSUE TITLE
Please create the following TXT records:

### ISSUE THREAD

**Issue by modemgeek** [rmbolger/Posh-ACME#323]
I'm not sure if upgrading to v4 caused it or I am doing something wrong.
We have customers whose DNS we don't manage so it requires HTTP validation. I've created the challenge file and uploaded it to my webserver.  The verification process passes and then all of a sudden my script stops at 
`Please create the following TXT records:`
This is the part that stumps me because if I am doing HTTP validation why would I need to add a TXT record.  We are running this in an automated script and the script hangs because it is expecting input.  Is there any way to prevent it from asking for a TXT record?  This is the command I am issuing
`New-PACertificate -Domain $HostNames -AcceptTOS -PfxPass $CertPass -FriendlyName $HostNames -Contact $ContactEmail`

The odd thing is if I cancel the script and just run this one line only, I am able to obtain the certificate.

**Comment by modemgeek** [comment]
I seem to have fixed this by specifying one of the HTTP plugins.  Not urgent now but was there a change in the latest version 4?
`-Plugin WebRoot -PluginArgs $pArgs`

**Comment by rmbolger** [comment]
Hey @modemgeek. Thanks for reaching out. It's possible this was an unintended consequence of the plugin architecture changes in 4.x. But theoretically using `New-PACertificate` with no plugin specified has always defaulted to using the Manual DNS plugin which would prompt for TXT record creation. I do recall some old bugs in 3.x that made it possible to create an order with a `$null` plugin value though.

Out of curiosity, what version of 3.x did you upgrade from? And can you post your script (or at least enough of it to see the cert request process) where it was previously working without prompting?

**Comment by modemgeek** [comment]
Our server is running 3.11.0
`            #New order for non DNS cert request
            New-PAOrder $Fqdn -force
           
            #get order authorizations
            $order=  Get-PAOrder | Get-PAAuthorizations #| fl
            #Revoke-PAAuthorization https://acme-v02.api.letsencrypt.org/acme/authz-v3/10380596620
            #The order generates a ChallengeToken
            $ChallengeToken = $order.HTTP01Token
            
            #Get the key authorization using the ChallengeToken to form the full token 
            $Getfulltoken = Get-KeyAuthorization $ChallengeToken
    
            #Copy full token to the local file ACMEChallengeFile.Txt
            $Getfulltoken | Out-File -Encoding ASCII -NoNewline -FilePath ".\ACMEChallengeFile.txt"

            #Specify Webfile directory where the Fulltoken will be uploaded to
            $challengefile = "/.well-known/acme-challenge/$ChallengeToken"

            #Call Copy-FileToWebApp function in WebAppFiles.ps1 script to copy the ChallengeToken to the WebAppfiles
            $WebAppCredential = Copy-FileToWebApp -WebAppName $WebAppName -ResourceGroupName $ResourceGroupName -Destination $challengefile -File ".\ACMEChallengeFile.txt" #Copy challenge file webappftp by calling (/WebAppFile/Copy-FileToWebApp)
       
            #Submit cahllenge 
            $order.HTTP01Url| Send-ChallengeAck
        
            #Get the order status
            Get-PAOrder -Refresh
          
            #Because DNS is not Hosted in Amazon, no pluggin is used and only the CustomDomain Name is used in the certificate request.
            New-PACertificate -Domain $Fqdn -NewCertKey -PfxPass $CertPass -FriendlyName $Alias -Contact $ContactEmail `

I'm making changes locally on my computer running 4.2.0 and this is where it keeps prompting for a TXT record when I don't specify a plugin

**Comment by rmbolger** [comment]
Perfect, thanks. I can't see anything obviously wrong with the code that shouldn't work in 4.x the same way it did in 3.x. In particular, the final call to `New-PACertificate` shouldn't need to invoke a plugin (and thus prompt for TXT record creation by the default Manual plugin) if the status of the order is "ready". And it should be "ready" assuming assuming the ACME validation initiated by `Send-ChallengeAck` was successful.

This might just be a timing issue. `Send-ChallengeAck` only asks the ACME server to *start* validating the challenge. So if the server hasn't finished before `New-PACertificate` is called, the module would still see the order as "pending" and try to validate the challenges with the default plugin. As a quick test, you could try putting a `Start-Sleep 10` right after `Send-ChallengeAck`. If that fixes the problem, I'd suggest putting the `Get-PAOrder -Refresh` code in a loop and making sure the returned order status is either "valid" or "invalid" before continuing.

Another option depending on the complexity of your `Copy-FileToWebApp` function is that you could convert that function into a native Posh-ACME plugin which would let you simplify the overall script.

**Comment by rmbolger** [comment]
> The odd thing is if I cancel the script and just run this one line only, I am able to obtain the certificate.

This is another thing that makes it sound like timing is ultimately the problem. By the time you've canceled the script and re-run the command, the ACME server has finished validating the challenge.

**Comment by modemgeek** [comment]
> > The odd thing is if I cancel the script and just run this one line only, I am able to obtain the certificate.
> 
> This is another thing that makes it sound like timing is ultimately the problem. By the time you've canceled the script and re-run the command, the ACME server has finished validating the challenge.

This was my thinking as well.  I put a 60 second wait and I would still see it happening.  As this isn't really a big issue, I'm fine with closing it as it is working for me now by specifying the HTTP plugin.

**Comment by rmbolger** [comment]
Here's an example of what the status check loop might look like:

```powershell
$order.HTTP01Url| Send-ChallengeAck

# wait for the order to become valid or invalid
$tries = 0
while (($order = Get-PAOrder -Refresh).status -notin 'valid','invalid' -and $tries -lt 30) {
    Start-Sleep 1
    $tries++
}

if ($order.status -eq 'valid') {
    #Because DNS is not Hosted in Amazon, no pluggin is used and only the CustomDomain Name is used in the certificate request.
    New-PACertificate -Domain $Fqdn -NewCertKey -PfxPass $CertPass -FriendlyName $Alias -Contact $ContactEmail
}
elseif ($order.status -eq 'invalid') {
    throw "Order status was invalid. Validation likely failed."
}
else {
    throw "Timed out waiting for order status to change after validation."
}
```

**Comment by rmbolger** [comment]
The other thing you could do to avoid the plugin prompt is skip `New-PACertificate` entirely. In 4.x, there's now a `Complete-PAOrder` function which is the only other thing `New-PACertificate` calls after finalizing the order. So once the order reaches the "ready" state, you'd just call:

```powershell
Submit-OrderFinalize
Get-PAOrder -Refresh # status should now be "valid"
Complete-PAOrder
```

In any case, happy to hear you've got it working well enough for your needs. I'll close the issue.

P.S. I also just remembered in 4.x `Get-PAAuthorizations` (plural) is now `Get-PAAuthorization` (singular). There's an alias for the plural version, but it will likely go away whenever 5.x rolls around. I haven't even started working on that, so no rush.
