### ISSUE TITLE
Route53 plugin fails to detect AWS modules when imported from outside PSModulePath folders

### ISSUE THREAD

**Issue by modemgeek** [rmbolger/Posh-ACME#324]
Sorry to be a pain, but was wondering if anyone has gotten this to run under an Azure function.

I had a bumpy start at first but after importing this modules, i was making progress
`import-module 'D:\Home\site\wwwroot\AddHostNameSSL\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.psd1'
import-module 'D:\Home\site\wwwroot\AddHostNameSSL\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.psd1'
import-module 'D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Posh-ACME.psd1'`

I believe these are the only 3 that I need.

Everything goes fine until i get to 
`New-PACertificate $RootDomain -AcceptTOS -Contact $ContactEmail -Plugin Route53 -DNSAlias $ChallengeDomain -PluginArgs $pArgs -PfxPass $CertPass -Verbose`

The error I get is 

> [Error] ERROR: An AWS PowerShell module is required to use this plugin with the R53ProfileName parameter. https://docs.aws.amazon.com/powershell/Exception             :Type                        : System.Management.Automation.RuntimeExceptionErrorRecord                 :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : An AWS PowerShell module is required to use this plugin with the R53ProfileName parameter. https://docs.aws.amazon.com/powershell/HResult : -2146233087CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : RuntimeExceptionWasThrownFromThrowStatement : TrueTargetSite                  :Name          : ThrowTerminatingErrorDeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35MemberType    : MethodModule        : System.Management.Automation.dllStackTrace                  :at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Message                     : An AWS PowerShell module is required to use this plugin with the R53ProfileName parameter. https://docs.aws.amazon.com/powershell/Source                      : System.Management.AutomationHResult                     : -2146233087TargetObject          : An AWS PowerShell module is required to use this plugin with the R53ProfileName parameter. https://docs.aws.amazon.com/powershell/CategoryInfo          : OperationStopped: (An AWS PowerShell m…zon.com/powershell/:String) [Submit-ChallengeValidation], RuntimeExceptionFullyQualifiedErrorId : An AWS PowerShell module is required to use this plugin with the R53ProfileName parameter. https://docs.aws.amazon.com/powershell/,Submit-ChallengeValidationInvocationInfo        :MyCommand        : Submit-ChallengeValidationScriptLineNumber : 216OffsetInLine     : 9HistoryId        : 1ScriptName       : D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\New-PACertificate.ps1Line             : Submit-ChallengeValidationPositionMessage  : At D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\New-PACertificate.ps1:216 char:9+         Submit-ChallengeValidation+         ~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : 

It's like i'm missing a module or something isn't getting loaded correctly.  Maybe it's having issues passing arguments through

**Comment by rmbolger** [comment]
No worries, @modemgeek. I think this one is my fault. The logic for whether the plugin tries to use the AWS module or raw REST calls is a bit complicated and I think I hadn't accounted for someone using the modules from outside the folders defined by the PSModulePath environment variable.

Let me test a few things on my end, but I can probably fix this for you.

Alternatively, you might be able to work around the issue by adding `D:\Home\site\wwwroot\AddHostNameSSL\Modules` to the PSModulePath environment variable.

**Comment by modemgeek** [comment]
I tried setting the PSModulePath
`$env:PSModulePath = $env:PSModulePath + ";D:\Home\site\wwwroot\AddHostNameSSL\Modules"`

I did get further and I was able to obtain the certificate.  Not sure what the following error is about though


`2021-03-12T14:50:41.487 [Error] ERROR: The pwsh executable cannot be found at "D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exe".Note that 'Start-Job' is not supported by design in scenarios where PowerShell is being hosted in other applications. Instead, usage of the 'ThreadJob' module is recommended in such scenarios.Exception             :Type        : System.Management.Automation.PSNotSupportedExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : The pwsh executable cannot be found at "D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exe".Note that 'Start-Job' is not supported by design in scenarios where PowerShell is being hosted in other applications. Instead, usage of the 'ThreadJob' module is recommended in such scenarios.HResult : -2146233087CategoryInfo          : NotImplemented: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : NotSupportedTargetSite  :Name          : ThrowTerminatingErrorDeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35MemberType    : MethodModule        : System.Management.Automation.dllStackTrace  :at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Message     : The pwsh executable cannot be found at "D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exe".Note that 'Start-Job' is not supported by design in scenarios where PowerShell is being hosted in other applications. Instead, usage of the 'ThreadJob' module is recommended in such scenarios.Source      : System.Management.AutomationHResult     : -2146233067TargetObject          : D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exeCategoryInfo          : NotInstalled: (D:\Program Files (x…coreapp3.1\pwsh.exe:String) [Start-Job], PSNotSupportedExceptionFullyQualifiedErrorId : IPCPwshExecutableNotFound,Microsoft.PowerShell.Commands.StartJobCommandInvocationInfo        :MyCommand        : Start-JobScriptLineNumber : 71OffsetInLine     : 17HistoryId        : 1ScriptName       : D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\Submit-OrderFinalize.ps1Line             : $null = Start-Job {PositionMessage  : At D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\Submit-OrderFinalize.ps1:71 char:17+         $null = Start-Job {+                 ~~~~~~~~~~~PSScriptRoot     : D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\PublicPSCommandPath    : D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\Submit-OrderFinalize.ps1InvocationName   : Start-JobCommandOrigin    : InternalScriptStackTrace      : at Submit-OrderFinalize<Process>, D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\Submit-OrderFinalize.ps1: line 71at New-PACertificate, D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\New-PACertificate.ps1: line 228at <ScriptBlock>, D:\home\site\wwwroot\AddHostNameSSL\run.ps1: line 83Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: The pwsh executable cannot be found at "D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exe".Note that 'Start-Job' is not supported by design in scenarios where PowerShell is being hosted in other applications. Instead, usage of the 'ThreadJob' module is recommended in such scenarios.Exception             :Type        : System.Management.Automation.PSNotSupportedExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : The pwsh executable cannot be found at "D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exe".Note that 'Start-Job' is not supported by design in scenarios where PowerShell is being hosted in other applications. Instead, usage of the 'ThreadJob' module is recommended in such scenarios.HResult : -2146233087CategoryInfo          : NotImplemented: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : NotSupportedTargetSite  :Name          : ThrowTerminatingErrorDeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35MemberType    : MethodModule        : System.Management.Automation.dllStackTrace  :at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Message     : The pwsh executable cannot be found at "D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exe".Note that 'Start-Job' is not supported by design in scenarios where PowerShell is being hosted in other applications. Instead, usage of the 'ThreadJob' module is recommended in such scenarios.Source      : System.Management.AutomationHResult     : -2146233067TargetObject          : D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exeCategoryInfo          : NotInstalled: (D:\Program Files (x…coreapp3.1\pwsh.exe:String) [Start-Job], PSNotSupportedExceptionFullyQualifiedErrorId : IPCPwshExecutableNotFound,Microsoft.PowerShell.Commands.StartJobCommandInvocationInfo        :MyCommand        : Start-JobScriptLineNumber : 71OffsetInLine     : 17HistoryId        : 1ScriptName       : D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\Submit-OrderFinalize.ps1Line             : $null = Start-Job {PositionMessage  : At D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\Submit-OrderFinalize.ps1:71 char:17+         $null = Start-Job {+                 ~~~~~~~~~~~PSScriptRoot     : D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\PublicPSCommandPath    : D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\Submit-OrderFinalize.ps1InvocationName   : Start-JobCommandOrigin    : InternalScriptStackTrace      : at Submit-OrderFinalize<Process>, D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\Submit-OrderFinalize.ps1: line 71at New-PACertificate, D:\Home\site\wwwroot\AddHostNameSSL\Modules\Posh-ACME\4.3.0\Public\New-PACertificate.ps1: line 228at <ScriptBlock>, D:\home\site\wwwroot\AddHostNameSSL\run.ps1: line 83Exception: The pwsh executable cannot be found at "D:\Program Files (x86)\SiteExtensions\Functions\3.0.15406\workers\powershell\7\runtimes\win\lib\netcoreapp3.1\pwsh.exe".Note that 'Start-Job' is not supported by design in scenarios where PowerShell is being hosted in other applications. Instead, usage of the 'ThreadJob' module is recommended in such scenarios.Stack:    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)`

**Comment by rmbolger** [comment]
That error appears to be caused by a limitation with how PowerShell is run within Azure functions. It doesn't support using `Start-Job` which the module calls after a successful order finalization to do a background task. The error message offers an alternative, but it will take me some time to look into it.

However, the error shouldn't be preventing anything from finishing. I think that's just overzealous Azure logging.

I'd still like to fix the module detection in the plugin, but I may pivot and work on this first since you seem to have a good workaround for that issue. I also just noticed another bug revolving around the Start-Job functionality that needs fixing.

**Comment by rmbolger** [comment]
So I just pushed version 4.3.1 to the gallery which contains both the Route53 fix so you don't have to have the AWS modules in PSModulePath and changes how the telemetry ping is done so it no longer relies on `Start-Job`. Can you give it a shot and let me know how it goes?

**Comment by modemgeek** [comment]
Thanks Ryan.  It seems both issues have been fixed

**Comment by rmbolger** [comment]
Excellent!
