### ISSUE TITLE
KeyLength not honored on renewal

### ISSUE THREAD

**Issue by juliansiebert** [rmbolger/Posh-ACME#326]
Hi,
on renewing with "Submit-Renewal" the specified keylength of the previous order is ignored and is set back to default "2048".
This fixed it for me: #325

Best regards
Julian

**Comment by rmbolger** [comment]
Hi @juliansiebert. Great find! I think this has been broken since the 4.0 release. After looking more closely, I think there might be a couple other places in the code that need fixing as well. Give me a bit to run through some edge cases and we'll get this patched up.

**Comment by rmbolger** [comment]
Ok, I think those changes cover the edge cases I sussed out. I'm gonna try and push this out pretty quick as 4.3.2. Thanks again.
