### ISSUE TITLE
PEM Format

### ISSUE THREAD

**Issue by centuryx476** [rmbolger/Posh-ACME#327]
Hello,
About three years ago I asked this question. Basically to output to .pem format.
I forgot that I asked the question until I did a google search. 
https://github.com/rmbolger/Posh-ACME/issues/25

I' am having a little difficulty understanding the powershell commands. 
How can I output for example the .pfx file into a .pem file ?
If I am reading the code correctly, POSH-ACME can do this natively.

Thank You

**Comment by rmbolger** [comment]
Welcome back, @centuryx476. As I mentioned in the previous question, PEM formatted files are already created by default in addition to the PFX files. Every cert related file other than the PFX files are actually PEM formatted. There are 6 total files generated for each certificate.

- `cert.cer` - (PEM) The certificate by itself
- `cert.key` - (PEM) The private key by itself
- `chain.cer` - (PEM) The issuing CA chain provided by the ACME server
- `fullchain.cer` - (PEM) cert.cert combined with chain.cert in a single file
- `cert.pfx` - (PFX) The cert and private key
- `fullchain.pfx` - (PFX) The cert, private key, and chain

You can see the full paths to all of these files after successfully completing a certificate order using the `Get-PACertificate` command. Try this:

```powershell
$cert = Get-PACertificate
$cert | Format-List
$cert.CertFile
```

**Comment by rmbolger** [comment]
I should probably add that if you have an application that doesn't recognize PEM files unless they have a `.pem` extension, you can just make a copy of the files you need and change the extension. Just don't rename the original files within the Posh-ACME config folder because that will break some functionality.

**Comment by centuryx476** [comment]
Thank you @rmbolger . 
I think that is what I need to do, just rename the extension. 
Let me test it on the application that needs the .pem extension. 
I'll update!!!

**Comment by centuryx476** [comment]
OK,
That was it. 
Simply renaming the extension to .PEM and I am all set. 
I feel like an idiot!
Go ahead and close this out

Thanks again

**Comment by rmbolger** [comment]
No worries, it's a surprisingly common misunderstanding. File extensions for certificate related stuff is definitely not standardized and sometimes it seems like every app wants something different.
