### ISSUE TITLE
Error writing challenge record to Route53

### ISSUE THREAD

**Issue by modemgeek** [rmbolger/Posh-ACME#329]
I've run into an issue that I haven't been able to figure out.  This below runs fine if domain is not hosted on Route53.  We have the domain owner setup a challenge alias to a hosted domain on Route53.
`New-PACertificate -Domain "$RootDomain", "$WildCardDomain" -AcceptTOS -Contact $ContactEmail -Plugin Route53 -DNSAlias $ChallengeDomain -PluginArgs $pArgs -PfxPass $CertPass -Force`

However, if the same code runs for a domain that is already hosted on Route53, I get the following error
> [Warning] WARNING: Fewer Plugin values than names in the order. Using Route53 for the rest.
> [Error] ERROR: Authorization invalid for domain.com: No TXT record found at _acme-challenge.domain.com

I've tried removing the DNSAlias parameter altogether, but still get the error.

**Comment by modemgeek** [comment]
> Hey @modemgeek. Challenge alias stuff can be easier to troubleshoot knowing the actual names involved. Can you post the value of `$RootDomain`, `$WildCardDomain`, and `$ChallengeDomain`? Or if you don't want it public, can you email them to me at ryan-oss (at) xyto.cc?
> 
> The warning can be ignored because all of the challenges will be written using the same Route53 plugin. The error is a response from the ACME CA just saying that it couldn't find the record it was looking for. Without knowing the actual domains, it's hard to say whether this is because the CNAME record is broken or the TXT record didn't actually get written to the write place.

Thanks.  I have sent you an email

**Comment by modemgeek** [comment]
Thanks Ryan.  I see what you mean.  However, I am trying to prevent having to write TXT records manually.  For DNS zones that are natively hosted on AWS Route 53, I should not have to use the DNS Alias flag, correct?  By requesting a certificate for the domain and specifying the AWS plugin, should not the plugin write the text record for me for the given hosted zone?

**Comment by rmbolger** [comment]
> For DNS zones that are natively hosted on AWS Route 53, I should not have to use the DNS Alias flag, correct?

Correct

> By requesting a certificate for the domain and specifying the AWS plugin, should not the plugin write the text record for me for the given hosted zone?

Yes, all `-DnsAlias` really does is tell the plugin to write the TXT value to that record instead of the one in `-Domain`. The value of the record is the same.

So without `-DnsAlias`, the plugin will go to Route53 looking for a zone that matches `_acme-challenge.example.com` and add the TXT record there. But with `-DnsAlias`, it will instead go to Route53 looking for a zone that matches `example.yourdomain.com` (no _acme-challenge prefix unless that's what you request) and write the value there instead.

It's the equivalent of saying "Give me a cert for example.com, but write the TXT record at example.yourdomain.com". Where `example.com` is hosted is irrelevant as long as the CNAME already points to `example.yourdomain.com` and is hosted in Route53.

And it sounds like all of that is working. But your client messed up the creation of the CNAME and it's not actually pointing to `example.yourdomain.com`.

Here's another thing you can try to check that things are working like they should.

```powershell
Publish-Challenge $RootDomain (Get-PAAccount) faketoken Route53 $pArgs -DnsAlias $ChallengeDomain -Verbose
```

This is basically the command that gets run for each of the `-Domain` values in your `New-PACertificate` command. For the wildcard name, the "*." is stripped so it's basically `$RootDomain` for both. And "faketoken" is replaced with the real token value for each challenge. After you run this, you should be able to see the record created in your Route53 hosted `$ChallengeDomain`.

**Comment by rmbolger** [comment]
Also, when you do the `Publish-Challenge` test, you should then also be able to do `nslookup -q=txt _acme-challenge.example.com` once the changes have propagated and get the value that you wrote to Route53 in the response.

**Comment by modemgeek** [comment]
`New-PACertificate -Domain "$RootDomain", "$WildCardDomain" -AcceptTOS -Contact $ContactEmail -Plugin Route53 -PluginArgs $pArgs -PfxPass $CertPass -force`

I am trying this without the DnsAlias because like you mentioned this should not be needed. I get the error

> Submit-ChallengeValidation : Authorization invalid for *.citycyclesalesharleydavidson.com: No TXT record found at _acme-challenge.citycyclesalesharleydavidson.com

If I run 
`Publish-Challenge $RootDomain (Get-PAAccount) -Token asdadasd -Plugin Route53 -PluginArgs $pArgs`

I can see the record written to the zone

![image](https://user-images.githubusercontent.com/25929536/111531142-60a48f80-8721-11eb-80bb-31381080164a.png)

Running the nslookup also returns the correct result.

**Comment by rmbolger** [comment]
I can see the test record you published from my end as well. So theoretically, the module should be able to publish the real records too. Can you add `-Verbose` to the `New-PACertificate` command and post the (optionally redacted) output? Also, is the module sleeping for the default 2 min after publishing the records? There should be a progress bar as it counts down. During the countdown, you should also be able to see the records in the Route53 console.

**Comment by modemgeek** [comment]
It seems to write these values.  It find the zone but it's not writing the record as _acme-challenge.example.com 

> examples.com | TXT | "0zj466fCgShS8bdlVmIWl0w7NjW9RyrMwUc3BMnnZKo""cb73f7HzUJHKAfqsdQnFXLQLv4JmqQrxO9r7nR5j32M"

here is the output of verbose

> PS C:\WINDOWS\system32> New-PACertificate -Domain "$RootDomain", "$WildCardDomain" -AcceptTOS -Contact $ContactEmail -Plugin Route53 -PluginArgs $pArgs -PfxPass $CertPass -force -verbose
VERBOSE: Using ACME Server https://acme-v02.api.letsencrypt.org/directory
VERBOSE: Using account 115073344
VERBOSE: Creating a new order for example.com, *.example.com
WARNING: Fewer Plugin values than names in the order. Using Route53 for the rest.
VERBOSE: Publishing challenge for Domain example.com with Token TTGNhP7Ay9OVRCQwOjUezwS9xd_wtKWbdrJafR4JZco using Plugin Route53 and DnsAlias 'example.com'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module AWS.Tools.Common.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\ImportGuard.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.Completers.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.Aliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.dll'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module AWS.Tools.Route53.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.Completers.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.Aliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.dll'.
VERBOSE: Populating RepositorySourceLocation property for module AWSPowerShell.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\ImportGuard.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShellCompleters.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShellLegacyAliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShell.dll'.
VERBOSE: Loading module from path 'C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell\AWSPowerShell.dll'.
VERBOSE: Attempting to find hosted zone for example.com
VERBOSE: Invoking Amazon Route 53 operation 'ListResourceRecordSets' in region 'us-west-2'
VERBOSE: Adding the record to zone ID /hostedzone/Z0014559ROKLZDVPVA0Y
VERBOSE: Invoking Amazon Route 53 operation 'ChangeResourceRecordSets' in region 'us-west-2'
VERBOSE: Publishing challenge for Domain example.com with Token yJjOxKjchfgkBY99xQBNQ_RIM9HRIGPnJMnHwIqxx5o using Plugin Route53 and DnsAlias 'example.com'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module AWS.Tools.Common.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\ImportGuard.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.Completers.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.Aliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.dll'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module AWS.Tools.Route53.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.Completers.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.Aliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.dll'.
VERBOSE: Populating RepositorySourceLocation property for module AWSPowerShell.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\ImportGuard.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShellCompleters.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShellLegacyAliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShell.dll'.
VERBOSE: Loading module from path 'C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell\AWSPowerShell.dll'.
VERBOSE: Attempting to find hosted zone for example.com
VERBOSE: Invoking Amazon Route 53 operation 'ListResourceRecordSets' in region 'us-west-2'
VERBOSE: Adding the record to zone ID /hostedzone/Z0014559ROKLZDVPVA0Y
VERBOSE: Invoking Amazon Route 53 operation 'ChangeResourceRecordSets' in region 'us-west-2'
VERBOSE: Saving changes for Route53 plugin
VERBOSE: Sleeping for 120 seconds while DNS change(s) propagate
VERBOSE: Requesting challenge validations
WARNING: ACME response body was not JSON parseable
VERBOSE: Unpublishing challenge for Domain example.com with Token TTGNhP7Ay9OVRCQwOjUezwS9xd_wtKWbdrJafR4JZco using Plugin Route53 and DnsAlias 'example.com'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module AWS.Tools.Common.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\ImportGuard.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.Completers.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.Aliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.dll'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module AWS.Tools.Route53.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.Completers.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.Aliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.dll'.
VERBOSE: Populating RepositorySourceLocation property for module AWSPowerShell.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\ImportGuard.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShellCompleters.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShellLegacyAliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShell.dll'.
VERBOSE: Loading module from path 'C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell\AWSPowerShell.dll'.
VERBOSE: Attempting to find hosted zone for example.com
VERBOSE: Invoking Amazon Route 53 operation 'ListResourceRecordSets' in region 'us-west-2'
VERBOSE: Removing the record from zone ID /hostedzone/Z0014559ROKLZDVPVA0Y
VERBOSE: Invoking Amazon Route 53 operation 'ChangeResourceRecordSets' in region 'us-west-2'
VERBOSE: Unpublishing challenge for Domain example.com with Token yJjOxKjchfgkBY99xQBNQ_RIM9HRIGPnJMnHwIqxx5o using Plugin Route53 and DnsAlias 'example.com'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module AWS.Tools.Common.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\ImportGuard.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.Completers.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.Aliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.9.0\AWS.Tools.Common.dll'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module AWS.Tools.Route53.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.Completers.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.Aliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Route53\4.1.9.0\AWS.Tools.Route53.dll'.
VERBOSE: Populating RepositorySourceLocation property for module AWSPowerShell.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\ImportGuard.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShellCompleters.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShellLegacyAliases.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AWSPowerShell\4.1.9.0\AWSPowerShell.dll'.
VERBOSE: Loading module from path 'C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell\AWSPowerShell.dll'.
VERBOSE: Attempting to find hosted zone for example.com
VERBOSE: Invoking Amazon Route 53 operation 'ListResourceRecordSets' in region 'us-west-2'
VERBOSE: Removing the record from zone ID /hostedzone/Z0014559ROKLZDVPVA0Y
VERBOSE: Invoking Amazon Route 53 operation 'ChangeResourceRecordSets' in region 'us-west-2'
VERBOSE: Saving changes for Route53 plugin
Submit-ChallengeValidation : The remote server returned an error: (405) Method Not Allowed.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.3.1\Public\New-PACertificate.ps1:216 char:9
+         Submit-ChallengeValidation
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Submit-ChallengeValidation], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (405) Method Not Allowed.,Submit-ChallengeValidation
 
WARNING: ACME response body was not JSON parseable
The remote server returned an error: (405) Method Not Allowed.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.3.1\Private\Invoke-ACME.ps1:153 char:17
+                 throw $ex
+                 ~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (405) Method Not Allowed.
 

PS C:\WINDOWS\system32>

**Comment by rmbolger** [comment]
Man, that AWS.Tools.Route53 module is chatty (I stripped out the module loading stuff from the comment). It looks like Let's Encrypt is/was in the middle of back end maintenance which is likely the cause of the "Method Not Allowed" error stuff at the end (though as I type this it appears to be [over now](https://letsencrypt.status.io/).

However, this is interesting.

> VERBOSE: Publishing challenge for Domain example.com with Token TTGNhP7Ay9OVRCQwOjUezwS9xd_wtKWbdrJafR4JZco using Plugin Route53 and DnsAlias 'example.com'.

When you haven't specified anything in `-DnsAlias`, that message should just have empty quotes at the end like `and DnsAlias ''`. It might be picking up the value from an old copy of the order (which is supposed to be a convenience feature but in this case might be causing problems).

Can you run `Get-PAOrder | Format-List` this and check the value of `DnsAlias` in the output? It should show as `{}`. But if there's something in there run this to clear it out and then check again.

```powershell
Set-PAOrder $RootDomain -DnsAlias @()
```

Alternatively, you can also make sure you're starting from scratch by removing the old order entirely first.

```powershell
Remove-PAOrder $RootDomain
```

**Comment by modemgeek** [comment]
Thanks.  That did it.  I couldn't figure out why it was acting like DnsAlias was still being specified.  Running Get-PAOrder did show it having the DnsAlias.  I ran Remove-PAOrder and it is now gone.  Tried New-PACertificate and see the _acme-challenge.example.com TXT record being written.

Thanks again.

**Comment by rmbolger** [comment]
Hooray! Let me know if you end up trying the DnsAlias stuff again and run into any issues. It's a little weird to wrap your head around at first, but I swear it works great once everything is setup properly.
