### ISSUE TITLE
New-Csr.ps1 detected as malware by Windows Defender

### ISSUE THREAD

**Issue by AcronicaOpica** [rmbolger/Posh-ACME#333]
New-Csr.ps1 was removed but it is still used in Submit-OrderFinalize.ps1 (line 50).

**Comment by rmbolger** [comment]
Hey @AcronicaOpica. Thanks for the report. I'm not sure what's going on yet. But the file isn't actually missing from any of the published packages. It appears that file is getting erroneously flagged as malware by the native Windows Antivirus scanner. So it may have been quarantined on your system.

This is the first I've hard of it happening, but it's definitely happening on my own system as well. That file hasn't been modified in the module since mid-March and it definitely wasn't getting flagged as malicious then. So I'm not sure what changed. It may take some time to find the right channels to deal with this. But in the mean time, you should be able to mark the file as safe from the [Protection History](https://www.windowscentral.com/how-view-malware-history-microsoft-defender-antivirus-windows-10).

**Comment by rmbolger** [comment]
I've submitted the file for false positive analysis to the Microsoft Security Intelligence website. But their online scan shows "No malware detected" using a newer definition version than I have on my machine. So it may have already been fixed. We'll see if they get back to me.

![image](https://user-images.githubusercontent.com/2327255/113525324-0bfa7480-9569-11eb-9884-cf283d9b11c8.png)

**Comment by AcronicaOpica** [comment]
Thank you for the quick reply @rmbolger. You are right, it was removed by Windows Defender. Sorry for my mistake, I also misread "New-Csr.ps1 removed references to Get-OrderFolder that are no longer necessary" note.

It works with "real-time" protection off on my NOT fully-updated Windows Server 2016.
But it works without any problem (with real-time protection on) on my fully-updated Windows 10 desktop and Windows Server 2019. Also all 50 antivirus tests on virscan.org are ok.

**Comment by rmbolger** [comment]
Not a problem. This was definitely a first for me and I'm still glad you reported the issue. The submission I made to Microsoft claims the detection has been removed. But I'm not sure how that translates to virus def updates for the various versions of Windows. I'm gonna leave this open for a bit just in case others run into the problem.

**Comment by sofusskovgaard** [comment]
I'm having a similar issue but my pc detected it as a trojan and i can't take it out of quarantine. And yet the file is still in the correct location in the package.

![image](https://user-images.githubusercontent.com/24526844/114000600-71957c00-985b-11eb-9592-28a48aab66db.png)

I can also confirm that virscan.org ok's all 50 scans, i also did a virustotal to be sure.

https://www.virustotal.com/gui/file/74ad7b6700e15257097c7e3a8f50e10e8147b6fe877410f34a92418710196d47/detection

![image](https://user-images.githubusercontent.com/24526844/114001665-6e4ec000-985c-11eb-853f-6074bb251477.png)

**Comment by rmbolger** [comment]
Yeah, that `Trojan:PowerShell/Mountsi.A!ml` is also what it was detected as on my machine. "Threat Removed or Restored" is what my machine shows after I restored it from quarantine.

**Comment by sofusskovgaard** [comment]
@rmbolger is there anything new on this? Has your submission been looked at yet?

**Comment by rmbolger** [comment]
Yes, it was confirmed to be an incorrect detection. Here are the comments from the analyst on the case:

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by sofusskovgaard** [comment]
> Yes, it was confirmed to be an incorrect detection. Here are the comments from the analyst on the case:
> 
> > We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> > 
> > 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> > 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> > 3. Run "MpCmdRun.exe -SignatureUpdate"
> > 
> > Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Amazing, this worked for me.
