### ISSUE TITLE
Submit Renewal Using Posh-Acme

### ISSUE THREAD

**Issue by getsolomon** [rmbolger/Posh-ACME#339]
Hi Team,

Can you please detail steps needed for *.example.com. I have dnsTXT record saved in DNS as "asdfasdfasdf". 
Can I do it just by command line or any coding required??

How can I Submit renewals using the above information. If not, can you detail out steps for the Renewal of particular DNS

Thanks

**Comment by rmbolger** [comment]
Hi @getsolomon. Have a look at the tutorial I've linked below. I wrote it to walk beginners through the process step by step.

https://github.com/rmbolger/Posh-ACME/blob/main/Tutorial.md

**Comment by getsolomon** [comment]
Thanks Ryan. Gone through the tutorial.

Can you please let me know how the new TXT records are replaced in the Customer domains when submitted renewals.

**Comment by rmbolger** [comment]
The DNS plugin and parameters that were used in the original order are re-used by the `Submit-Renewal` command. If you didn't use a plugin in the original order and modified the records by hand, you'll have to do the same thing for a renewal.
