### ISSUE TITLE
Digital Ocean DNS:  _acme-challenge.mywebsite.com  TXT records safe to delete?

### ISSUE THREAD

**Issue by mkanet** [rmbolger/Posh-ACME#342]
Hi,

You had kindly helped me set up DNS on DigitalOcean (DDNS for my domain updated by my Asus router).  You also helped me to create my SSL cert for my domain using Posh-ACME + the DigitalOcean plugin.

Anyway, I just jumped on my DigitalOcean account for DNS.  I noticed 4 ** _acme-challenge.mywebsite.com**  **TXT** records.

I can't remember when/why/how I created these 4 TXT records.  **Are they safe to delete?**  I'm completely drawing a blank.

Thank you for your time!

**Comment by rmbolger** [comment]
Yes, totally safe. They only need to exist long enough to be validated by Let's Encrypt. Normally the plugin should be deleting them automatically.
