### ISSUE TITLE
How can i create a wildcard certificate using azure plugin.

### ISSUE THREAD

**Issue by Gaku-Yamaguchi** [rmbolger/Posh-ACME#354]
I checked your tutorial (https://github.com/rmbolger/Posh-ACME/blob/main/Tutorial.md#dns-plugins) and "How to use Azure Plugin" (https://github.com/rmbolger/Posh-ACME/blob/main/Posh-ACME/Plugins/Azure-Readme.md)

I read Azure-Readme.md(https://github.com/rmbolger/Posh-ACME/blob/main/Posh-ACME/Plugins/Azure-Readme.md) and followed this md file step by step.

but I always failed the last command. I mean New-PACertificate.

steps i executed are below.
1, Set-PAServer LE_STAGE
2, Connect-AzAccount as Tenant Admin.
3, New-AzADServicePrincipal for create service principal.
4, New-AzRoleAssignment  assign a custom role for editing dns records to the service principal i created.
5, New-PACertificate *.[mydomain.]net -AcceptTOS -Plugin Azure -PluginArgs @{AZSubscriptionId=$subscriptionId;AZTenantId=$tenantId;AZAppUsername=$appUser;AZAppPasswordInsecure=$appPass}

i recieved a message below.
```
Submit-ChallengeValidation : Authorization invalid for *.example.net: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.example.net - check that a DNS record exists for this domain
発生場所 C:\Users\myuser\Documents\WindowsPowerShell\Modules\Posh-ACME\4.4.0\Public\New-PACertificate.ps1:218 文字:9
+         Submit-ChallengeValidation
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Authorization i...for this domain:String) [Submit-ChallengeValidation], RuntimeException
    + FullyQualifiedErrorId : Authorization invalid for *.[mydomain].net: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.example.net - check that a DNS record exists for this domain,Submit-ChallengeValidation
```
 
I already have _acmechallenge records on my dns zone in azure.
![image](https://user-images.githubusercontent.com/84550686/120290310-2f3d6800-c2fd-11eb-925e-3525e3319d07.png)

Why did New-PACertificate command failed? and Is my steps right?

**Comment by rmbolger** [comment]
Hi @Gaku-Yamaguchi. Your steps looks correct. Were there any error messages during the `New-PACertificate` command other than the last one about NXDOMAIN?

The "NXDOMAIN" error indicates that the Let's Encrypt servers didn't find any TXT records for the challenge it they were looking for. This can either mean the TXT records weren't created successfully or the Azure DNS servers hadn't fully propagated the change to all of their nameservers by the time the 2 minute sleep timer was done.

Also, are you sure your domain's DNS is publicly accessible? You accidentally forgot to redact the domain in the error message (I fixed it for you). But when I try to look up the NS records for the domain, I don't get any answers. If you substitute your domain for `example.net` on this [web based DNS query tool](https://www.digwebinterface.com/?hostnames=example.net&type=NS&ns=resolver&useresolver=8.8.4.4&nameservers=) and click the Dig button, a public Azure DNS hosted zone would usually respond with four NS records such as such as `ns2-01.azure-dns.net`. But your domain responds with zero as if the .net TLD doesn't know about your domain. Is it an internal-only domain by any chance?

**Comment by rmbolger** [comment]
Thanks for the follow up. Let me know if you have more problems after sorting out the AppService problem.

I'm not positive, but I don't think you can create arbitrary DNS records in your xxxxx.onmicrosoft.com zone. That's controlled automatically by Office 365. So you wouldn't be able to create a wildcard cert for it unless Microsoft offers some native way to request one.

**Comment by Gaku-Yamaguchi** [comment]
after I solved AppService problem with Microsoft Support, I tried creating wildcard cert again for domain I created (custom domain).
so, it's worked. I successfully created wildcard certificate.

Thank you for your support!
