### ISSUE TITLE
Call to "New-PACertificate" fails because of empty payload calling update account

### ISSUE THREAD

**Issue by janlii** [rmbolger/Posh-ACME#357]
If have my own implementation of a ACME server where the update account requires a payload.

DEBUG: Refreshing account 11
DEBUG: ACME Header: 
{
    "kid":  "https://localhost:44398/acct/11",
    "alg":  "ES256",
    "nonce":  "Dead8PdccwYvgIkVmhLzhhdxgsY",
    "url":  "https://localhost:44398/acct/11"
}
DEBUG: ACME Payload: (empty)
DEBUG: Signing message using EC with SHA256
DEBUG: POST https://localhost:44398/acct/11

**Comment by rmbolger** [comment]
Hi @janlii, thanks for posting. I think your ACME server implementation might have a bug if it requires a non-empty payload. The internal Update-PAAccount method is using a POST-AS-GET request as described in [RFC8555 section 6.3](https://datatracker.ietf.org/doc/html/rfc8555#section-6.3).

> If a client wishes to fetch a resource from the server (which would otherwise be done with a GET), then it MUST send a POST request with a JWS body as described above, where the payload of the JWS is a zero-length octet string.  In other words, the "payload" field of the JWS object MUST be present and set to the empty string ("").

**Comment by janlii** [comment]
Hi!
Thank you for the answer and sorry for the late reply. I've been on vacation for a while.

I'll have a look at the code I'm using (<https://github.com/PeculiarVentures/acme-cs>).


Have a nice day!

Best regards,Jan Liikamaa



18 juni 2021 17:37:52 +02:00, skrev Ryan Bolger ***@***.***>:
