### ISSUE TITLE
Support for Hosting.de

### ISSUE THREAD

**Issue by FabianNiehaus** [rmbolger/Posh-ACME#358]
Support for handling DNS challenges for [hosting.de](https://hosting.de) via its API would be greatly appreciated.

The API reference can be found at [https://www.hosting.de/api/#the-zoneconfig-object](https://www.hosting.de/api/#the-zoneconfig-object).

The go-acme/lego project already has support for hosting.de: [https://go-acme.github.io/lego/dns/hostingde/](https://go-acme.github.io/lego/dns/hostingde/)

Thank you very much.

**Comment by rmbolger** [comment]
Hi @FabianNiehaus, thanks for the request. I'll take a look and see what I can do.

**Comment by rmbolger** [comment]
Hey @FabianNiehaus. I've added a draft version of the plugin called `HostingDe`. It seems to be working for me. But I'd love it if you could give it a test as well before it goes out in an official release.

**Comment by FabianNiehaus** [comment]
Thank's for the quick work! I will try it and report the results 👍

**Comment by rmbolger** [comment]
Now live with 4.6.0
