### ISSUE TITLE
Support plugin for beget.com

### ISSUE THREAD

**Issue by L719dhh** [rmbolger/Posh-ACME#359]
**Support for handling DNS challenges for [beget.com](https://beget.com/en) via its API would be greatly appreciated.**

The API reference can be found at [DNS administration functions](https://beget.com/en/kb/api/dns-administration-functions)
Thank you very much.

**Comment by rmbolger** [comment]
Hi @L719dhh , thanks for the request. I'll take a look after I finish the other plugin request that came in before yours.

**Comment by rmbolger** [comment]
Hey @L719dhh, sorry for the wait. I've been having trouble ordering a new domain from them. For some reason, they're unable to charge my credit card and I'm waiting on support to figure out what's wrong.

**Comment by L719dhh** [comment]
Hi. I can buy a test domain for you, or pay for yours, if it is convenient for you

**Comment by rmbolger** [comment]
If you want to create a second account or share the credentials for your existing account (randomize the password first), that could work. My email is ryan-oss at xyto.cc.

Using the Github sponsors feature to send me a one-time payment would also normally work except part of the problem right now is that I can't get beget to accept my money.

**Comment by L719dhh** [comment]
By the way, if you have created an account, you do not have to pay for it (30 days free period), also, a domain for tests _"yourlogin.beget.tech"_ is automatically created.

If it doesn't work, I will send the login and password to access the test account.

**Comment by rmbolger** [comment]
I tried, but the registration page wants credit card data even for the free trial (presumably so they can start billing you once the trial is done). But the card data form doesn't like any of the card details I've given it.

**Comment by L719dhh** [comment]
Very strange with registration. 
I sent an email with access to ryan-oss @ xyto.cc

**Comment by rmbolger** [comment]
Got the credentials and I've started working on the plugin. There's some weirdness in their API and how they distinguish between sub-zones and sub-domains.

For example, if I'm trying to create a TXT record for `sub.poshacme.beget.tech`, I can successfully do that with the `dns/changeRecords` method and the record gets returned by the default nameservers. The record also shows up as a "subzone" in the DNS records management UI. However, when I make a `dns/getData` call for the same FQDN, I get an error saying "Failed to get DNS records".

If I had first created a sub-domain for the same name from the "Domains and subdomains" page, then the `dns/getData` call works. But it also creates a bunch of additional default records that we don't need or want. The UI also won't let me create a sub-domain for `_acme-challenge.poshacme.beget.tech` which is critical for ACME challenge records.

So I'm sort of stuck doing a blind add for the TXT records if the initial `dns/getData` call fails. It should be fine most of the time because `_acme-challenge` prefixed records aren't really used outside of ACME validation. But it could be bad if you try to use DNS challenge aliases against a sub-zone that has other records because the `dns/changeRecords` call would wipe out those other records since the call is basically overwriting all records for that FQDN.

It's the least bad option though, so that's probably what I'll end up doing.

**Comment by rmbolger** [comment]
Ok, I've got an initial version of the plugin committed to the main branch. Give it a try and let me know how it goes.

**Comment by L719dhh** [comment]
###  This work fine 👍 🥇 

```powershell
$cred = Get-Credential -Message "Beget Credentials"
$pArgs = @{BegetCredential = $cred}
New-PACertificate 'vv.testdomain.com','aa.testdomain.com' -AcceptTOS ` -Contact 'admin@testdomain.com' -Plugin Beget -PluginArgs $pArgs -Verbose

```
<details>
<summary>Out Powershell </summary>

  ```PowerShell

Using ACME Server https://acme-v02.api.letsencrypt.org/directory                                                                                                                                                      
Using account 1301*****                                                                                                                                                                                               
Creating a new order for vv.testdomain.com, aa.testdomain.com
WARNING: Fewer Plugin values than names in the order. Using Beget for the rest.
Publishing challenge for Domain vv.testdomain.com with Token pzJrRharlZzNPEPz8CVv7RKq0qRzzOV9-EXXCVBAMB0 using Plugin Beget and DnsAlias ''.
No existing records found for _acme-challenge.vv.testdomain.com. This is expected for sub-zones that don't have a corresponding sub-domain.
Adding _acme-challenge.vv.testdomain.com with value yapfe8kQ1MNWoLlE8QRcbmJdyEyq9tDTMV8GqwLBDEo.
Publishing challenge for Domain aa.testdomain.com with Token NHQSLYQlhJW54QmaY2DwYDbDb03HizNAHvXD37PPsEU using Plugin Beget and DnsAlias ''.
No existing records found for _acme-challenge.aa.testdomain.com. This is expected for sub-zones that don't have a corresponding sub-domain.
Adding _acme-challenge.aa.testdomain.com with value TsV5I9xp6-GFX22vNIsmSz95QQpd7sEomy9_MmxojwM.
Saving changes for Beget plugin
Committing changes for _acme-challenge.aa.testdomain.com
Committing changes for _acme-challenge.vv.testdomain.com
Sleeping for 120 seconds while DNS change(s) propagate
Requesting challenge validations
Nonce rejected by ACME server. Retrying with updated nonce.
Unpublishing challenge for Domain vv.testdomain.com with Token pzJrRharlZzNPEPz8CVv7RKq0qRzzOV9-EXXCVBAMB0 using Plugin Beget and DnsAlias ''.
No existing records found for _acme-challenge.vv.testdomain.comtestdomain.com. This is expected for sub-zones that don't have a corresponding sub-domain.
Deleting all TXT records for _acme-challenge.vv.testdomain.com
Unpublishing challenge for Domain aa.testdomain.com with Token NHQSLYQlhJW54QmaY2DwYDbDb03HizNAHvXD37PPsEU using Plugin Beget and DnsAlias ''.
No existing records found for _acme-challenge.aa.testdomain.com. This is expected for sub-zones that don't have a corresponding sub-domain.
Deleting all TXT records for _acme-challenge.aa.testdomain.com
Saving changes for Beget plugin
Committing changes for _acme-challenge.aa.testdomain.com
Committing changes for _acme-challenge.vv.testdomain.com
Finalizing the order.
Creating new certificate request with key length 2048.
Creating new private key for the certificate request.
Downloading signed certificate
Updating cert expiration and renewal window
Successfully created certificate.

Subject        	 	 NotAfter            KeyLength Thumbprint                               AllSANs
-------          	--------            --------- ----------                               -------
CN=vv.testdomain.com 13.10.2021 19:37:47 2048      A068422DDD0AC1E2E0B***********1EFFD7 {vv.testdomain.com, aa.testdomain.com}
  ```
</details>
<hr></hr>


#[Add comment file](https://github.com/rmbolger/Posh-ACME/commit/c7e75ea8b045323016b20dd03dff075e8f820600?branch=c7e75ea8b045323016b20dd03dff075e8f820600&diff=unified#r53545282) _Posh-ACME/Plugins/Beget-Readme.md_

**Comment by rmbolger** [comment]
I pushed a change to the readme that talks about the API specific password and permissions limitation. Thanks for the tip.

**Comment by rmbolger** [comment]
Now live with 4.6.0
