### ISSUE TITLE
Revoking a certificate does not require an account

### ISSUE THREAD

**Issue by Mika56** [rmbolger/Posh-ACME#361]
Hi,
Revoking a certificate does not always require an account. If you have the certificate's private key, you can revoke using: 
```ps
Revoke-PACertificate -CertFile .\pathtocert.pem -KeyFile .\pathtokey.key
```

However, the `Begin` section of Revoke-PACertificate first makes sure that we have an account (using Get-PAAccount).
To workaround, you have to create an account (New-PAAccount) that will not be related to the certificate you're about to revoke, yet it still revokes without any issue.

**Comment by rmbolger** [comment]
Thanks, @Mika56. You're totally right. I can't get rid of the account check entirely, because the function does try and fall back on it if the specified private key couldn't be imported. But I can definitely change up the logic so it's not always required.

**Comment by rmbolger** [comment]
Ok, a fix is now in main. Give that a test if you'd like.

**Comment by rmbolger** [comment]
Now live with 4.6.0
