### ISSUE TITLE
DNS Plugin Request

### ISSUE THREAD

**Issue by ebduncanutmck** [rmbolger/Posh-ACME#362]
Network Solutions
networksolutions.com

**Comment by rmbolger** [comment]
Hi @ebduncanutmck. Thanks for what I assume is a plugin request. I'm having a bit of trouble finding any documentation about a DNS API for Network Solutions though. Do you have any links? I've seen a couple references to an E-commerce API and a partner portal, but nothing that implies it can be used to manipulate DNS records.

**Comment by rmbolger** [comment]
Another thing to keep in mind is that you don't have to host your domain's DNS with the same company that you registered the domain with. You can move just the DNS to a DNS provider that already has a plugin and leave the domain registration with Network Solutions.

**Comment by ebduncanutmck** [comment]
Thank you for the reply! I checked with Network Solutions support and they do not offer API access. I guess I will look to move DNS. Thanks again!

**Comment by rmbolger** [comment]
Happy to help. The most popular free option is probably [Cloudflare](https://www.cloudflare.com/dns/). Another personal favorite of mine that is also free is [Digital Ocean](https://www.digitalocean.com/).
