### ISSUE TITLE
Host Europe DNS support

### ISSUE THREAD

**Issue by Tragen** [rmbolger/Posh-ACME#366]
Is it possible to get Host Europe DNS support?
https://www.hosteurope.de/

They manage the DNS settings over
https://kis.hosteurope.de/
and I think they don't have an API

There is this shell script
https://gist.github.com/Aikhjarto/11006704
to modify DNS settings. I don't know if this is enough or how I could help you.

**Comment by Tragen** [comment]
We have the hosting with Hetzner, but the domain was registered with HE a long time ago because Hetzner didn't allow .ag domains at that time. We think we will move the domain to Hetzner, there you have a working plugin.

**Comment by rmbolger** [comment]
That is a perfectly reasonable plan as well. Let me know if you have any trouble with the Hetzner plugin.
