### ISSUE TITLE
Azure DNS Plugin Presents a Content-Length error on Linux/PowerShell Core

### ISSUE THREAD

**Issue by shawnparslow** [rmbolger/Posh-ACME#371]
I was able to obtain an SSL certificate with no issue running manually (where I added the txt record) but when I try using the Azure plugin I am getting the following error.  FWIW - I have the same code working on Windows with PS7 but am trying to setup a linux instance running powershell 7.

I am using the latest Posh-SSH and Az modules.

```
PS /etc/devops-scripts> New-PACertificate $TargetDomainName -DnsPlugin Azure -PluginArgs $azParams -AcceptTOS -Contact $EmailContact
Submit-ChallengeValidation: /root/.local/share/powershell/Modules/Posh-ACME/4.6.0/Public/New-PACertificate.ps1:218
Line |
 218 |          Submit-ChallengeValidation
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  Length Required  Length Required HTTP Error 411. The request must be chunked or have a content length.
```

**Comment by rmbolger** [comment]
Thanks for the report, @shawnparslow. I'll see if I can repro this on my end and figure out what's going on. My guess is that there's some sort of small implementation difference in how the .NET Core web libraries function on Linux. Seems weird that it would only affect connections to Azure though.

**Comment by shawnparslow** [comment]
@rmbolger - Sounds good, I am still testing/investigating also so I will update if I find anything more or a resolution.  Thanks!

**Comment by rmbolger** [comment]
Testing from an Ubuntu 18.04 box running PowerShell 7.1.3 against the Let's Encrypt staging server, everything seems to work for me so far. Not sure if it matters, but this VM is also external to Azure and using the default plugin parameter set that takes a Subscription ID, Tentant ID, and App Cred.

Let's see if we can narrow this down to Azure specifically or something tied to Let's Encrypt (I'm assuming that's the CA you're using). Try running this and if it fails, post the (optionally sanitized) output here.

```powershell
$DebugPreference = 'Continue'
Publish-Challenge $TargetDomainName (Get-PAAccount) faketoken Azure $azParams -Verbose
Unpublish-Challenge $TargetDomainName (Get-PAAccount) faketoken Azure $azParams -Verbose
```

**Comment by shawnparslow** [comment]
Thanks, I ran the publish and unpublish.

Publish:
```
PS /etc/devops-scripts> Publish-Challenge $TargetDomainName (Get-PAAccount) faketoken Azure $azParams -Verbose
VERBOSE: Publishing challenge for Domain test-reports.mydomain.com with Token faketoken using Plugin Azure and DnsAlias ''.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling Azure plugin to add _acme-challenge.test-reports.mydomain.com TXT with value 4rylu2jqUsbdMPLx5pmyL-wU5GRl2bHyo3_Drh17_bM
DEBUG: Current Token Expires: 08/18/2021 21:33:05 +00:00
VERBOSE: Authenticating with provided access token
DEBUG: Retrieved token expiration: 1629329261
VERBOSE: Attempting to find hosted zone for _acme-challenge.test-reports.mydomain.com
VERBOSE: Querying _acme-challenge.test-reports.mydomain.com
VERBOSE: GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxx/resourceGroups/myresourcegroup-rg/providers/Microsoft.Network/dnszones/mydomain.com/TXT/_acme-challenge.test-reports?api-version=2018-03-01-preview with 0-byte payload
VERBOSE: received 472-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Sending updated _acme-challenge.test-reports
DEBUG: {"properties":{"TXTRecords":[{"value":["jCYUuNgfo3_Qkia6ZeDeyBr3mqhO777M1g-2wHfaTVE"]},{"value":["4rylu2jqUsbdMPLx5pmyL-wU5GRl2bHyo3_Drh17_bM"]}],"TTL":10}}
VERBOSE: PUT https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxx/resourceGroups/myresourcegroup-rg/providers/Microsoft.Network/dnszones/mydomain.com/TXT/_acme-challenge.test-reports?api-version=2018-03-01-preview with 156-byte payload
VERBOSE: received 344-byte response of content type text/html
Invoke-RestMethod: /root/.local/share/powershell/Modules/Posh-ACME/4.6.0/Plugins/Azure.ps1:71
Line |
  71 |  … $response = Invoke-RestMethod "$($script:AZEnvironment.ResourceManage …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  Length Required  Length Required HTTP Error 411. The request must be chunked or have a content length.
```

Unpublish:
```
PS /etc/devops-scripts> Unpublish-Challenge $TargetDomainName (Get-PAAccount) faketoken Azure $azParams -Verbose
VERBOSE: Unpublishing challenge for Domain test-reports.mydomain.com with Token faketoken using Plugin Azure and DnsAlias ''.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling Azure plugin to remove _acme-challenge.test-reports.mydomain.com TXT with value 4rylu2jqUsbdMPLx5pmyL-wU5GRl2bHyo3_Drh17_bM
DEBUG: Current Token Expires: 08/18/2021 23:22:41 +00:00
DEBUG: Existing token has not expired.
VERBOSE: Attempting to find hosted zone for _acme-challenge.test-reports.mydomain.com
VERBOSE: Querying _acme-challenge.test-reports.mydomain.com
VERBOSE: GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxx/resourceGroups/myresourcegroup-rg/providers/Microsoft.Network/dnszones/mydomain.com/TXT/_acme-challenge.test-reports?api-version=2018-03-01-preview with 0-byte payload
VERBOSE: received 472-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Record _acme-challenge.test-reports doesn't contain 4rylu2jqUsbdMPLx5pmyL-wU5GRl2bHyo3_Drh17_bM. Nothing to do.
```

**Comment by rmbolger** [comment]
Nice, that at least narrows it down to Azure and the specific call it doesn't like. Let me know what else you find. I'll also do some more digging and see if I can find any additional info on that error in conjunction with Azure.

**Comment by rmbolger** [comment]
Had a thought about another test you can run against httpbin.org to see what headers are being sent from the problem system:

```powershell
$irmParams = @{
    Uri = 'https://httpbin.org/anything'
    Method = 'Put'
    Body = @{properties=@{TTL=10;TXTRecords='fakeval'}} | ConvertTo-Json -Compress
    Headers = @{Authorization = "Bearer fake"}
    ContentType = 'application/json'
    UseBasicParsing = $true
}
Invoke-RestMethod @irmParams | Select -Expand headers
```

Azure seems to be saying that the `Content-Length` header is not being sent (which PowerShell is supposed to calculate and send automatically). So I'm curious if the response you get from httpbin.org will say it's being sent or not. On my Ubuntu box, I get output like this:

```
Content-Length  : 48
Content-Type    : application/json
Host            : httpbin.org
User-Agent      : Mozilla/5.0 (Linux; Linux 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021; ) PowerShell/7.1.3
X-Amzn-Trace-Id : Root=1-611d9205-54af82c93d41e06a573818d6
```

**Comment by shawnparslow** [comment]
Running that, I also get the Content-Length header:

```
PS /etc> Invoke-RestMethod @irmParams | Select -Expand headers

Authorization   : Bearer fake
Content-Length  : 48
Content-Type    : application/json
Host            : httpbin.org
User-Agent      : Mozilla/5.0 (Linux; Linux 3.10.0-1062.51.1.el7.x86_64 #1 SMP Wed Jun 9 21:19:24 UTC 2021; en-US) PowerShell/7.1.4
X-Amzn-Trace-Id : Root=1-611d97f7-18d6105e5d1649305337e12a
```

**Comment by rmbolger** [comment]
Well darn, hoped I was on to something there.

**Comment by webprofusion-chrisc** [comment]
It's not likely to be relevant but Posh-ACME is using a preview API version and probably should switch up to the release 
`2018-05-01`

@shawnparslow is there absolutely nothing proxy-like between your server and the internet? i.e. there is nothing else could drop the content-length header? I've actually seen this in something completely different (.net based) where someone calling a webhook in Team got no content length header, even though it was supplied in the original request.

**Comment by rmbolger** [comment]
Thanks Chris. Totally forgot about that. I think the preview version was the only one available when I first wrote the plugin.

**Comment by webprofusion-chrisc** [comment]
You could maybe explicitly set the `TransferEncoding` so it doesn't try to guess anything, also googling suggests that sometimes the default header validation can strip stuff, so `-SkipHeaderValidation` might help? The underlying .net stuff could just be performing buggy validation.

**Comment by shawnparslow** [comment]
@webprofusion-chrisc - I do not think this machine is getting any proxy but it is on a corprate network so this could be an issue (though my local dev windows laptop and windows VM I have been running Posh-ACME on for over a year is also on the same network and has not had this issue).  I think the httpbin.org test above shows the Content-Length is not being stripped.  The only variables that I can see to what I am doing is that my working Windows VM is not on the latest Az (Or Posh-ACME) module and its Windows, the Red Hat linux VM I have the absolute latest of everything and its not windows.  I also have a Mac here local I am going to set everything up with the latest and see if the same thing happens.

**Comment by webprofusion-chrisc** [comment]
@shawnparslow do you have access to WSL? You might be able to get a redhat image for that - it's great for just trying out linux stuff without leaving windows.

**Comment by rmbolger** [comment]
> not on the latest Az

Just to clarify, the plugin doesn't depend on any external modules like Az. It's doing all raw REST stuff.

**Comment by shawnparslow** [comment]
@webprofusion-chrisc - cool, will have to check it out.  This particular Red Hat VM was deployed in Azure for production use.

@rmbolger -  Ok, well one other variable between my working system (running old modules) and the new VM with the latest I can see that does use Az is the method for getting the token passed to the Azure params - Az made a change in the last 6-9 months that nulls the tokencache from context (something about ADAL > MSAL) and added a cmdlet to directly Get-AzAccessToken which I pass in to the AzParams.  I don't think this has anything to do with the issue I am seeing but figure I would note.

Old Az way to get token:
```
$context = Get-AzContext
$cache = $context.tokencache
$cacheItem = $cache.ReadItems() | Where-Object { $_.Resource -eq $AUTH_RESOURCE } | Select-Object -First 1
$AzToken = $cacheItem.AccessToken
$azParams = @{AZSubscriptionId=$subscriptionId;AZAccessToken=$AzToken;}
```

New Az way to get token:
```
$AccessToken = Get-AzAccessToken
$AzToken = $AccessToken.Token | Out-String
$azParams = @{AZSubscriptionId=$SubscriptionId;AZAccessToken=$AzToken;}
 ```

**Comment by shawnparslow** [comment]
Oh, I think that is ht issue - piping the token to  $AccessToken.Token | Out-String

I have stripped the `| Out-String` part off and I think everything is working now.

**Comment by rmbolger** [comment]
Ok weird. I was gonna say the token stuff shouldn't matter because the call that's failing happens after at least one successful authenticated GET where it checks if the record already exists.

**Comment by shawnparslow** [comment]
Yeah - this was all a code issue on my end.  For whatever reason I thought I was seeing weird stuff from the Get-AzAccessToken .Token and sent it to | Out-String before putting in params and that was causing the eventual `Length Required HTTP Error 411.` it seems.  Once I remove that the plugin is working as expected.  Sorry for any confusion there.

**Comment by rmbolger** [comment]
Not a problem at all. Glad we helped get it sorted.

**Comment by shawnparslow** [comment]
Thanks again for the help and quick response - this is an excellent project I hope to contribute back to in the future!
