### ISSUE TITLE
[RFC2136] Renewal stopped working

### ISSUE THREAD

**Issue by loxK** [rmbolger/Posh-ACME#374]
Hello,

Following the issue here https://github.com/rmbolger/Posh-ACME/issues/307, things have been working properly, with the certificate renewing properly every three months using a windows scheduled task.

But now it doesn't work anymore:
```powershell
PS C:\Users\Administrateur\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Windows PowerShell> C:\Users\Administrateur\Documents\WindowsPowerShell\Scripts\Renew.ps1
COMMENTAIRES : Renewing certificate for order winserver.office.domain.com
COMMENTAIRES : Using ACME Server https://acme-staging-v02.api.letsencrypt.org/directory
COMMENTAIRES : Using account 17529942
COMMENTAIRES : Using existing order for winserver.office.domain.com with status pending
COMMENTAIRES : Updating plugin args for plugin(s) RFC2136
COMMENTAIRES : Setting DnsAlias to 
COMMENTAIRES : Setting AlwaysNewKey to False
COMMENTAIRES : Setting UseSerialValidation to False
COMMENTAIRES : Saving order changes
COMMENTAIRES : Publishing challenge for Domain winserver.office.domain.com with Token 8Y5wmZt3MvZG7pRe1pyXBEni3ySzuQmQeb60yLV_qDM using Plugin RFC2136 and DnsAlias ''.
COMMENTAIRES : Adding _acme-challenge.winserver.office.domain.com with value yGglsQaeGU-PnxMWYK-3N-sbBxPTV_yZ6NrZTrCvY4U
COMMENTAIRES : nsupdate output:
; TSIG error with server: expected a TSIG or SIG(0)
update failed: NOTIMP
Answer:
;; ->>HEADER<<- opcode: UPDATE, status: NOTIMP, id:  31140
;; flags: qr ra; ZONE: 0, PREREQ: 0, UPDATE: 0, ADDITIONAL: 0
Submit-ChallengeValidation : nsupdate returned non-zero exit code which indicates failure. Check -Verbose output for details.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.6.0\Public\New-PACertificate.ps1:218 : 9
+         Submit-ChallengeValidation
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (nsupdate return...ut for details.:String) [Submit-ChallengeValidation], RuntimeException
    + FullyQualifiedErrorId : nsupdate returned non-zero exit code which indicates failure. Check -Verbose output for details.,Submit-ChallengeValidation
```

The script used:

```powershell
Import-Module -Name Posh-ACME -Force
Import-Module -Name Posh-ACME.Deploy -Force

Set-PAOrder winserver.office.domain.com
if ($cert = Submit-Renewal -Verbose) {
    $cert | Set-IISCertificate -SiteName 'Default Web Site' -RemoveOldCert
    $cert | Set-RDGWCertificate -RemoveOldCert
    $cert | Set-RDSHCertificate -RemoveOldCert
}
```

I then updated Posh-ACME and nsupdate (I changed its path in domain's pluginargs.json), same issue.

I manually tried nsupdate, and it works:

```cmd
C:\Users\Administrateur>"C:\Program Files\BIND9.16.20.x64\nsupdate.exe"  -v -y hmac-sha512:domain.com:[redacted: TSIG key]
> server [redacted: IP]
> zone domain.com
> update add _acme-challenge.winserver.office.domain.com 86400 TXT "test"
> send
> quit

C:\Users\Administrateur>nslookup -type=txt  _acme-challenge.winserver.office.domain.com [redacted: IP]
_acme-challenge.winserver.office.domain.com        text =

        "test"
```

Finally, I tried issuing a fresh certificate using the same script I used months ago, I get the same error `TSIG error with server: expected a TSIG or SIG(0)`.

**Comment by loxK** [comment]
I ran in Debug mode and tried what Posh-ACME is sending to nsupdate:

```
server [redacted server IP] 53
zone domain.com.
key HMAC-SHA512:domain.com ************
update add _acme-challenge.winserver.office.domain.com. 60 TXT "************"
send
``` 

And I get the error:

```
; TSIG error with server: expected a TSIG or SIG(0)
update failed: NOTIMP
```

If I launch nsupdate this way `nsupdate.exe  -v -y hmac-sha512:domain.com:************` and send the following, it works:

```
server [redacted server IP] 53
zone domain.com.
update add _acme-challenge.winserver.office.domain.com. 60 TXT "************"
send
``` 

I have no idea why and how it happened, since I haven't updated nsupdate nor Posh-ACME prior to the renewing failed.

**Comment by rmbolger** [comment]
Thanks for posting, @loxK. That's really weird. I have no idea why specifying the key on the command line would affect how it gets sent to the server, but that does seem to be the case from your tests.

I'll probably end up doing a packet capture in my test environment to see what (if any) differences end up on the wire. It may be a few days before I can mess with it though.

As a total stab in the dark until I can mess with this myself, can you try the first test again, but slightly change the order of commands so the `key` line comes immediately after the `server` line?

```
server [redacted server IP] 53
key HMAC-SHA512:domain.com ************
zone domain.com.
update add _acme-challenge.winserver.office.domain.com. 60 TXT "************"
send
```

**Comment by rmbolger** [comment]
Found some time this afternoon to test and downloaded the latest BIND 9.16.20 to test with.

As far as I can tell, there is no difference in the packets on the wire between sending the key in the input data versus a command line argument. The position of the `key` line in the input data also doesn't seem to matter whether it's before or after the `zone` line.

> If I launch nsupdate this way nsupdate.exe -v -y hmac-sha512:domain.com:************ and send the following, it works:

The one thing I notice about this command is that the `-v` option forces it to use TCP instead of UDP. Does it still work if you exclude the `-v` and let it use UDP?

**Comment by loxK** [comment]
Thanks for pointing out the TCP/UDP think. The ISP added a DNS proxy config on the router (NAT on port 53 UDP), from his side, without telling. So, the UDP requests were sent to the router.

**Comment by rmbolger** [comment]
Hooray. Glad it wasn't something more insidious.
