### ISSUE TITLE
ISPConfig DNS-01 Challenge update plugin

### ISSUE THREAD

**Issue by djbx83** [rmbolger/Posh-ACME#380]
Hello,
is it possible to implement a new plugin for DNS-01 challange that update records to ISPConfig?

Thank you so much

**Comment by djbx83** [comment]
I've found this plugin for certbox https://github.com/m42e/certbot-dns-ispconfig
I think this could help.

Thank you

**Comment by rmbolger** [comment]
Hi @djbx83. I've never heard of ISPConfig. My quick web searching makes it sound like it's a generic hosting control panel? https://www.ispconfig.org/

If I've got the right thing, the feature list makes it sound like it can act as a front end for a few different DNS server implementations. But it doesn't say whether it supports an API or not and I can't find any references to it on their Documentation page. Without an API the plugin could connect to, the answer is probably no.

However, other hosting control panels like ISPConfig usually have their own native, automated certificate installer that uses something like Let's Encrypt under the hood. It doesn't look like ISPConfig supports that, but they have an outdated article that links to a forum post about using certbot.
https://www.howtoforge.com/community/threads/securing-ispconfig-3-control-panel-port-8080-with-lets-encrypt-free-ssl.75554/

**Comment by rmbolger** [comment]
That plugin does make it look like there *is* an API. So there's hope. Do you have an instance you could send me credentials for that I could test against? I'm not sure I'm up for building my own instance from scratch.

**Comment by djbx83** [comment]
Yeah, for sure.
I will prepare a new vm in a couple of days with last ISPConfig for testing pourposes.

See you soon

**Comment by djbx83** [comment]
Hello @rmbolger ,
I've finished to set-up a new instance of ISPConfig.
Please let me know how can I send you account info to access it.

Regards

**Comment by rmbolger** [comment]
I've got a works-for-me version of the plugin ready to go in the ISPConfig-plugin branch.

**Comment by djbx83** [comment]
Thank you so much Ryan!

**Comment by rmbolger** [comment]
FYI, it's now merged with the main branch. So the links above will be broken. But it should also be in the next official release which I'm hoping to publish soon.
