### ISSUE TITLE
Digital Ocean acme-challenge breaks when over 20 domains

### ISSUE THREAD

**Issue by Xpyder** [rmbolger/Posh-ACME#384]
I dug into the code and the error seems to be that ‘Find-DOZone’ Doesn’t properly support pagination
This breaks the ability to use the script when you have more than 20 domains across all of your certificates

See:
https://docs.digitalocean.com/reference/api/api-reference/#section/Introduction/Links-and-Pagination

For ease of debugging here’s the code to replicate the “check domains” part of Find-DOZone in DOcean.ps1

```
$ApiRoot = 'https://api.digitalocean.com/v2/domains'
$RestParams = @{
    Headers =  @{Authorization='Bearer {your api token}'}
    ContentType = 'application/json'}
$script:UseBasic = @{UseBasicParsing=$True}
(Invoke-RestMethod "$ApiRoot" @RestParams @script:UseBasic).domains|tee -va domains
$domains.count
```

**Comment by Xpyder** [comment]
Here’s equivalent code to the above that does support the pagination and gathers all the domains into $zones (as used in the script)

```
$ApiRoot = 'https://api.digitalocean.com/v2/domains'
$RestParams = @{
    Headers =  @{Authorization='Bearer {Your API Key}'}
    ContentType = 'application/json'}
$script:UseBasic = @{UseBasicParsing=$True}

		$zones = @()
		$responses = @()
		$request = $ApiRoot
		do {
			try {
				$responses += Invoke-RestMethod "$request" @RestParams @script:UseBasic
			} catch {
				throw
			}
			$zones += ($responses[-1]).domains
			$request = $responses[-1].links.pages.next
		} until (
			($null -eq $request)
		)
```

**Comment by rmbolger** [comment]
Hey @Xpyder. Thanks for the heads up on this. Rather than implementing paging to get all the domains on the account, I think I'm going to modify the logic to match some other plugins where it queries for the existence of each test zone directly. It's marginally less efficient for small accounts, but more efficient for really big accounts.

**Comment by Xpyder** [comment]
Makes sense, I was actually surprised when I saw it gathered all domains rather than just querying the one in question.   Feel free to note and then close my pr

**Comment by rmbolger** [comment]
It's definitely one of the earlier plugins I wrote...heh. So it's missing some of the more common tricks I've picked up over the years. I'm using this as an opportunity to revamp it. In any case, thanks again for bringing this up though. I really do appreciate it!

**Comment by rmbolger** [comment]
Updated version with the fixes is now in the main branch if you wanna test it out.

**Comment by Xpyder** [comment]
Thanks, I'll probably test it next cycle (about 2 months)

**Comment by rmbolger** [comment]
It'll definitely be in a new release by then. So feel free to submit another issue if you run into problems.
