### ISSUE TITLE
Help me please: windows does not have enough information to verify this certificate

### ISSUE THREAD

**Issue by orlipr84** [rmbolger/Posh-ACME#390]
Hello there

I have installed and configured the certificate service using the posh-acme client and let's encrypt, it was working fine for months but as of today I started receiving this error message: windows does not have enough information to verify this certificate. Can someone help me please. 

Thanks.

![Untitled](https://user-images.githubusercontent.com/87840598/135355623-22089e48-c39f-432a-b246-2afb9b034eff.png)
![error](https://user-images.githubusercontent.com/87840598/135355626-6355279e-849f-4668-9a88-b713ca00325d.jpg)

**Comment by rmbolger** [comment]
An intermediate certificate (not your specific server certificate) that your server may have been using expired today. The quickest way to fix it is likely to reboot your server. However, before you reboot, double check the following:

- The system date/time is correct (including time zone)
- Run the following PowerShell command to make sure the `ISRG Root X1` cert is in your Trusted Root cert store.

```
Get-ChildItem Cert:\LocalMachine\Root\CABD2A79A1076A31F21D253635CB039D4329A5E8
```

After the reboot, it should automatically find the non-expired version of that intermediate cert and start using it instead.

**Comment by orlipr84** [comment]
Thanks for your quick response:

I ran the powershell command and the ISRG Root X1 was not in the  Trusted Root cert store. I downloaded the corresponding certificate from the website [https://censys.io/certificates/96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6](url) and imported it into the Trusted Root cert store and when I execute the powershell command I get everything right. But after restarting the server, the certificate tells me that it is still invalid because the intermediate chain R3 expired today..

![ps](https://user-images.githubusercontent.com/87840598/135374654-167a3b99-43b7-4e57-bada-ff91b3654bb9.jpg)
![ISRG Root X1](https://user-images.githubusercontent.com/87840598/135374666-e179e2f0-30f7-4d6c-adcb-178a940554d8.jpg)
![certificte2](https://user-images.githubusercontent.com/87840598/135374662-8eda3218-1320-49af-a266-935024ae254b.jpg)
![certificte1](https://user-images.githubusercontent.com/87840598/135374664-dea410f4-297b-46f9-b49f-b92bd44e65fd.jpg)

**Comment by orlipr84** [comment]
Thanks for your quick response:

I ran the powershell command and the ISRG Root X1 was not in the Trusted Root cert store. I downloaded the corresponding certificate from the website https://censys.io/certificates/96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6 and imported it into the Trusted Root cert store and when I execute the powershell command I get everything right. But after restarting the server, the certificate tells me that it is still invalid because the intermediate chain R3 expired today..

![ps](https://user-images.githubusercontent.com/87840598/135375314-18563a14-5159-4033-bc24-565f1ec20068.jpg)
![ISRG Root X1](https://user-images.githubusercontent.com/87840598/135375317-6e4b2fb9-aeb3-4bd1-8bb8-bcfa6a37bdeb.jpg)
![certificte1](https://user-images.githubusercontent.com/87840598/135375311-169a1225-0943-4b28-893f-72110bbe0a7a.jpg)
![certificte2](https://user-images.githubusercontent.com/87840598/135375313-6ab4907f-76e2-46f9-b7af-1fb7a5b1396e.jpg)

**Comment by orlipr84** [comment]
I had to download manually the valid ISRG Root X1 certificate from the site  [https://letsencrypt.org/certificates/](url) and install it and after restart the server everything work properlys.

Thanks for your support.
Regards.

![cert_good1](https://user-images.githubusercontent.com/87840598/135382514-5ead6989-d0e0-4649-b7ed-130af46ff5aa.jpg)
![cert_good2](https://user-images.githubusercontent.com/87840598/135382518-a625cd87-16db-4913-bf4f-854e0354282e.jpg)
![cert_good3](https://user-images.githubusercontent.com/87840598/135382517-9e026f9b-82fd-4342-8263-c4f523d8742b.jpg)

**Comment by orlipr84** [comment]
I had to download manually the valid ISRG Root X1 certificate from the site [https://letsencrypt.org/certificates/](url) and install it and after restart the server everything work properlys.

Thanks for your support.
Regards.

![cert_good1](https://user-images.githubusercontent.com/87840598/135383161-46bd55a5-7dc1-4093-a115-103a664b25da.jpg)
![cert_good2](https://user-images.githubusercontent.com/87840598/135383165-ecbf9b5e-f4e8-4454-989d-5ca0335adaf1.jpg)
![cert_good3](https://user-images.githubusercontent.com/87840598/135383163-02db7b2a-ce26-4a4d-81d3-c5e266c4770e.jpg)

**Comment by orlipr84** [comment]
The problem was solved, close the post. Thaks.

**Comment by orlipr84** [comment]
The problem was solved, close the post. Thaks.

**Comment by rmbolger** [comment]
Sorry for the delay. Glad to hear you managed to sort things out.

**Comment by orlipr84** [comment]
Your help was very important to solving the problem, thanks for the quick
response and support. Greetings from Havana, Cuba.
