### ISSUE TITLE
"Incorrect datetime value" in ISPConfig plug-in

### ISSUE THREAD

**Issue by remkohat** [rmbolger/Posh-ACME#404]
ISPConfig plug-in returns an error:

```
Submit-ChallengeValidation : ISPConfig Error: Incorrect datetime value: '' for column `dbispconfig`.`dns_rr`.`stamp` at row 1 INSERT INTO `dns_rr` (`server_id`, `zone`, 
`name`, `type`, `data`, `ttl`, `active`, `stamp`, `serial`, `sys_userid`, `sys_groupid`, `sys_perm_user`, `sys_perm_group`, `sys_perm_other`) VALUES ('10', '25', '_acme-
challenge.<domain>', 'TXT', '<challenge>', '60', 'Y', '', '0', '1', '1', 'riud', 'riud', '')
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.10.0\Public\New-PACertificate.ps1:238 char:9
+         Submit-ChallengeValidation
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ISPConfig Error...d', 'riud', ''):String) [Submit-ChallengeValidation], RuntimeException
    + FullyQualifiedErrorId : ISPConfig Error: Incorrect datetime value: '' for column `dbispconfig`.`dns_rr`.`stamp` at row 1 INSERT INTO `dns_rr` (`server_id`, `zone` 
   , `name`, `type`, `data`, `ttl`, `active`, `stamp`, `serial`, `sys_userid`, `sys_groupid`, `sys_perm_user`, `sys_perm_group`, `sys_perm_other`) VALUES ('10', '25',   
  '_acme-challenge.<domain>', 'TXT', '<challenge>', '60', 'Y', '', '0', '1', '1', 'riud', 'riud', ''),Submit-ChallengeValidation
```

I've solved this by adding this on line 60:

`stamp = $($(get-date).ToString('yyyy-MM-dd HH:mm:ss'))
`
```
47                $queryParams = @{
48                    Function = 'dns_txt_add'
49                    BodyParams = @{
50                        client_id = $null
51                        update_serial = $true
52                        params = @{
53                            server_id = $serverID
54                            zone = $zoneID
55                            name = $recShort
56                            type = 'TXT'
57                            data = $TxtValue
58                            active = 'Y'
59                            ttl = 60
60 +                          stamp = $($(get-date).ToString('yyyy-MM-dd HH:mm:ss'))
61                        }
62
63                    }
64                }
```

**Comment by rmbolger** [comment]
Hey @remkohat. Thanks for reaching out and suggesting a fix. Out of curiosity, what version of ISPConfig is throwing this error? Back in September when I was working on this for the user who originally requested it, this code was working on the instance he had spun up for me. I'm trying to figure out what's different between his instance and yours.

In any case, it seems like a simple enough fix.

**Comment by rmbolger** [comment]
The fix is now in the main branch and should be included in the next release. I'd appreciate if you could test it for me though since I don't currently have an ISPConfig instance to test against.

**Comment by remkohat** [comment]
> Hey @remkohat. Thanks for reaching out and suggesting a fix. Out of curiosity, what version of ISPConfig is throwing this error? Back in September when I was working on this for the user who originally requested it, this code was working on the instance he had spun up for me. I'm trying to figure out what's different between his instance and yours.
> 
I was surprised to see the error myself.
On October the 15th I used Posh-ACME for the first time, to enroll a non-internet accessible certificate.
At that time I was using ISPConfig stable release **3.2.6** for DNS validation and all was working as aspected.

Meanwhile ISPConfig has released stable release **3.2.7p1** which fixes a security issue in the remote API.
I've installed that version on all my servers last week.
I guess that's why the plug-in is throwing the error now.

**Comment by remkohat** [comment]
> The fix is now in the main branch and should be included in the next release. I'd appreciate if you could test it for me though since I don't currently have an ISPConfig instance to test against.

I've tested your change today and it seems to work OK.

**Comment by rmbolger** [comment]
This is now live in 4.11.0
