### ISSUE TITLE
ClouDNS - invalid credentials are reported as "No Zone Found ..."

### ISSUE THREAD

**Issue by webprofusion-chrisc** [rmbolger/Posh-ACME#414]
Currently if you supply invalid credentials to the ClouDNS provider it will attempt the Zone lookup and receive the following from the API (for each attempted zone lookup):
```
[HTTP Status 200]

{"status":"Failed","statusDescription":"Invalid authentication, incorrect user ID or password."}

```

The ClouDNS credentials themselves can be a little complex due to there being an array of options (sub-user etc), so ideally the reported error would be failed authentication, rather than no zone found. If the recursive zone lookup can conceivably have mixed auth results depending on the slice of record name it tries (it loops from the longest record name to the shortest to try to get a zone lookup result) then I can see why we might just catch the error and move on.

Possible alternative strategies:
- Perform some other API operation first to check auth (maybe a call to get current IP address, since we might want to check that also)
- Report the authentication error on first failed call (not sure if that's the right move).
- If all lookup calls fail report it as a possible authentication error.
- or just change the error to be "No Zone Found or Incorrect User ID/Password"

**Comment by rmbolger** [comment]
Hey @webprofusion-chrisc. I tweaked the plugin a bit so the zone finding function only swallows the specific error that indicates the searched-for zone wasn't found. So invalid credential errors should show up properly now.

The only caveat is that if the user has good credentials but hasn't been delegated access to the zone, it'll still show up as zone not found because the API effectively just hides it from them.

**Comment by webprofusion-chrisc** [comment]
Thanks Ryan! I'm working with a user who has been trying to figure out why one instance isn't working and the root cause is that ClouDNS doesn't accept URL encoded passwords, so if the content requires URL encoding (funny characters etc) then it gets mangled and won't be understood by ClouDNS. Just calling the API directly in the browser using the raw password works fine, so the workaround is to set a less complex password.

**Comment by webprofusion-chrisc** [comment]
I should add that I'm still checking whether this is just a new bug in Certify The Web, we recently moved to using the secure parameters etc in Posh-ACME so maybe something is messed up there and introducing encoding when it shouldn't.

**Comment by rmbolger** [comment]
Weird, I generally have special chars in my test account passwords and I haven't run into anything yet. But I'll see if I can purposefully break it. The plugin is ultimately just passing the credentials as a hashtable to the Body param of `Invoke-RestMethod`. So there's no explicit URL encoding beyond what PowerShell natively does. But I think it ultimately does do that under the hood.

**Comment by rmbolger** [comment]
Ok, so I added all of the special chars I could think of to my test account password and it still seems to be working from the plugin. However, I recall one of the things I ran into when I was spinning up my account again was that my API accounts had been "deactivated" because my account had been downgraded to the Free tier which doesn't allow API access. But the API was acting as if I was just sending invalid credentials.

**Comment by webprofusion-chrisc** [comment]
Thanks Ryan, yeah I don't really understand it currently, I was testing with an account the user gave me and we found that if you pasted the complex password into the URL in the browser it worked OK, but via Powershell it got encoded and didn't work (this was testing in Powershell ISE using just our POSH-ACME Wrapper and a call to the ClouDNS Add-DnsTxt, watched with Fiddler classic). 

However, the user reports being able to use raw Posh-ACME to get a cert OK so that implies it's something about the way we call it, I need to reproduce that myself. They also had it working with a complex pwd on old versions of CTW (which used Posh-ACME 4.2, we now use 4.11). The main context differences are that we are running in a Powershell Runspace (in C#, .net 4.6.2 or higher) vs using the native powershell.exe, and obviously we have our Posh-ACME wrapper - I'll look into getting another test account anyway and can do my own testing to figure it out.

**Comment by webprofusion-chrisc** [comment]
Found it, the password has a backtick and we construct the script but don't escape the pwd being fed in. Doh.
