### ISSUE TITLE
Broken link for using SecretsManagment module with POSH-ACME

### ISSUE THREAD

**Issue by robesmithjr** [rmbolger/Posh-ACME#415]
Hi,

Broken link to the guide for using SecretsManagement module with posh-acme.

Great work on the module,

Thanks,

Rob

**Comment by robesmithjr** [comment]
The link under new features is broken, the link to the guide deeper in the doc works

**Comment by rmbolger** [comment]
Hey @robesmithjr, thanks for reaching out! The link in the readme should be fixed now.
