### ISSUE TITLE
Duplicate Certificate Request

### ISSUE THREAD

**Issue by peter-thompson-sc** [rmbolger/Posh-ACME#417]
Hello, 

I am using posh-acme v4.10.0.  When I look at website https://crt.sh I see that there are 2 certificates issued each time I run my script. The certificate the script downloads corresponds with the 2nd of the 2 certificates shown on https://crt.sh. 

My script is run once a week.

Why when running the script below, would it be generating 2 certificates? The output of the script is only showing 1 certificate being created?

$LE_Env = "LE_PROD"

import-module posh-ACME
$env:POSHACME_HOME = "C:\LetsEncrypt"
import-module posh-ACME -force
$domainname = 'example.com'

# Request  Certificate
$NewCert = (New-PACertificate "*.$domainname","$domainname" -Name $domainname -Contact '****' -AcceptTOS -PfxPass $OLSCertPassword -DirectoryUrl $LE_Env -Plugin Route53 -PluginArgs @{R53UseIAMRole=$true} -DnsSleep 15 -Force)
$NewCert | fl

#Upload PFX Certificate used by Windows servers to S3 Bucket
$PFX_Cert = $NewCert.PfxFile
Write-S3Object -BucketName example/Certificates/ -File $PFX_Cert -Key "domainname.pfx"

**Comment by rmbolger** [comment]
Hi @peter-thompson-sc. What you're seeing in crt.sh are what is known as "precertificates". It's essentially a copy of the cert with an extra OID added that has to do with certificate transparency requirements. You can see the difference in the Summary field when viewing a specific cert's details in crt.sh. You can find a bit more discussion about it here:

https://community.letsencrypt.org/t/duplicates-in-ct-logs-precertificate-vs-leaf-certificate/69190

I'm pretty sure there's a way to format the crt.sh URL so it doesn't show duplicates. But I can never remember what it is.

**Comment by peter-thompson-sc** [comment]
Thanks for the info Ryan.
