### ISSUE TITLE
Request: Leaseweb DNS API support

### ISSUE THREAD

**Issue by tmaniac** [rmbolger/Posh-ACME#420]
I was wondering if you could include the Leaseweb API in Posh-ACME.

I know the acme.sh project supports it https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_leaseweb.sh

But my PowerShell skills are not so good that i can translate the .sh to ps1 :(

thanks in advance :)

**Comment by rmbolger** [comment]
Hey @tmaniac. Thanks for reaching out. I'd be happy to. Do I assume correctly that the DNS hosting is free with the purchase of a domain from them?

I've done blind ports of acme.sh plugins before, but it's way easier when I've got an actual account to test things with. Would you be willing to sponsor the cost of the domain registration? The cheapest TLD appears to be 6 EUR for a year. I won't actually need a year, but it's the minimum contract length they support. Alternatively, it can also work if you temporarily share your own API key and domain name with me to test against so I don't have to purchase a domain myself.

**Comment by tmaniac** [comment]
Sure, i can sponsor you for 6 euro's.
Just tell me where to send it to :)

**Comment by rmbolger** [comment]
Perfect. I placed the domain order. Now awaiting the account details and confirmation everything is setup.

**Comment by rmbolger** [comment]
Quick update. Leaseweb has denied my order because apparently they don't do business with individuals, only other businesses. Gonna need some more time to see if I can work around this.

**Comment by rmbolger** [comment]
I managed to whip up a potential first draft of the LeaseWeb plugin using mostly just their API docs. If you want to give it a shot, you can find it in the [leaseweb](/rmbolger/Posh-ACME/tree/leaseweb) branch. Here's a link to the plugin file and readme.

https://github.com/rmbolger/Posh-ACME/blob/leaseweb/Posh-ACME/Plugins/LeaseWeb.ps1
https://github.com/rmbolger/Posh-ACME/blob/leaseweb/docs/Plugins/LeaseWeb.md

You can drop the PS1 file in your existing module's Plugins folder or use [this guide](https://poshac.me/docs/v4/Guides/Using-Custom-Plugins/) to use the POSHACME_PLUGINS environment variable. Once installed, you'll either have to close and re-open your PowerShell session or force reload the module using `Import-Module Posh-ACME -Force`.

Then you can test just the plugin's functionality without actually requesting a cert like this:

```powershell
$DebugPreference = 'Continue'
$pArgs = @{ LSWApiKey = (Read-Host 'API Key' -AsSecureString) }
Publish-Challenge example.com (Get-PAAccount) faketoken LeaseWeb $pArgs -Verbose
Unpublish-Challenge example.com (Get-PAAccount) faketoken LeaseWeb $pArgs -Verbose
```

`example.com` would be your actual domain. But `faketoken` should literally be the string "faketoken". You'll also be prompted for your API key.

This should give you both Verbose and Debug output in case anything fails. Let me know how things go. Once this basic test works, I'd love if you could do some additonall edge case tests for me as well.

**Comment by tmaniac** [comment]
just checked.
Unfortunately the API throws an error 400;

PS D:\Script> Publish-Challenge <DOMAIN> (Get-PAAccount) faketoken LeaseWeb $pArgs -Verbose
VERBOSE: Publishing challenge for Domain tmaniac.nl with Token faketoken using Plugin LeaseWeb and DnsAlias ''.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling LeaseWeb plugin to add _acme-challenge.<DOMAIN> TXT with value ckKRZ-VXAvh3_GMbpdaK9QYXFhaAMZM4IPOAfjhtR6w
DEBUG: Checking _acme-challenge.<DOMAIN>
DEBUG: GET https://api.leaseweb.com/hosting/v2/domains/_acme-challenge.<DOMAIN>
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At D:\Scripts\POSH-ACME\LeaseWeb.ps1:256 char:25
+ ...           $response = Invoke-RestMethod @queryParams @script:UseBasic
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by tmaniac** [comment]
Ok, i made some changes myself and now it works;

Line 12 (and 112):
 `[string]$LSWApiBase = 'https://api.leaseweb.com',`
Should be:
`[string]$LSWApiBase = 'https://api.leaseweb.com/hosting/v2/',`

line 258:
`# 404 responses mean the zone wasn't found, so skip to the next check
            if (404 -eq $_.Exception.Response.StatusCode) {
                continue
            }`
Should be:
`# 404 responses mean the zone wasn't found, so skip to the next check
            if (404 -eq $_.Exception.Response.StatusCode) {
                continue
            }
            # Leaseweb sometimes just states bad request if not found
            elseif (400 -eq $_.Exception.Response.StatusCode) {
                continue
            }`

Furthermore, i replaced all instances of:
`Body = @{...}`

with:
`Body = [ordered]@{...}`

Now i get the following output when i run the cmd:
`PS D:\Scripts> Publish-Challenge <DOMAIN> (Get-PAAccount) faketoken LeaseWeb $pArgs -Verbose
VERBOSE: Publishing challenge for Domain <DOMAIN> with Token faketoken using Plugin LeaseWeb and DnsAlias ''.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling LeaseWeb plugin to add _acme-challenge.<DOMAIN> TXT with value ckKRZ-VXAvh3_GMbpdaK9QYXFhaAMZM4IPOAfjhtR6w
VERBOSE: Found domain <DOMAIN>
DEBUG: GET https://api.leaseweb.com/hosting/v2//domains/<DOMAIN>/resourceRecordSets/_acme-challenge.<DOMAIN>/TXT
DEBUG: POST https://api.leaseweb.com/hosting/v2//domains/<DOMAIN>/resourceRecordSets
{
    "name":  "_acme-challenge.<DOMAIN>",
    "type":  "TXT",
    "content":  [
                    "ckKRZ-VXAvh3_GMbpdaK9QYXFhaAMZM4IPOAfjhtR6w"
                ],
    "ttl":  60
}
VERBOSE: Adding new TXT record for _acme-challenge.<DOMAIN>


name     : _acme-challenge.<DOMAIN>.
type     : TXT
content  : {"ckKRZ-VXAvh3_GMbpdaK9QYXFhaAMZM4IPOAfjhtR6w"}
ttl      : 60
editable : True
_links   : @{self=; collection=}`

**Comment by tmaniac** [comment]
Ok, here goes :)
i replaced all 6 instances of
```
Invoke-RestMethod @queryParams @script:UseBasic | Out-Null
```
with
```
Invoke-RestMethod @queryParams | Out-Null
```
the 'Get-LSWTxtRecord' function returns the record as followed:
```
name     : _acme-challenge.<DOMAIN>.
type     : TXT
content  : {"ckKRZ-VXAvh3_GMbpdaK9QYXFhaAMZM4IPOAfjhtR6w"}
ttl      : 60
editable : True
_links   : @{self=; collection=}
```
So when you try to compare it, it takes the `"` as well.
I had to remove those from the results like so:
```
$rec.content.replace('"','')
```
i applied this on line 31, from;
```
if ($TxtValue -in $rec.content) 
```
to:
```
if ($TxtValue -in $rec.content.replace('"',''))
```

and further down the line i changed a bit more to get the proper array
line 39:
```
content = $rec.content + @( $TxtValue )
```
with
```
content =  @( $TxtValue,$rec.content.replace('"','') )
```

may be a bit of hack n slash...but it moved me along ;)

**Comment by tmaniac** [comment]
it works!

```
PS D:\Script> $script:UseBasic = @{ UseBasicParsing = $true }
PS D:\Script> Unpublish-Challenge <DOMAIN> (Get-PAAccount) faketoken LeaseWeb $pArgs -Verbose
VERBOSE: Unpublishing challenge for Domain <DOMAIN> with Token faketoken using Plugin LeaseWeb and DnsAlias ''.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling LeaseWeb plugin to remove _acme-challenge.<DOMAIN> TXT with value ckKRZ-VXAvh3_GMbpdaK9QYXFhaAMZM4IPOAfjhtR6w
VERBOSE: Found domain <DOMAIN>
DEBUG: GET https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/_acme-challenge.<DOMAIN>/TXT
DEBUG: DELETE https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/_acme-challenge.<DOMAIN>/TXT
VERBOSE: Removing TXT record for _acme-challenge.<DOMAIN>
```

**Comment by rmbolger** [comment]
Excellent!. Let's do a few more tests for some other potential scenarios. As before, `example.com` should be your actual domain. In the last test, `fakedomain.com` can be anything. It doesn't actually get used except for debug messages when `-DnsAlias` is specified.

This one makes sure we can add/remove records for dotted labels in the domain apex.

```powershell
Publish-Challenge www.example.com (Get-PAAccount) faketoken LeaseWeb $pArgs -Verbose
Unpublish-Challenge www.example.com (Get-PAAccount) faketoken LeaseWeb $pArgs -Verbose
```

This one will test the ability to add/remove multiple values for the same TXT record.

```powershell
Publish-Challenge example.com (Get-PAAccount) fakeA LeaseWeb $pArgs -Verbose
Publish-Challenge example.com (Get-PAAccount) fakeB LeaseWeb $pArgs -Verbose
Publish-Challenge example.com (Get-PAAccount) fakeC LeaseWeb $pArgs -Verbose
Unpublish-Challenge example.com (Get-PAAccount) fakeA LeaseWeb $pArgs -Verbose
Unpublish-Challenge example.com (Get-PAAccount) fakeB LeaseWeb $pArgs -Verbose
Unpublish-Challenge example.com (Get-PAAccount) fakeC LeaseWeb $pArgs -Verbose
```

This one will test the ability to create a record in the domain apex.

```powershell
Publish-Challenge fakedomain.com (Get-PAAccount) fakeA LeaseWeb $pArgs -Verbose -DnsAlias example.com
Unpublish-Challenge fakedomain.com (Get-PAAccount) fakeA LeaseWeb $pArgs -Verbose -DnsAlias example.com
```

**Comment by tmaniac** [comment]
Ok,

publishing works.
However, removing records from a larger CNAME record gives problems;
```
PS D:\Script> Unpublish-Challenge <DOMAIN> (Get-PAAccount) fakeA LeaseWeb $pArgs -Verbose
VERBOSE: Unpublishing challenge for Domain <DOMAIN> with Token fakeA using Plugin LeaseWeb and DnsAlias ''.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling LeaseWeb plugin to remove _acme-challenge.<DOMAIN> TXT with value ASlZPvgcqpau4oKLey1BXaqdY6wi5DcMhss3SkGnoY8
VERBOSE: Found domain <DOMAIN>
DEBUG: GET https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/_acme-challenge.<DOMAIN>/TXT
DEBUG: PUT https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/_acme-challenge.<DOMAIN>/TXT
{
    "content":  [
                    "\"YMLkQjsElv50ZomdmJe2-47XvjxYp_JJozJXOBOAWx0\"",
                    "\"muAWyYk9hn-ohXKXPk4O8XM7FcjvWjPK4JMu5FYy0kc\""
                ],
    "ttl":  60
}
VERBOSE: Removing TXT record value ASlZPvgcqpau4oKLey1BXaqdY6wi5DcMhss3SkGnoY8 from _acme-challenge.<DOMAIN>
PS D:\Script> Unpublish-Challenge <DOMAIN> (Get-PAAccount) fakeB LeaseWeb $pArgs -Verbose
VERBOSE: Unpublishing challenge for Domain <DOMAIN> with Token fakeB using Plugin LeaseWeb and DnsAlias ''.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling LeaseWeb plugin to remove _acme-challenge.<DOMAIN> TXT with value muAWyYk9hn-ohXKXPk4O8XM7FcjvWjPK4JMu5FYy0kc
VERBOSE: Found domain <DOMAIN>
DEBUG: GET https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/_acme-challenge.<DOMAIN>/TXT
DEBUG: PUT https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/_acme-challenge.<DOMAIN>/TXT
{
    "content":  "\"YMLkQjsElv50ZomdmJe2-47XvjxYp_JJozJXOBOAWx0\"",
    "ttl":  60
}
VERBOSE: Removing TXT record value muAWyYk9hn-ohXKXPk4O8XM7FcjvWjPK4JMu5FYy0kc from _acme-challenge.<DOMAIN>
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At D:\Scripts\POSH-ACME\LeaseWeb.ps1:167 char:17
+ ...               Invoke-RestMethod @queryParams @script:UseBasic | Out-N ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

i think it has to do with the array having an extra ',' in the end...

**Comment by rmbolger** [comment]
Looks like the `content` field in the second call wasn't converted to JSON as an array (because there's only 1 value left) but a simple string value. Pretty sure I can fix that. One sec.

**Comment by rmbolger** [comment]
Ok, pushed an update to the branch that should fix it.

**Comment by tmaniac** [comment]
Everything works!

not exactly sure what the last 2 commands are used for but here's the output:
```
PS D:\Script> Publish-Challenge fake.it (Get-PAAccount) fakeA LeaseWeb $pArgs -Verbose -DnsAlias <DOMAIN>
VERBOSE: Publishing challenge for Domain fake.it with Token fakeA using Plugin LeaseWeb and DnsAlias '<DOMAIN>'.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling LeaseWeb plugin to add <DOMAIN> TXT with value ASlZPvgcqpau4oKLey1BXaqdY6wi5DcMhss3SkGnoY8
DEBUG: Checking <DOMAIN>
DEBUG: GET https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>
VERBOSE: Found domain <DOMAIN>
DEBUG: GET https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/<DOMAIN>/TXT
DEBUG: PUT https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/<DOMAIN>/TXT
{
    "content":  [
                    "\"v=spf1 a mx -all\"",
                    "\"ASlZPvgcqpau4oKLey1BXaqdY6wi5DcMhss3SkGnoY8\""
                ],
    "ttl":  60
}
VERBOSE: Adding TXT record value ASlZPvgcqpau4oKLey1BXaqdY6wi5DcMhss3SkGnoY8 to <DOMAIN>

PS D:\Script> Unpublish-Challenge fake.it (Get-PAAccount) fakeA LeaseWeb $pArgs -Verbose -DnsAlias <DOMAIN>
VERBOSE: Unpublishing challenge for Domain fake.it with Token fakeA using Plugin LeaseWeb and DnsAlias '<DOMAIN>'.
DEBUG: Loading PAAccount list from disk
DEBUG: Calling LeaseWeb plugin to remove <DOMAIN> TXT with value ASlZPvgcqpau4oKLey1BXaqdY6wi5DcMhss3SkGnoY8
VERBOSE: Found domain <DOMAIN>
DEBUG: GET https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/<DOMAIN>/TXT
DEBUG: PUT https://api.leaseweb.com/hosting/v2/domains/<DOMAIN>/resourceRecordSets/<DOMAIN>/TXT
{
    "content":  [
                    "\"v=spf1 a mx -all\""
                ],
    "ttl":  60
}
VERBOSE: Removing TXT record value ASlZPvgcqpau4oKLey1BXaqdY6wi5DcMhss3SkGnoY8 from <DOMAIN>
```

**Comment by rmbolger** [comment]
Perfect. I think this is ready to merge. Thanks a ton for doing the testing work for me. Is there anything you think I should add to the plugin's user guide for it to help other folks?

**Comment by tmaniac** [comment]
I think it's pretty self explanatory!

Thanks for the coding!
time for me to start building some integration scripts etc (or be lazy and ask the CertifyTheWeb team to integrate the fresh Leaseweb plugin ;) )

**Comment by rmbolger** [comment]
Awesome, merging the changes into the main branch now, I'll see if I can get an updated release out next week some time.

**Comment by rmbolger** [comment]
This is now live in 4.13.0
