### ISSUE TITLE
Loopia Plugin: Error in the PowerShell example code

### ISSUE THREAD

**Issue by TomAafloen** [rmbolger/Posh-ACME#426]
On the info page for the Loopia plugin (https://poshac.me/docs/v4/Plugins/Loopia/) there is some PowerShell example code:

![image](https://user-images.githubusercontent.com/29425904/158405396-c40490a4-779b-4bd9-812a-d7924d0b3d2d.png)

Running that code gives the error:
**_Unexpected token '@{' in expression or statement_**

There is an equal sign missing there:

![image](https://user-images.githubusercontent.com/29425904/158405550-86319d6a-049d-4b88-8955-77833170b20c.png)

Thanks for the fix to this plugin yesterday, really appreciate it!

**Comment by rmbolger** [comment]
Ooh, thanks! Fixed.
