### ISSUE TITLE
Plugin Support for No-IP Managed DNS

### ISSUE THREAD

**Issue by peter-thomas-mgd** [rmbolger/Posh-ACME#427]
I'm using Posh-ACME with No-IP as the DNS service. Any chance on getting a plugin for this platform? Thanks!

**Comment by rmbolger** [comment]
Hey @peter-thomas-mgd, thanks for reaching out. I'd be happy to give it a try. But I can't seem to find any API documentation for their service beyond the basic protocol for their free Dynamic DNS service. The Managed DNS service also doesn't appear to have any sort of trial period. So it would be a minimum of $30 for me to get an account for 1 year with 1 zone unless you're willing to temporarily share your credentials.

**Comment by peter-thomas-mgd** [comment]
Thanks for the quick response! I poked around a bit to see what type of documentation exists on their web site. I was also unable to find anything that explicitly mentioned support for TXT records in the Managed DNS service tier. I have opened a support ticket to see what they support. Depending on the answer, I may end up looking at one of the other supported providers for hosting my DNS. I will update this ticket once I here back from them. Cheers!

**Comment by peter-thomas-mgd** [comment]
@rmbolger, I heard back from the No-IP support team. Unfortunately they don't have an API that can be used to manage TXT records in any of their DNS service offerings. So it looks like I'll be moving my business to CloudFlare, which seems to have a fairly robust offering in this regard. Thanks for your help.

**Comment by rmbolger** [comment]
That's unfortunate. But Cloudflare has a lot of good offerings and will likely continue to be well supported by this and other ACME clients. So it's a good alternative choice.
