### ISSUE TITLE
Azure DNS - TXT-record does not propagate

### ISSUE THREAD

**Issue by dimmelsw** [rmbolger/Posh-ACME#432]
Iam trying to set up Azure DNS for issuing Let'sEncrypt for the develeopment of a webapp.
I've followed your tutorial: [https://poshac.me/docs/v4/Plugins/Azure/](url) and created everything I need.

1. Connected to Azure
2. Created a custom role
3. Created an app registration (password based)
4. Assigned Permissions
5. Switched to the Stagging LE CA

Everything is fine, and i can see my settings in Azure to check them.

**I then created a public dns zone in Azure, and here is the (i think) tricky part: I gave it (Azure DNS Zone) the same name, which also our productive hosted DNS Zone at a different DNS Provider has. 
So: (Azure) example.de - (Hosteurope) example.de**

App registration has acces only to the TXT-records of the Azure DNS Zone.

Now when i run:
`PS C:\Users\Administrator> New-PACertificate test.example.de -Plugin Azure -PluginArgs $pArgs -verbose`
I can see the TXT-Record and it's value getting created in Azure via POSH-ACME.
It (POSH) then wait two minutes to propagate, then deletes the record from Azure and in POSH there is following error:
`Submit-ChallengeValidation : Authorization invalid for test.example.de: DNS problem: NXDOMAIN looking up TXT for
_acme-challenge.test.example.de - check that a DNS record exists for this domain
In C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.13.1\Public\New-PACertificate.ps1:238 Zeichen:9
        Submit-ChallengeValidation
         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Authorization i...for this domain:String) [Submit-ChallengeValidation
   ], RuntimeException
    + FullyQualifiedErrorId : Authorization invalid for test.example.de: DNS problem: NXDOMAIN looking up TXT for _acme
   -challenge.test.example.de - check that a DNS record exists for this domain,Submit-ChallengeValidation`

Also, when I try nslookup with 1.1.1.1 or 8.8.8.8. or 8.8.4.4 the record seems to not be propagated, because I always get "Non existent domain". But when I use nslookup with the Azure NS "ns1-37.azure-dns.com." I get the record and it's value.

Also here is the full log with `-verbose`
PS C:\Users\Administrator> New-PACertificate test.example.de -Plugin Azure -PluginArgs $pArgs -verbose
AUSFÜHRLICH: Updating directory info from https://acme-staging-v02.api.letsencrypt.org/directory
AUSFÜHRLICH: Using ACME Server https://acme-staging-v02.api.letsencrypt.org/directory
AUSFÜHRLICH: Using account 49167618
AUSFÜHRLICH: Order name not specified, using 'test.example.de'
AUSFÜHRLICH: Creating a new order 'test.example.de' for test.example.de
AUSFÜHRLICH: Publishing challenge for Domain test.example.de with Token _f6an7fgu7gLOJ0nrSxYxNVa9fgtuoeqDj88EXRPd0o
using Plugin Azure and DnsAlias ''.
AUSFÜHRLICH: Attempting to find hosted zone for _acme-challenge.test.example.de
AUSFÜHRLICH: Querying _acme-challenge.test.example.de
AUSFÜHRLICH: GET
https://management.azure.com/subscriptions/5c579297-ffb6-434a-8236-ff7944bd5925/resourceGroups/acme-dns/providers/Micro
soft.Network/dnszones/example.de/TXT/_acme-challenge.test?api-version=2018-03-01-preview with 0-byte payload
AUSFÜHRLICH: Sending updated _acme-challenge.test
AUSFÜHRLICH: PUT
https://management.azure.com/subscriptions/5c579297-ffb6-434a-8236-ff7944bd5925/resourceGroups/acme-dns/providers/Micro
soft.Network/dnszones/example.de/TXT/_acme-challenge.test?api-version=2018-03-01-preview with -1-byte payload
AUSFÜHRLICH: received 422-byte response of content type application/json; charset=utf-8
AUSFÜHRLICH: Saving changes for Azure plugin
AUSFÜHRLICH: Sleeping for 120 seconds while DNS change(s) propagate
AUSFÜHRLICH: 60 seconds remaining to sleep
AUSFÜHRLICH: Requesting challenge validations
AUSFÜHRLICH: Unpublishing challenge for Domain test.example.de with Token _f6an7fgu7gLOJ0nrSxYxNVa9fgtuoeqDj88EXRPd0o
using Plugin Azure and DnsAlias ''.
AUSFÜHRLICH: Attempting to find hosted zone for _acme-challenge.test.example.de
AUSFÜHRLICH: Querying _acme-challenge.test.example.de
AUSFÜHRLICH: GET
https://management.azure.com/subscriptions/5c579297-ffb6-434a-8236-ff7944bd5925/resourceGroups/acme-dns/providers/Micro
soft.Network/dnszones/example.de/TXT/_acme-challenge.test?api-version=2018-03-01-preview with 0-byte payload
AUSFÜHRLICH: received 422-byte response of content type application/json; charset=utf-8
AUSFÜHRLICH: Deleting _acme-challenge.test. No values left.
AUSFÜHRLICH: DELETE
https://management.azure.com/subscriptions/5c579297-ffb6-434a-8236-ff7944bd5925/resourceGroups/acme-dns/providers/Micro
soft.Network/dnszones/example.de/TXT/_acme-challenge.test?api-version=2018-03-01-preview with 0-byte payload
AUSFÜHRLICH: received 0-byte response of content type
AUSFÜHRLICH: Saving changes for Azure plugin
Submit-ChallengeValidation : Authorization invalid for test.example.de: DNS problem: NXDOMAIN looking up TXT for
_acme-challenge.test.example.de - check that a DNS record exists for this domain
In C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.13.1\Public\New-PACertificate.ps1:238 Zeichen:9
         Submit-ChallengeValidation
         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Authorization i...for this domain:String) [Submit-ChallengeValidation
   ], RuntimeException
    + FullyQualifiedErrorId : Authorization invalid for test.example.de: DNS problem: NXDOMAIN looking up TXT for _acme
   -challenge.test.example.de - check that a DNS record exists for this domain,Submit-ChallengeValidation

What am I doing wrong/ where am i mistaken?

**Comment by dimmelsw** [comment]
Excuse me, I was on holiday.
I tried your option 3 (the other two are not actionable within short time).
But I cant seem to find the hostname for my Azure DNS Zone to create a CName in my productive DNS.
I tried various configurations, also i tried the also the NS (which seems to be some kind of host?)
![Bild_2022-04-28_150033722](https://user-images.githubusercontent.com/6417192/165757817-5d529e01-2b00-4c8f-94c0-168c860fd9fc.png)
Do you have an idea?

**Comment by dimmelsw** [comment]
Nvm, i solved it.
Forgot to set the NS record :)

**Comment by rmbolger** [comment]
Nice. Glad to hear you're working now.
