### ISSUE TITLE
goDaddy Code

### ISSUE THREAD

**Issue by centuryx476** [rmbolger/Posh-ACME#434]
Hello,
I do not understand the code for some reason. It is asking me to input the secret part of the API Key ?
I did that and then it asks me for the GDKey and the GDSecret. It then waits a bit and then loops all over again ?
It is pretty simple code unless I am overthinking it ?

`$pArgs = @{
    GDKey = 'xxxxxxxxxxxxxxxx'
    GDSecret = (Read-Host 'Secret' -AsSecureString)
}
New-PACertificate example.com -Plugin GoDaddy -PluginArgs $pArgs
`

**Comment by centuryx476** [comment]
OK, I'm stupid. I had to input the same secret key in the above code example.

**Comment by rmbolger** [comment]
No worries. Sometimes we all miss simple stuff.
