### ISSUE TITLE
Help with active directory certificate questions using posh-acme and server migration. 

### ISSUE THREAD

**Issue by orlipr84** [rmbolger/Posh-ACME#435]
Hello friends,

Perhaps this is not the place to comment on this situation, but I don't know what to do or where to go.

I am using Posh-Acme to use LTE Encrypt certificates for Active Directory.

I need to migrate the Active Directory from server 2012r2 to server 2019. What do you recommend so as not to lose the certificate already downloaded and configured?

Greetings, and thanks for any help.

**Comment by rmbolger** [comment]
Hi @orlipr84. The answer to your question is going to depend on whether you are doing an in-place upgrade of the OS on the domain controller or a migration to a new domain controller where the two exist simultaneously until you demote the old one.

For an in-place upgrade, my understanding is that certificates (and scheduled tasks and local user profiles) will all be preserved in the new OS. So theoretically you shouldn't need to do anything.

For a new domain controller, presumably it will have a new name and thus need a new certificate. So you'd have to re-setup whatever script you're using to get the cert on the previous domain controller.

**Comment by orlipr84** [comment]
Our migration will be adding new domain controllers. But we want to keep the same names on the servers as well as the IP addresses. The solution that we are going to carry out is perhaps not the best, but in our little experience, it is the only possible one.

We have three domain controllers, and we are going to remove, reinstall and re-add each one and thus keep the names and configurations that we already have.

In this way, the script that we already have will serve us without problems.

Greetings, and thanks for the prompt response and support.

Blessings from Havana, Cuba.
👍🙌👌
