### ISSUE TITLE
Renewals failing due to pluginargs being set to null on renew cert

### ISSUE THREAD

**Issue by mikes-gh** [rmbolger/Posh-ACME#438]
I install a cert in the context of an admin user using DMEasy plugin using SecureString for storage.
The DNSME plugin args use secure string.
```
{
    "DMEKey":  "xx-yyy-zzz-aaa-bbb",
    "DMESecret":  {
                      "origType":  "securestring",
                      "value":  "01000000d08c9ddf0115d1118c7a00c04fc297eb010000004e1aee5f244ed242a42c39ffd486bab50000000002000000000003660000c000000010000000d751b8453fbbb08ba43ec63903c3c5f70000000004800000a00000001000000031393da50f88ab55d506ec30fb52255d500000008c0ec4a7fc6c457a5cd85b753dd9fda9d589f58f69c50dc847331f5326e83704b37f5425a534317b9033166932b669f613d2027671817bd07837f84c279163035b6006f3de2a1234e5d160cb32ddffed140000005e85cb04384c432bc08fe1a3caebe72108911bdb"
                  }
}
```
The scheduled task then runs Submit-Renewal daily (runs under the system account in scheduler)
If the certificate needs to be renewed.
This renews the certificate correctly.

However

The plugin args now show
```
{
    "DMEKey":  "xx-yyy-zzz-aaa-bbb",
    "DMESecret":  null
}
```
Subsequent renewals fail.

I am sure I used the same scripts before for a couple of years without issue.

I realise native Secrets storage stores secret in the context of the machine and the user but this used to work.

I looked at the new SecretsStorage but is seems too complex for my scenario.  I would be happy to store the API keys in plain text and rely on OS file permissions to protect this.  But I see this functionality will be removed.

**Comment by rmbolger** [comment]
Hey @mikes-gh. The way the module encrypts SecureString data in the config by default is tied to the specific user who created the original order. So the SYSTEM account being different user than the admin user means it won't be able to decrypt and use the secret.

While the SecretManagement support is one way to workaround this. There's another way that doesn't have any external dependencies or setup. The [guide](https://poshac.me/docs/v4/Guides/Using-an-Alternate-Config-Location/) on using an alternate config location talks a bit about it and the end. Try this from the admin account context to enable the alternative method of plugin encryption.

```powershell
Set-PAAccount -UseAltPluginEncryption
```

If the null DMESecret value got saved to the config, you may also need to re-associate the correct value in your config like this:

```powershell
$pArgs = @{
    DMEKey = 'xx-yyy-zzz-aaa-bbb'
    DMESecret = (Read-Host 'secret' -AsSecureString)
}
Set-PAOrder -Plugin DMEasy -PluginArgs $pArgs
```

**Comment by mikes-gh** [comment]
@rmbolger Hi Ryan. thanks I changed my script to use `-UseAltPluginEncryption` and it now works.  The bit I missed was the `-AsSecureString` in the read host.  

I am currently using
```
$pluginArgs = @{
    DMEKey = 'xxx.yyy.zz'
    DMESecret = ConvertTo-SecureString 'xxx-yyyy-zzz' -AsPlainText -Force
}
```

and then using
```
Set-PAAccount -UseAltPluginEncryption
```
Which I believe converts the DPAPI SecureString if the current user is the one that set the secure string?

Is there a way to set the secret without using read host.
I realise it's not a good idea to have  secrets in scripts but I am happy with this compromise in this case.

**Comment by rmbolger** [comment]
> Is there a way to set the secret without using read host.

It looks like you already found it with the `ConvertTo-SecureString 'blah' -AsPlainText -Force`.

**Comment by rmbolger** [comment]
> Or is it it only when the secure string gets persisted

You got it. DPAPI (and the AES/SecretManagement alternatives) only comes into play for serializing the secure variables. Essentially when doing `ConvertFrom-SecureString $mySecureString` which the module does under the hood when it's saving the variables to disk.

**Comment by mikes-gh** [comment]
Great thanks for taking the time to explain.  I am clear now.

**Comment by mikes-gh** [comment]
```$env:POSHACME_HOME = $poshACMEPath
$pluginArgs = @{
    DMEKey = 'xx-yyy-zz'
    DMESecret = ConvertTo-SecureString 'aa-bb-cc' -AsPlainText -Force
}
Set-PAServer LE_PROD
# issue a cert
$cert = New-PACertificate "$env:ComputerName.somedomain.com" -AcceptTOS -Contact support@somedomain.com -DnsPlugin DMEasy -PluginArgs $pluginArgs -Force
Install-PACertificate $cert
Set-PAAccount -UseAltPluginEncryption
```
Since `New-PACertificate` doesn't support `-UseAltPluginEncryption` is the above the best way?

**Comment by mikes-gh** [comment]
Or maybe
```
```$env:POSHACME_HOME = $poshACMEPath
$pluginArgs = @{
    DMEKey = 'xx-yyy-zz'
    DMESecret = ConvertTo-SecureString 'aa-bb-cc' -AsPlainText -Force
}
Set-PAServer LE_PROD
Set-PAAccount -UseAltPluginEncryption
# issue a cert
$cert = New-PACertificate "$env:ComputerName.somedomain.com" -AcceptTOS -Contact support@somedomain.com -DnsPlugin DMEasy -PluginArgs $pluginArgs -Force
Install-PACertificate $cert

```
is better (note set UseAltPluginEncryption change of order

**Comment by rmbolger** [comment]
Technically, the calls to `Set-PAServer` and `Set-PAAccount` are only necessary once unless another process changes the server or account between runs of your script. 

If you run this on a system that has no existing Posh-ACME config, `Set-PAAccount` won't work until after the `New-PACertificate` call because it does a `New-PAAccount` for you under the hood. But you could change that `Set-PAAccount` call to something like this to conditionally create the account if it doesn't already exist.

```powershell
if (-not(Get-PAAccount)) { New-PAAccount -AcceptTOS -Contact support@somedomain.com -UseAltPluginEncryption }
```

Then you could also simplify the `New-PACertificate` command by removing `-AcceptTOS -Contact support@somedomain.com` since AcceptTOS is only needed to create the account and Contact is already associated with the account.

**Comment by rmbolger** [comment]
Changing the default wouldn't be a breaking change. But technically speaking, it's marginally less secure because they AES key is stored (obfuscated) with the config rather than somewhere deeper and presumably more secure wherever DPAPI gets its key. And I'd rather have the defaults be more secure. However, I could potentially make it the default on non-Windows OSes where DPAPI doesn't exist and the .NET default workaround is arguably worse than my local AES key method.
