### ISSUE TITLE
Adding/Changing an E-Mail on an already created Account

### ISSUE THREAD

**Issue by dimmelsw** [rmbolger/Posh-ACME#443]
Hi, quick question.
Got my setup working, automatic renewal via powershell and task scheduler.
Everything works, I just didn't add a contact e-mail-address to my initial creation of an account via `NEW-PAACertificate`.

Can I add an e-mail-address to my already created account?

**Comment by rmbolger** [comment]
Yes, you can add/change the email address(es) associated with an account at any time using `Set-PAAccount` like this:

```powershell
Set-PAAccount -Contact me@example.com
```

Technically, the protocol supports multiple addresses as well so you can add more than one in an array if you need to. Though support varies depending on the ACME server. Let's Encrypt definitely supports it though.

**Comment by dimmelsw** [comment]
OK, thanks.
I've set the e-mail. :)
