### ISSUE TITLE
Documentation Site is Down with Invalid Certificates

### ISSUE THREAD

**Issue by SuperJC710e** [rmbolger/Posh-ACME#444]
First, thanks for the great tools! 😄 

Unfortunately, the documentation site is down, with, of all things, an SSL certificate error... 😮 🤣  I've heard there are some great tools out there to help with automating certificate renewal and installation! 😆 

```
Error 526 Ray ID: 723994e34ddd2ba7 • 2022-06-30 20:16:46 UTC

Invalid SSL certificate

You
Browser
Working

Chicago
Cloudflare
Working

poshac.me
Host
Error

What happened?

The origin web server does not have a valid SSL certificate.

What can I do?

If you're a visitor of this website:

Please try again in a few minutes.

If you're the owner of this website:

The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/200721975)
```

**Comment by rmbolger** [comment]
We’ll that’s certainly embarrassing. 😂 Should be fixed now. Thanks for the heads up.

**Comment by SuperJC710e** [comment]
> We’ll that’s certainly embarrassing. 😂 Should be fixed now. Thanks for the heads up.

It happens to the best of us at times! I had just refreshed and was typing a message that it was working when I saw your message pop up! Great timing!

Thanks for the tools, and thanks for the quick fixup! 😄 👍
