### ISSUE TITLE
How can I make the Domeneshop plugin output REST API data?

### ISSUE THREAD

**Issue by Tarjei-stavanger** [rmbolger/Posh-ACME#454]
It would be nice if Posh-ACME allowed the results from invoking Invoke-DomeneshopAPI to be displayed when  the -Verbose switch is turned on.

If it is some sort of error code, it is very much of interest. And it is less fun to modify the code instead of just adding the -Verbose Switch.

I would not mind if there was a -VeryVerbose switch which allowed the display of the return information.

I'll even agree to the return information displayed using a hex dump.

**Comment by rmbolger** [comment]
Hi @Tarjei-stavanger, thanks for reaching out. Normally, if you're looking for "VeryVerbose" output, you would enable Debug output in addition to Verbose. However, using the `-Debug` switch on a command in PowerShell has the unfortunate side effect of prompting for confirmation on every line in a function. Instead, you can set the [$DebugPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables#debugpreference) variable before running your command like this:

```powershell
$DebugPreference = 'Continue'
```

This will make the function show its debug output without the confirmation prompts.

However, the original author of the Domeneshop plugin didn't choose to make the raw REST API data available via Debug messages. So I took the liberty of updating the plugin to do so in commit 495a2e3. I also fixed a bug I found when using CNAME aliases pointing to a domain apex. Both changes should go live in the next release. But you can also grab the updated copy of the [plugin file](https://github.com/rmbolger/Posh-ACME/blob/main/Posh-ACME/Plugins/Domeneshop.ps1) from Github and use it until then by overwriting your existing copy.

**Comment by Tarjei-stavanger** [comment]
Thanks for the reply.

I have tried using the -Debug switch, but it does not go according to plan. I assume that the $DebugPreference variable is somehow is overridden in the code because I get prompted all the time.

So I created a test file : 
    $DebugPreference;
    Write-Debug -Message "Hello, World"
    Write-Debug -Message "Hello, World"
    Write-Debug -Message "Hello, World" -Debug

This give me 3 debug "Hello, World" and one prompt as seen below.

![image](https://user-images.githubusercontent.com/82510602/188556074-fc2fd288-91f2-4db8-880d-f6dc8bd07ac9.png)

**Comment by Tarjei-stavanger** [comment]
I misunderstood the **-Debug** switch vs just setting the **$DebugPreference** variable.

**Comment by rmbolger** [comment]
Generally speaking, the Domeneshop API does return JSON. But PowerShell's `Invoke-RestMethod` converts it into a custom object automatically. Converting it back to JSON for debug output seems appropriate. But perhaps the error you're getting is not JSON. Can you post the output with the error so we can review what might be going wrong?

In my brief testing, the plugin is working for my single-domain account. But it's possible there are some assumptions being made in the code that break for accounts with more than one domain.

> You may also want to ensure that you are using a more recent version of TLS.
> [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;

This is already handled by the base module when it detects PowerShell 5.1 is in use.

**Comment by rmbolger** [comment]
The changes are now live in 4.15.1

**Comment by Tarjei-stavanger** [comment]
Sorry that I'm late with my comments. I'm not the worlds greatest PowerShell programmer, but probably not the worst either.

TLS appears to not be handled in the base module. Or there is some weird things happening. I have to set the TLS version to 1.2 on the command line. I have a PowerShell test script which also sets it, but that does not help. Copying that line and pasting it to the command line works. Late Friday, setting TLS version behaved weird. I had to run my test script twice to make it work after I had set it. That is something I still have to do.

For Debug-Print to display only a reconstituted JSON message is definitely wrong. That is because it gives no hint about what is really returned from  `Invoke-RestMethod`. With both the JSON and the return from `Invoke-RestMethod`, I can see what is wrong. In this case it is `$_.services.dns` which is false in the  JSON file while `registrar` is true. I have complained about this breach of what is documented to Domeneshop.

Domeneshop API documentation : [](https://api.domeneshop.no/docs/)

Here is a partial screenshot. It shows what is returned. And I know instantly what I need to do to access the information. JSONPlaceholder site is a free API test site. Using it really enlightened me.

![image](https://user-images.githubusercontent.com/82510602/189582322-c910e72a-3170-4662-8bb6-dd3bb0270876.png)

I finally managed to use write-Debug to display what  `Invoke-RestMethod` returns.
```
DEBUG: Invoke-DomeneshopAPI Response :
DEBUG: @{domain=stavanger.kommune.no; expiry_date=2023-04-23; id=12345678; nameservers=System.Object[];
registrant=STAVANGER KOMMUNE; renew=True; services=; status=active; transferred_date=2011-06-27}
DEBUG:  Invoke-DomeneshopAPI Rest Response :
DEBUG: Response: {
    "domain":  "stavanger.kommune.no",
    "expiry_date":  "2023-04-23",
    "id":  12345678,
    "nameservers":  [
                        "ns1-02.azure-dns.com",
                        "ns2-02.azure-dns.net",
                        "ns3-02.azure-dns.org",
                        "ns4-02.azure-dns.info"
                    ],
    "registrant":  "STAVANGER KOMMUNE",
    "renew":  true,
    "services":  {
                     "dns":  false,
                     "email":  false,
                     "registrar":  true,
                     "webhotel":  "none"
                 },
    "status":  "active",
    "transferred_date":  "2011-06-27"
}
```
(some data changed)

```
    Write-Debug "Invoke-DomeneshopAPI Response :"
    $response | Write-Debug
	Write-Debug " Invoke-DomeneshopAPI Rest Response :"
	Write-Debug "Response: $($response | ConvertTo-Json)"
```
I needed both to make sense of what is going on.

There is still the issue of searching the kommune.no domain for subdomains. Which I find weird.

**Comment by Tarjei-stavanger** [comment]
I get the same results as you are getting from [Net.ServicePointManager]::SecurityProtocol. I wonder if order is significant and it will try TLS 1.0 first and fail.

I have disabled TLS 1.0 and 1.1 on my PC. I suspect that I don't have TLS 1.3.

You are right about DomeneShop not being our DNS provider.

`Invoke-RestMethod `might return an array. It is one thing that the plugin gets wrong. It is looping through the domains in the query, not the results from the query. It tries both stavanger.kommune.no and kommune.no. The latter results in a array with 5 elements . I can see this because Write-Debug writes each array member as a separate string prefixed with 'DEBUG:'.
