### ISSUE TITLE
Set-PAServer does not use proxy settings of system

### ISSUE THREAD

**Issue by coldflame-js** [rmbolger/Posh-ACME#458]
Dear Guys

Is there currently no support to use the system proxy settings?

The error message says (in English) "the connection to the remote server cannot be esablished".

```
PS C:\Users\xxx> Set-PAServer LE_STAGE
Set-PAServer : Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
In Zeile:1 Zeichen:1
+ Set-PAServer LE_STAGE
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Set-PAServer], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Set-PAServer

```
In Wireshark I see, that the connection is tried to be made directly to the server instead of to the proxy.

![2022-10-12 17_13_07-Aufzeichnen von Ethernet 3](https://user-images.githubusercontent.com/93835070/195381343-1c345b01-3184-4f1c-9ce4-81cf5f1d84c9.png)

We're using a proxy pac file but i tried also to fix the proxy manually.

```
PS C:\Users\xxxx> netsh winhttp set proxy "proxy.xxxxx:8080"

Aktuelle WinHTTP-Proxyeinstellungen:

    Proxyserver     :  proxy.xxxxxx:8080
    Umgehungsliste  :  (keine)

```
Sincerely jonas

**Comment by rmbolger** [comment]
Hi @coldflame-js. This was already brought up by another user in issue #396. Unfortunately, dealing with proxy services gracefully across different PowerShell versions is kind of a mess and additionally difficult for me to deal with as I have no proxy environments to test in. I'm going to close this issue but we can continue the discussion in the other one.
