### ISSUE TITLE
Install-PACertificate only possible if PFX is provided by CA

### ISSUE THREAD

**Issue by AkiraFFM** [rmbolger/Posh-ACME#461]
Hello,

our CA is not providing the PFXFile and PFXFullchain, so install to the Windows certificate store will fail.
Is it possible to implement an installation of the certificate only with the Fullchain.cer File and without the PFXFile and PFXFullchain or
make the PFX not mandatory?

Best regards,
Stefan

**Comment by webprofusion-chrisc** [comment]
CAs don't generally provide the PFX and certainly not in ACME, instead Posh-ACME builds that for you. 

The CA provides a public key certificate (in PEM format) which corresponds to the private key you hold on your machine and they derive that from CSR (certificate signing request) which is submitted to them as part of the certificate request process. This certificate is often then converted to a PFX file, which is a container format (also called p12 or pkcs12) including your public certificate, intermediate certificates from the CA and your private key (optionally protected by a password).

So if you have a .cer file for example from your CA and you also have the corresponding private key and any required intermediate certificates then you can use things like openssl to cretae your pfx file. For example: https://www.oxabox.com/how-to-create-a-pfx-certificate-from-a-cer-certificate/

Who is your CA and what exactly are you trying to do?

Hi @rmbolger just an aside to say the docs are redirecting to :8080 currently, e.g. if you go to https://poshac.me/docs/v4/Tutorial it redirects to https://poshac.me:8080/docs/v4/Tutorial/ then fails to connect.

**Comment by AkiraFFM** [comment]
@webprofusion-chrisc Thanks. I found another solution.
Import-Certificate -FilePath (Get-PACertificate).certfile -CertStoreLocation Cert:\LocalMachine\My

**Comment by rmbolger** [comment]
Thanks for the heads up on the docs, @webprofusion-chrisc. I think I've got a misconfiguration on my LB that's making that happen with any URL that doesn't have the trailing slash. I'll hopefully get it fixed later today.
