### ISSUE TITLE
Include Unicode support into ACME CA Comparison

### ISSUE THREAD

**Issue by mehov** [rmbolger/Posh-ACME#466]
Turns out, Google Cloud Certificate Manager [does not support UTF-8 domains](https://cloud.google.com/blog/products/identity-security/automate-public-certificate-lifecycle-management-via--acme-client-api): 

> **Do you issue certificates for punycode encoded Unicode domain names?**
> Not at this time

[Also](https://cloud.google.com/certificate-manager/docs/public-ca#limitations):

> **Limitations of Certificate Manager Public CA**
> This release of Certificate Manager Public CA does not support punycode domains.

The ACME CA Comparison page (https://poshac.me/docs/v4/Guides/ACME-CA-Comparison/, https://github.com/rmbolger/Posh-ACME/blob/main/docs/Guides/ACME-CA-Comparison.md) has no mention of that, but it may be important to someone.

**Comment by rmbolger** [comment]
Hi @mehov. Excellent suggestion. I'll test the rest of the CAs on the list and get it added as soon as I have time.

**Comment by rmbolger** [comment]
I just realized there is actually a note below the first table mentioning that Google doesn't support punycode/IDN domains. But I like the idea of just making it a column in the table.

**Comment by mehov** [comment]
Thank you! 🙂

**Comment by rmbolger** [comment]
This is now live.
