### ISSUE TITLE
'server' parameter for RFC2136 and nsupdate

### ISSUE THREAD

**Issue by soa-jrt** [rmbolger/Posh-ACME#468]
The RFC2136 plugin requires $DDNSNameserver be set. That value is mapped to a 'server' instruction which is piped to the nsupdate command. nsupdate does not require the 'server' instruction to perform its work, and in some cases providing it is counter productive. This parameter should be optional.

Use-case: The zone's primary server (as defined in the SOA record) changes, but the old value was hard coded into the scheduled jobs. Updates will now probably fail. We should have the option of not providing the server-name, and thereby using whatever is published in the SOA record.

**Comment by rmbolger** [comment]
Hi @soa-jrt . Thanks for reaching out. This sounds reasonable to me. I had no idea the server command was optional but I suppose it makes sense. I've been swamped with real work lately, so it might take me a bit to look into this.

**Comment by rmbolger** [comment]
Got the change into the main branch if you want to test it. This will go out in the next release.

**Comment by rmbolger** [comment]
This is now live in 4.17.0
