### ISSUE TITLE
You cannot call a method on a null-valued expression - WebSelfHost

### ISSUE THREAD

**Issue by rfranks-securenet** [rmbolger/Posh-ACME#474]
I'm trying to issue a certificate using the webselfhost plugin, and I'm getting the following error message:

```
DEBUG: HttpListener started with 120 second timeout
VERBOSE: Stopping HttpListener
Submit-ChallengeValidation : You cannot call a method on a null-valued expression.
At C:\Users\ansible\Documents\WindowsPowerShell\Modules\Posh-ACME\Public\New-PACertificate.ps1:252 char:9
+         Submit-ChallengeValidation
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Submit-ChallengeValidation], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Submit-ChallengeValidation
```

I successfully managed to use the manual DNS entry plugin to issue a cert, however I need to use HTTP-01 validation.

**Comment by rmbolger** [comment]
Hi @rfranks-securenet, thanks for reaching out. Using the WebSelfHost plugin on Windows may require some pre-configuration depending on whether the PowerShell session running Posh-ACME has elevated/admin permissions or not. If not, did you follow the steps in the [plugin usage guide](https://poshac.me/docs/v4/Plugins/WebSelfHost/) to pre-configure the http.sys urlacl with netsh?

If everything sounds like it should be right with the http.sys urlacl, can you make another attempt with debug output turned on and post the results? The easiest way to enable debug output is to put `$DebugPreference = 'Continue'` before your call to New-PACertificate. It can be set back to the default of `SilentlyContinue` afterwards.
