### ISSUE TITLE
Plugin Azure, Add-DnsTxtAzure is not using the AZUseIMDS switch

### ISSUE THREAD

**Issue by mithrandyr** [rmbolger/Posh-ACME#48]
```powershell
$azParams = @{AZSubscriptionId = 'xxxx-xxxxxx-xxx-xx'; AZUseIMDS=$true}
New-PACertificate somedomain -DnsPlugin Azure -PluginArgs $azParams -verbose
```

gives me this output

> VERBOSE: Using directory https://acme-v02.api.letsencrypt.org/directory
VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/acct/36862242 with -1-byte payload
VERBOSE: received 333-byte response of content type application/json
VERBOSE: Using account 36862242
VERBOSE: Creating a new order for somedomain
VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/new-order with -1-byte payload
VERBOSE: received 369-byte response of content type application/json
VERBOSE: Publishing DNS challenge for somedomain
cmdlet Add-DnsTxtAzure at command pipeline position 1
Supply values for the following parameters:
AZTenantId:

Why is it prompting me for AZTenantId -- when I passed in "AZUseIMDS"?

**Comment by rmbolger** [comment]
That's a good question. The only thing I can think of is that you previously used one of the other Azure auth types from this account and when the module merges the supplied `$azParams` with the previously saved params, it's confusing PowerShell's parameter binding. But I'm having trouble duplicating the circumstances. Does the same thing happen if you just try to publish an arbitrary TXT record? Try this:

```powershell
# turn on debug logging
$DebugPreference = 'Continue'

Publish-DnsChallenge somedomain (Get-PAAccount) faketext Azure $azParams -Verbose
```

If the same thing happens, can you try creating a new ACME account (`New-PAAccount -AcceptTOS`) and try the `Publish-DnsChallenge` command again? The new account won't have any previous plugin param data saved to it and should verify whether that's the core issue or not.

Also, what platform is this on? Can you post your `$PSVersionTable` output?

**Comment by mithrandyr** [comment]
@rmbolger Sorry for the delay in getting back to you -- I discovered what the problem is.  I was using a windows server 2016 core image (Azure VM)… which doesn't come with .Net 4.7 (which you clearly state is required for the module to work).  So you can mark this as closed, not an issue.  Thanks for the fast response!
