### ISSUE TITLE
Hetzner API plugin runs into issues when you have more than 100 DNS zones in your account

### ISSUE THREAD

**Issue by Deutschi** [rmbolger/Posh-ACME#481]
I ran into an issue with where some domains would not work with the Hetzner API plugin. The function "Find-HetznerZone" in the plugin wants to load all zones and iterate through them to find the best/closest entry. However, the Hetzner API limits the total amount of results (zones) to 100 (per page) and our Hetzner account has more than 100 entries. This is the reason for my problems.

My suggestion would be to not try to load all zones, but instead make use of the "name" parameter. This should also scale well for people who have even more DNS zones in their Hetzner account.

1) move this
```
# first, get all Zones, Zone to get is identified by 'ZoneID'.
try {
    $response = Invoke-RestMethod -Uri "https://dns.hetzner.com/api/v1/zones" `
        @RestParameters @Script:UseBasic -EA Stop
} catch { throw }
```

2) and put it within the iteration, using the "name" parameter
```
$pieces = $RecordName.Split('.')
  for ($i=0; $i -lt ($pieces.Count-1); $i++) {
    $zoneTest = $pieces[$i..($pieces.Count-1)] -join '.'
    Write-Debug "Checking $zoneTest"

    ### change start
    try {
      $response = Invoke-RestMethod -Uri "https://dns.hetzner.com/api/v1/zones?name=$zoneTest" `
        @RestParameters @Script:UseBasic -EA Stop
    }
    catch {
      Write-Debug $_.Exception.Message
      continue
    }
    ### change end
				
    $zone = $response.zones | Select-Object id,name |
      Where-Object { $_.name -eq $zoneTest }

    if ($zone) {
      Write-Debug "Zone $zoneTest found."
      $script:HetznerRecordZones.$RecordName = $zone
      return $zone
    } else {
      Write-Debug "Zone $zoneTest does not exist ..."
    }
}
```

**Disclaimer:** 
My experience with PowerShell is not the best. I wanted to fully debug this and make it robust, but I just can't use the plugin by myself without running into weird errors like "A positional parameter cannot be found that accepts argument '$null'" on the Invoke-RestMethod.

This plugin is used within a program called "Certify" (from Certify The Web) and my changes seem to work. However, due to the lack of experience I don't want to make a pull request but instead provide a possible solution this way. I hope it is still ok.

**Comment by rmbolger** [comment]
I've pushed a change to the main branch that should fix the problem. It's working for my small account. But can you verify it works for you as well, @Deutschi?

**Comment by Deutschi** [comment]
I tried the update, there were no issues. Thank you very much for your work. 👍
