### ISSUE TITLE
Account key rollover not working with SSL.com

### ISSUE THREAD

**Issue by okruga** [rmbolger/Posh-ACME#483]
Hi!
It looks like `-keyRollover` doesn't work for EAB accounts.
```
Set-PAServer -DirectoryUrl SSLCOM_RSA
openssl genrsa 4096 -out acc.key
New-PAAccount -ExtAcctKID $eabKID -ExtAcctHMACKey $eabHMAC -Contact 'some@mail.com' -AcceptTOS -KeyFile 'acc.key'
openssl genrsa 4096 -out acc-new.key
set-paaccount -ID <Id of created account> -keyRollover -KeyFile 'acc-new.key' -debug
```
Error: `{"message":"Missing Authentication Token"}`

But it works for accounts without EAB.

Or I'm doing something wrong?
thanks in advance.

**Comment by rmbolger** [comment]
Unfortunately, this is a known problem with the SSL.com CA specifically. I've documented the various spec features supported by the major free ACME CAs here:
https://poshac.me/docs/v4/Guides/ACME-CA-Comparison/#acme-spec-and-feature-support

The module is requesting key rollover properly according to [RFC 8555 section 7.3.5](https://www.rfc-editor.org/rfc/rfc8555.html#section-7.3.5). But SSL.com (and ZeroSSL) both don't support it for some reason. The EAB values aren't involved in the transaction. As an example, key rollover using Google's CA which also uses EABs does work properly.

**Comment by okruga** [comment]
thanks @rmbolger for the shift response.
