### ISSUE TITLE
trying to create a SANs cert  with New-PACertificate

### ISSUE THREAD

**Issue by BurntSingedToast** [rmbolger/Posh-ACME#484]
So  i'm able to create a new cert with a single domain, but when i try to create a SANs cert i get:

contains incompatible characters. Please use only A-Z, a-z, 0-9, or any of '-._!'

i know for a fact that i'm not using any incompatable characters. going to letsencrypt stating server and DMEasy plugin

**Comment by rmbolger** [comment]
Hi @BurntSingedToast. Can you post the command you're using that causes the error?

**Comment by BurntSingedToast** [comment]
param (
    [string]$cert,
    $pass
)
$Args = @{
    DMEKey = "$XXX"
    DMESecret = (convertto-securestring "$($XXX)" -AsPlainText -Force)
}
Set-PAServer LE_STAGE
$password = (convertto-securestring $Pass -AsPlainText -Force)
try {
New-PACertificate -domain $cert -PfxPassSecure $password -AcceptTOS -Plugin DMEasy -PluginArgs $Args -Verbose
} catch {
    Write-Output $_.Exception
}

**Comment by rmbolger** [comment]
For your SAN cert, what is the value in the `$cert` variable? The `-Domain` parameter expects an array of strings. So if you passed a single string with domain names comma delimited in it, that would be the problem.

So whatever is calling your function would need to call it like:
```powershell
myfunc -cert 'example.com','example.org'
```
and not
```powershell
myfunc -cert 'example.com,example.org'
```

**Comment by BurntSingedToast** [comment]
i've tested successfully with testing.something-domain.com (works) and i've done testing.something-domain.com,1testing.something-domain.com (doesn't work). i've done it with and without the -domain.

**Comment by BurntSingedToast** [comment]
i've also done it with 'testing.something-domain.com','1testing.something-domain.com' (not working)

**Comment by rmbolger** [comment]
I think in order for `'testing.something-domain.com','1testing.something-domain.com'` to work with your script, you'd need to change the param block so the `$cert` param takes a string array like this:

```powershell
param (
[string[]]$cert,
$pass
)
```

**Comment by rmbolger** [comment]
Here's a demonstration of the difference:
```powershell
> function test { param([string]$cert) $cert }
> test 'foo','bar'
foo bar
> function test { param([string[]]$cert) $cert }
> test 'foo','bar'
foo
bar
```

In the first result, PowerShell is joining the two string arguments together with a space because it's trying to helpfully convert the string array into a single string. In the second result, it recognizes the string array and outputs each element separately.

**Comment by BurntSingedToast** [comment]
i'll give it a try

**Comment by BurntSingedToast** [comment]
the life of scripts calling scripts.  i was feeding the input as a single string.  once i broke up the calling script to send an array of strings instead of a single string, it works.  thank you.
