### ISSUE TITLE
Plugin for  Zoneedit DNS Provider

### ISSUE THREAD

**Issue by aboulang** [rmbolger/Posh-ACME#495]
Hi,

The DNS provider I use for several domains is Zoneedit. https://www.zoneedit.com/ Can you do a plugin for that provider? 

Kind regards,
Albert Boulanger

**Comment by rmbolger** [comment]
Hi @aboulang, thanks for reaching out. Last I checked which was a few years ago, ZoneEdit didn't have an API capable of making TXT record changes. But I did a quick web search and it [looks like](https://forum.zoneedit.com/threads/automating-changes-of-txt-records-in-dns.7394/page-2) they may have implemented some sort of DynDNS compatible API that might work. It will take some time to look into though.

I'd be curious if it's compatible with the plugin @jbrunink is working on in #494.

**Comment by rmbolger** [comment]
Hey @aboulang, I just added a new branch with the commit linked above that has a working ZoneEdit plugin. I still need to write the guide and some other stuff to get it ready to merge. But you should be able to grab the file and test it against your stuff.

Here's a quick start on using it. You need to generate an authentication token for the zone you're creating the record in. Then, try publishing a record like this:

```powershell
$pArgs = @{
    ZEUsername = 'myusername'
    ZEDynCredential = (Get-Credential 'example.com')
}
New-PACertificate example.com -Plugin ZoneEdit -PluginArgs $pArgs -Verbose
```

If you need to get a cert that contains names from multiple different zones, you need to provide each zone's authentication token in your plugin parameters like this:

```powershell
$pArgs = @{
    ZEUsername = 'myusername'
    ZEDynCredential = @(
        (Get-Credential 'example.com')
        (Get-Credential 'example.net')
    )
}
```

**Comment by rmbolger** [comment]
This is now live in 4.19.0.

**Comment by aboulang** [comment]
> Hey @aboulang, I just added a new branch with the commit linked above that has a working ZoneEdit plugin. 

Thanks @rmbolger !
