### ISSUE TITLE
GoDaddy plugin breaks with records in sub-domains

### ISSUE THREAD

**Issue by davehope** [rmbolger/Posh-ACME#50]
I am attempting to issue a certificate for acmetest.int.hope.mx , using the GoDaddy plugin.  I'm doing this as follows:

` New-PACertificate 'acmetest.int.hope.mx' -AcceptTOS -Contact someone@someone.com -DnsPlugin GoDaddy -PluginArgs @{GDKey='xxx'; GDSecret='xxx'} -Debug`

This results in an error:

```
.. trimmed before here ..
DEBUG: Calling GoDaddy plugin to add _acme-challenge.acmetest.int.hope.mx TXT with value NH-jufRQ57OPCLCgTTSHPpu8P1s80NswgATY8ozKt7U
DEBUG: Checking acmetest.int.hope.mx
DEBUG: Checking int.hope.mx
DEBUG: Checking hope.mx
DEBUG: ""

Invoke-RestMethod : {"code":"INACTIVE_DOMAIN","message":"The given domain is not eligible to have its nameservers changed"}
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.4.0\DnsPlugins\GoDaddy.ps1:125 char:17
+     $response = Invoke-RestMethod -Uri "$apiRoot/$zone/records" `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```
PR incoming.

**Comment by rmbolger** [comment]
Good catch and thanks for the PR as well! I'll follow up there.

**Comment by Dule011** [comment]
fix seems to be needed in Add-DnsTxtGoDaddy and Remove-DnsTxtGoDaddy functions. Replacing lines 25 and 107: $name = ($RecordName -split "\.")[0]
with: $name = $RecordName.Split(".")[0..($RecordName.Split(".").count - 3)] -join "."
worked for me.

**Comment by rmbolger** [comment]
@Dule011 I think this is more or less what @davehope's pull request #51 does except instead of making `$name` the first X pieces of the FQDN, it removes the zone name returned by `Find-GDZone`.

**Comment by Dule011** [comment]
yup, that's about right. i like @davehope solution better. just completed the test on my side and can confirm that it works. thank you all!

**Comment by rmbolger** [comment]
Merged and should go out in the next release. I'll wait until we get the rest of this GoDaddy stuff sorted out.
