### ISSUE TITLE
Add -CsrString parameter to New-PACertificate

### ISSUE THREAD

**Issue by ziptx** [rmbolger/Posh-ACME#503]
Fantastic product.  Thank you for sharing this with the world.   

The certificate work we are doing is completed through API calls.   So, the CSR is actually already loaded and available in a string variable.   The current version requires a path to a file for loading the CSR; hence the CSR needs to be written to disk vs being passed as a string.   The code already exists to parse the CSR into the necessary data elements, we just need the mechanism to drop the CSR string into the function vs a file path.

**Comment by rmbolger** [comment]
Hey @ziptx, thanks for reaching out. This should definitely be doable. I'll try to get it into the next release.

**Comment by rmbolger** [comment]
Hey @ziptx, have a look at PR #506 and let me know if that will work for your use-case. I'd also love it if you could grab the source from the `allow-csrstring` branch and test it. I may also roll it into the main branch over the next few days because it seems to be fairly solid so far.

**Comment by rmbolger** [comment]
This is now live in 4.19.0.

**Comment by ziptx** [comment]
Much appreciated!
