### ISSUE TITLE
possible documentation issue with Tutorial  

### ISSUE THREAD

**Issue by AndyDeck** [rmbolger/Posh-ACME#504]
Hi,

I think I'm seeing an issue with the tutorial's description of how to handle Task Scheduler/Cron renewals. The sample code at https://poshac.me/docs/v4/Tutorial/#task-scheduler-cron for handling multiple certificates contains code like this:
```
Submit-Renewal -AllOrders | ForEach-Object {
    $cert = $_
    if ($cert.MainDomain -eq 'example.com') {
        # deploy for example.com
    } elseif ($cert.MainDomain -eq 'example.net') {
        # deploy for example.com
    } else {
        # deploy for everything else
    }
}
```
using `$cert.MainDomain` - but the functional documentation at https://poshac.me/docs/v4/Functions/Submit-Renewal/#outputs says that `Submit-Renewal` returns a `PoshACME.PACertificate`, which does not seem to have a `MainDomain` parameter.

Should those references instead be using something like `$cert.Subject -eq 'CN=example.com'`?

I noticed all this when my renewals code did renew the certs but did not trigger the deployment script. Unfortunately I only have this code deployed on one device right now, and it won't trigger a renewal for validation for another 60 days or so.

Thanks.

**Comment by rmbolger** [comment]
Whoops. You might be right. I'll review that section and make the appropriate changes. Thanks for the heads up.

**Comment by rmbolger** [comment]
Tutorial has been updated. Thanks again.
