### ISSUE TITLE
create certificates with non public TLDs

### ISSUE THREAD

**Issue by 100110010111** [rmbolger/Posh-ACME#505]
It seems its not possible to create certificates for domains that have a non-public TLD. This means corporate networks that use .local or .int cant use posh-acme. Since registration authorities are a thing, its now possible to answer challenges that for devices that only live inside a private network. Please add support for non public TLDs please!

**Comment by rmbolger** [comment]
Hi @100110010111, the ability to get certs for non-public TLDs is entirely dependent on the ACME server you connect to. Publicly trusted CAs like Let's Encrypt, Google, etc. are not allowed to issue certs for anything except ICANN recognized domains. Posh-ACME is just showing you a message passed back from your chosen ACME server.

But you can easily use it for internal, non-public domains if you have a privately hosted internal CA that supports ACME. You'd just need to point Posh-ACME to the correct directory endpoint like this:

```powershell
Set-PAServer -DirectoryUrl 'https://myca.corp/directory'
```

**Comment by 100110010111** [comment]
Interesting, thanks. I am using smallstep with a registration authority, ill reach out to them thanks. I know they support this

**Comment by rmbolger** [comment]
This might help:
https://smallstep.com/docs/tutorials/acme-protocol-acme-clients/
