### ISSUE TITLE
Condition based on result of Submit-Renewal or Install-PACertificate

### ISSUE THREAD

**Issue by EdificomSA** [rmbolger/Posh-ACME#514]
Hello,

I'm trying to write a Powershell script that does stuff if the renewal/install actually went through (not `is not recommended for renewal yet`)

Obviously the following doesn't work as `Install-PACertificate` doesn't have any output (or is it ?)
```
$renewal = Submit-Renewal -AllAccounts -Verbose -PluginArgs $pArgs | Install-PACertificate
if ($renewal) {
```

Is there a way to check if the renewal&install "worked", or would it be possible to add a boolean output to `Install-PACertificate` ?

**Comment by rmbolger** [comment]
Hi @EdificomSA, thanks for reaching out. The `Submit-Renewal` function will return `PACertificate` objects (the same thing returned by `New-PACertificate` and `Get-PACertificate`) for any certs that were renewed successfully. So anything that is missing from the output either had a problem or wasn't scheduled to renew yet.

As you noticed, the `Install-PACertificate` function doesn't return anything and is effectively swallowing the output from `Submit-Renewal` in your current script. While I might be able to add something like a `-PassThru` switch to `Install-PACertificate`, there are other ways you could accomplish the same task. There's a section in the [tutorial](https://poshac.me/docs/v4/Tutorial/#task-scheduler-cron) with some sample code for renewal logic that might work better.

Here's how I might modify your existing code:

```powershell
Submit-Renewal -AllOrders | ForEach-Object {
    # every item in this loop is a cert that was renewed successfully
    $cert = $_
    $cert | Install-PACertificate
    if ('example.com' -in $cert.AllSANs) {
        # deploy for example.com
    } elseif ('example.net' -in $cert.AllSANs) {
        # deploy for example.net
    } else {
        # deploy for everything else
    }
}
```

You could also avoid needing to call `Install-PACertificate` explicitly by adding the Install flag to your existing orders. For each order in each account, you can run the following:
```powershell
Set-PAOrder -Install
```
