### ISSUE TITLE
godaddy wildcard issues

### ISSUE THREAD

**Issue by olsonnn** [rmbolger/Posh-ACME#516]
normal cert works  but wildcard results in

Line |
 253 |          Submit-ChallengeValidation
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":"INVALID_BODY","message":"Request body doesn't fulfill schema, see details in `fields`"}

with:
New-PACertificate 'mydomain.eu','*.mydomain.eu' -Plugin GoDaddy -PluginArgs $pArgs  -AcceptTOS -Contact 'support@mydomain.eu' -verbose

what could be wrong here

**Comment by rmbolger** [comment]
Hi @olsonnn, thanks for reaching out. That appears to be a fairly common error from the GoDaddy API. But based on your command, I don't see an obvious reason why it would have happened. Do you have more context prior to the error from the verbose output you can post?

This is likely happening during the calls to `Publish-Challenge` that `Submit-ChallengeValidation` makes under the hood. You could try sending some test publish commands to narrow down the problem like this. The way wildcard TXT records are published is the same as non-wildcard. So we'll publish two records with different fake token values.

```powershell
# using the same $pArgs variable from before
Publish-Challenge mydomain.eu (Get-PAAccount) fake1 GoDaddy $pArgs -Verbose
Publish-Challenge mydomain.eu (Get-PAAccount) fake2 GoDaddy $pArgs -Verbose
UnPublish-Challenge mydomain.eu (Get-PAAccount) fake1 GoDaddy $pArgs -Verbose
UnPublish-Challenge mydomain.eu (Get-PAAccount) fake2 GoDaddy $pArgs -Verbose
```

**Comment by olsonnn** [comment]
Hi!
Verbose log: not special from my point of view.

VERBOSE: Updating directory info from https://acme-v02.api.letsencrypt.org/directory
VERBOSE: Using ACME Server https://acme-v02.api.letsencrypt.org/directory
VERBOSE: Using account 132853xxx
VERBOSE: Order name not specified, using 'mydomain.eu'
VERBOSE: Using existing order 'mydomain.eu' with status pending
VERBOSE: Setting Plugin to GoDaddy
VERBOSE: Updating plugin args for plugin(s) GoDaddy
VERBOSE: Saving order changes
WARNING: Fewer Plugin values than names in the order. Using GoDaddy for the rest.
VERBOSE: Publishing challenge for Domain mydomain.eu with Token JAEckwibzCadfadfdsafDKDzkYLpq2syfWksD05DB1a9OvELE using Plugin GoDaddy and DnsAlias ''.
VERBOSE: Adding a new TXT record for _acme-challenge with value nGuoMadfadfdsafdfdsfrhphKDnzU017KFqtQQIfUI
Submit-ChallengeValidation: C:\Users\user1\Documents\PowerShell\Modules\Posh-ACME\4.19.0\Public\New-PACertificate.ps1:253
Line |
 253 |          Submit-ChallengeValidation
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":"INVALID_BODY","message":"Request body doesn't fulfill schema, see details in `fields`"}
PS C:\Users\user1>

Single cert like test.mydomain just works fine.

**Comment by rmbolger** [comment]
The log shows it failing on the very first publish command. I think the problem is specifically with creating a domain root TXT record. But it only seems to be a problem for your domain. It works normally for one on my account. Can you create a domain root TXT message via the web GUI?

When you try the publish command, is there any more text to the error?

**Comment by rmbolger** [comment]
Correction. It's not actually the domain root. It would be an `_acme-challenge.example.com` record which is even weirder since you said `test.example.com` worked.

**Comment by rmbolger** [comment]
Ok, let's try this super raw and see if we can get a better error message. Give this a shot and post the result.

```powershell
# Change the $zone variable to your own domain and use the same $pArgs variable from before
$zone = 'example.com'
$auth = 'sso-key {0}:{1}' -f $pArgs.GDKey,[pscredential]::new('a',$pArgs.GDSecretSecure).GetNetworkCredential().Password
$headers = @{Authorization = $auth}
$body = ConvertTo-Json @(@{data='fakevalue';ttl=600}) -Compress
$queryParams = @{Uri = "https://api.godaddy.com/v1/domains/$zone/records/TXT/_acme-challenge"; Method='Put'; Headers=$headers; Body=$body; ContentType='application/json'}
Invoke-RestMethod @queryParams
```

**Comment by olsonnn** [comment]
Quick check: 
with wildcard
VERBOSE: Adding a new TXT record for _acme-challenge with value nGuoM6SA30hVo-HmsbSytrhphKDnzU017KFqtQQIfUI

with olaf2 
VERBOSE: Adding a new TXT record for _acme-challenge.olaf2 with value ocCdNvqjBLdEXQFZCh8YIAAdSEvem1hhH-o9zExMTcw

Note the _acme-challenge..OLAF2
Is that part missing / required in wildcard required?
Going to work on your test req. now

**Comment by olsonnn** [comment]
hmm script gives an error
MethodException: Cannot find an overload for "new" and the argument count: "2".

args:
GDKey = 'mykey'
GDSecretSecure = 'mysecret'

**Comment by olsonnn** [comment]
issue fixed. duplicate _acme-challenge. im so sorry for the trouble....

**Comment by rmbolger** [comment]
Nice! Glad you figured out the problem. Was there something special about the existing `_acme-challenge` record? The code should have been able to work even if a record already existed and just added another value to it. That's what it ends up doing anyway when you get a cert for both the domain apex and the wildcard name.

**Comment by olsonnn** [comment]
Ryan, there might be an issue with that.
I had 1 row with _acme-challenge. (nothing special tbh) 

Added a second in Godaddy UI. And got an error msg with conflicting records.

It seems it's not allowed!? I can post screenshot later if you want...
