### ISSUE TITLE
Error Thrown with large SAN List

### ISSUE THREAD

**Issue by rgg8354** [rmbolger/Posh-ACME#517]
When processing an order with a total of 33 endpoint names (total of 32 SANs), the following error is thrown twice: 

OperationStopped: C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.17.1\Public\New-PAOrder.ps1:245
Line |
 245 |          $order.authorizations[$i] = $auth.location
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Index was outside the bounds of the array.

After the error (because I was adding additional subdomains to an existing order), I see the existing endpoints with an already valid authorization and then PS returns to the prompt and no cert or even CSR is generated. 

As a test, the same occurs when the order is created new and an existing order.json does not exist.
![PoshAcme](https://github.com/rmbolger/Posh-ACME/assets/54369409/8f30b7a3-50dc-489e-8ebb-b63164741b50)

Edited: to correct the number of endpoints/SANs

**Comment by rmbolger** [comment]
Hey @rgg8354, thanks for reaching out. Can you double check whether there are any duplicate values in the endpoint names? The only way I've been able to reproduce this so far is if there's at least one duplicate and an error is generated for each duplicate value in the list.

I'm still planning on treating this as a bug, but I haven't decided exactly what to do when `New-PAOrder` is given a list of identifiers that has duplicates. What I'm leaning towards is automatically de-duping the list and throwing a warning.

**Comment by rgg8354** [comment]
@rmbolger Yes, it turns out that was the issue! After checking with the user who ordered the certificate, we decided to split it out for security between dev and prod domains. In that process, I found that two endpoints which were duplicated in the request.

**Comment by rmbolger** [comment]
Excellent. Thanks for the confirmation. I've already committed a change that should fix the issue if it happens again. It'll go out in the next release.

**Comment by rmbolger** [comment]
The fix is now live in 4.20.0
