### ISSUE TITLE
Timeout with WebSelfHost on Server 2022 and some 2019

### ISSUE THREAD

**Issue by manucad94** [rmbolger/Posh-ACME#518]
Hello everyone

While using `Get-PACertificate` with the `WebSelfHost` plugin and with our own internal Step-CA server the request reaches the timeout of the http challenge.
This problem occurs on all our Windows Server 2022 and some of the newer 2019.
The Request works in debug mode when you take your time and confirm the actions around the starting of the listener for the http challenge with a few seconds delay. It does almost never work in debug mode if you instantly accept each step or keep on pressing enter.
This behavior brought us to this workaround which works 100% of the time:
We have added a "Start-Sleep 5" to [Save-Challange.ps1](https://github.com/rmbolger/Posh-ACME/blob/main/Posh-ACME/Public/Save-Challenge.ps1) after the `Save-HttpChallange` at the end (line 34).

So we guess it could be something like, the procedure going on, while the http listener is not completely ready yet and somehow messing it up completely. In the 60 seconds to the timeout, multiple retries fail while the listener is up, displaying the correct token and the correct ID in the URL. Maybe it could be that PowerShell performance is worse on our newer server for whatever reason. The servers are all virtual and mostly on the same hardware...
Antivirus software has also been uninstalls for troubleshooting purpose without success.

Due to a lack of knowledge we are not able to come up with a adequate fix and for now we live with this workaround.

This image shows a comparison of the relevant part of the run in debug mode. Left one is working (waiting a few seconds between confirmations), Right one is not working (confirm each one instantly)
![Posh-ACME_WebSelfHost_troubles](https://github.com/rmbolger/Posh-ACME/assets/147408133/296d185b-d5cf-4aad-9ed6-fcf9a030a267)

Best regards,
Manu

**Comment by rmbolger** [comment]
Hey @manucad94, thanks for reaching out. That's a weird one. I wonder if there's an issue in the underlying .NET listener or maybe the PowerShell job runner.  It's also weird that it never seems to work even on retries by the ACME server.

In any case, I should be able to add an additional param to the plugin that will allow for a customizable sleep value following the listener starting up but before control returns to the module. That should at least make working around the problem easier if we can't identify the root cause.

**Comment by rmbolger** [comment]
I just made a commit on the main branch that adds a `WSHDelayAfterStart` param to the plugin. You should be able to add `WSHDelayAfterStart=5` to your plugin args hashtable to effectively get the same timeout functionality as your modified `Save-Challenge.ps1` file.

Let me know if that seems to work. Also, for future reference if you want the debug output without having to confirm every debug message, you can run `$DebugPreference = 'Continue'` in your session prior to running the cert command.

**Comment by manucad94** [comment]
Hi @rmbolger 
Thank you very much for the quick response and handling.
This modification works very well.

If we find any clues to the origin of this error, we'll let you know.

Thanks & best regards,
Manu

**Comment by rmbolger** [comment]
The new param is live in 4.20.0
