### ISSUE TITLE
Error running on azure automation

### ISSUE THREAD

**Issue by frehnejc** [rmbolger/Posh-ACME#52]
After importing all modules and dependency modules I get an error:
New-Object : Cannot find type [Org.BouncyCastle.Security.SecureRandom]: verify that the assembly containing this type 
is loaded.
At C:\Modules\User\Posh-ACME\Private\New-Csr.ps1:38 char:20
+         $sRandom = New-Object Org.BouncyCastle.Security.SecureRandom
+                    ~~~~~~~~~~~~~~~

**Comment by rmbolger** [comment]
If you do try the workarounds, I'd love to hear back on whether they worked or not. I haven't had a chance to test them myself yet.

**Comment by frehnejc** [comment]
OK I tried the workaround with -2048. However getting a new error:
Publish-DnsChallenge : Cannot bind argument to parameter 'AZAccessToken' because it is an empty string.
At C:\Modules\User\Posh-ACME.net46\Public\Submit-ChallengeValidation.ps1:122 char:25
+ ...             Publish-DnsChallenge $auth.DNSId $Account $auth.DNS01Toke ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Publish-DnsChallenge], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Publish-DnsChallenge

**Comment by rmbolger** [comment]
It sounds like the you either figured out or worked around the parameter binding issue in the other issue you opened.

I just wanted to mention that I released a .NET 4.6.1 compatible version of the module primarily for working with Azure stuff that hasn't been updated yet. It basically does all the workaround stuff I mentioned previously so you don't have it. You can find it here.
https://www.powershellgallery.com/packages/Posh-ACME.net46

I'm hoping to keep it updated in parallel with the main version until Azure gets upgraded to .NET 4.7.1 or better.
