### ISSUE TITLE
WEDOS DNS support ?

### ISSUE THREAD

**Issue by as-it** [rmbolger/Posh-ACME#528]
Would be possible to add WEDOS.com support? 
They have DNS API: https://kb.wedos.com/en/wapi-api-interface/wdns-en/wapi-wdns/

**Comment by rmbolger** [comment]
Hi @as-it, thanks for reaching out. Most likely yes. A quick look at the website implies you can sign up for DNS service for free which should make things much easier. I can't give any definitive timelines though.

**Comment by rmbolger** [comment]
So I have a draft implementation in a `wedos` branch that seems functional. I'm just testing it a bit before I pull it into the main branch. But this provider takes a really long time to replicate DNS updates. When you apply DNS changes, there's a message that it could take up to an hour. So I'm running some tests to see how long on average it actually takes. But realistically, I'm going to need to put a disclaimer in the guide that you'll have to set your `DnsSleep` parameter to something really large to account for the delay in propagation.

**Comment by as-it** [comment]
I see. One hour is quite long... Will this still be ok for Let's Encrypt to accept 'DNS challenge' after such delay?

Maybe you - as a developer of Posh-ACME - can reach out to them and write them 'idea to get better service: shorten propagation time of DNS updates' with some valid arguments (like competition 'normal' propagation times, etc.) ... WEDOS guys are always eager to get better - so I think they could hear you out 😉

**Comment by rmbolger** [comment]
Thankfully, none of my tests ended up being anywhere near a whole hour. The range seemed to be around 4-8 minutes which is slower than average, but not terrible. I still put the warning in the guide though. I should have it ready to pull into the main branch soon.

I'm curious under what circumstances it could take an hour though. Or if that's just them setting low expectations so they get less support calls.

**Comment by rmbolger** [comment]
This is now live in 4.21.0
