### ISSUE TITLE
Submit-Renewal doesn't appear to follow ErrorAction

### ISSUE THREAD

**Issue by mrdenny** [rmbolger/Posh-ACME#531]
I've got Submit-Renewal setup to ignore errors using the -ErrorAction SilentyContinue and the error messages are still being displayed (I'm catching the error via -ErrorVariable).

This is causing my automation to fail since it sees the error being returned.

**Comment by rmbolger** [comment]
Hey @mrdenny, thanks for reaching out. The docs for [ErrorAction](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.4#-erroraction) indicate it only affects non-terminating errors. But all of the errors that are explicitly directly by `Submit-Renewal` are currently terminating errors like having no account set or a no order found.

If you want to trap those, you'll likely have to put that code in a try/catch block.

**Comment by mrdenny** [comment]
Ah, that explains why it's acting like it it. I can build in a try catch in there. I'm getting no order errors currently.
