### ISSUE TITLE
Is there a full list of supported fields for -Subject? 

### ISSUE THREAD

**Issue by 100110010111** [rmbolger/Posh-ACME#532]
I have no issues when using `-Subject O="company name"` but when `-Subject O="company name",OU="team name",E="team@email"` it fails.

**Comment by 100110010111** [comment]
nevermind, code problem. its resolved.

**Comment by rmbolger** [comment]
Just for reference, know that public CAs issuing DV certificates don't use or include any Subject values other than the CN which is generated automatically by the module based on the first domain name. So specifying a Subject with things like Company, Team, Email doesn't actually include those things in the resulting certificate unless you're utilizing a private CA or only OV/EV certs from a commercial CA.

**Comment by 100110010111** [comment]
Right, I'm using a private CA.

-------- Original Message --------
