### ISSUE TITLE
Document output path somewhere

### ISSUE THREAD

**Issue by SeanFromIT** [rmbolger/Posh-ACME#55]
It would be helpful to know that the default output path is `%LOCALAPPDATA%\Posh-ACME\acme-v02.api.letsencrypt.org\`

**Comment by rmbolger** [comment]
Hey Sean, thanks for the suggestion. I agree. Do you think the readme or the tutorial would be a better place? Or somewhere else? Where did you unsuccessfully go looking for it first?

Technically, the full path to the cert related files that are generated are also in the output object from `New-PACertificate`, `Get-PACertificate`, and `Submit-Renewal`. However, they're not displayed by default. The easiest way to check them is via `Get-PACertificate | fl`, but admittedly that's not terribly intuitive or discoverable.

**Comment by SeanFromIT** [comment]
I went to the tutorial because the quick start in the readme didn't appear to do anything (of course it did, I just didn't know where to go). :-)

**Comment by Christoph-Wagner** [comment]
I'd like to add that this is the kind of information I'd expect on the quickstart page. Possibly also in the command output, but that's just icing ;)

**Comment by rmbolger** [comment]
Thanks again for the suggestions, guys. Hopefully this will help new people a bit more.
