### ISSUE TITLE
Gandi API change

### ISSUE THREAD

**Issue by webprofusion-chrisc** [rmbolger/Posh-ACME#554]
I think maybe the Gandi API endpoint has changed, not sure if the API requests stay the same or not. I'm seeing reported errors like ```{"object": "HTTPNotFound", "cause": "Not Found", "code": 404, "message": "The resource could not be found."}``` when trying to add TXT records. I don't personally have access to a Gandi account, this is based on second hand info so I'm just flagging it in case anyone else is seeing this.

https://api.gandi.net/docs/livedns/

**Comment by rmbolger** [comment]
Looks like they may have added a new authentication method for the API (Personal Access Tokens) and deprecated the old simple API Keys. Though the old method still works if you generate a key.

https://api.gandi.net/docs/authentication/

Working on adding support for PATs now. Annoyingly, it looks like they won't allow you to generate a PAT that is good for more than 1 year. So people using them will need to remember to update their PATs annually.

Coincidentally, I feel like I've seen a lot of random social media posts recently with people wanting to ditch Gandi for some reason.

**Comment by rmbolger** [comment]
The PAT change is now live in 4.25.0
