### ISSUE TITLE
Plugin request: Scaleway.com/Online.net

### ISSUE THREAD

**Issue by Freeben666** [rmbolger/Posh-ACME#557]
Hi,

Could you do a plugin for DNS challenge working with Online ?

I'd love to submit a PR but don't have he necessary skills.

Here is the Online plugin for acme.sh, if it helps : https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_online.sh

Regards

**Comment by rmbolger** [comment]
Hi @Freeben666. I'd be happy to spend the time writing a plugin. But it looks like the cheapest domain I can register there is about 6-8 EUR and they don't have any sort of sandbox/test API I can find. Would you be willing to temporarily share your own API key or perhaps do a one-time [sponsorship](https://github.com/sponsors/rmbolger) to cover the cost of the domain?

**Comment by Freeben666** [comment]
Hi @rmbolger ,
I won't be able to share my API key, but no problem for the sponsorship 🙂

**Comment by rmbolger** [comment]
Thanks! Much appreciated. This should be pretty straightforward once I grab a domain from them. Will hopefully get to it sometime next week.

**Comment by rmbolger** [comment]
Small update. After struggling a bit with their identity verification process, I successfully purchased a domain and have begun working on the plugin.

**Comment by rmbolger** [comment]
I'm a little confused now. Scaleway.com and Online.net are the same company, right? The domain I purchased was from online.net and I have a basic plugin working for the online.net API. But I realized my credentials don't actually work for the Scaleway.com dashboard and it seems like a whole separate site with a totally different API. Are they in the middle of a migration? Creating a new Scaleway.com account with the same email as Online.net seems to be a completely separate identity.

It almost seems like I should make an `OnlineNet` plugin separate from a `Scaleway` plugin?

**Comment by Freeben666** [comment]
> I'm a little confused now. Scaleway.com and Online.net are the same company, right? The domain I purchased was from online.net and I have a basic plugin working for the online.net API. But I realized my credentials don't actually work for the Scaleway.com dashboard and it seems like a whole separate site with a totally different API. Are they in the middle of a migration? Creating a new Scaleway.com account with the same email as Online.net seems to be a completely separate identity.
> 
> It almost seems like I should make an `OnlineNet` plugin separate from a `Scaleway` plugin?

Hello,

Yes, Scaleway and Online are the same company (I can't remember which one bought the other). But I think accounts for both platforms are still separate.

Personnaly I only use the portal available at https://console.online.net/ and the API on that same domain (https://console.online.net/fr/api/access)

**Comment by rmbolger** [comment]
Weird. Well, the plugin for the online.net API is in a new branch called `plugin-onlinenet` if you want to check it out. I've got a support ticket open with Scaleway to see if they can somehow merge my 2 accounts so I can also make a plugin for the newer API without having to transfer the existing domain or purchase another one.

**Comment by rmbolger** [comment]
Support came back and said the only way to use the newer Scaleway API is by paying to transfer the domain to the Scaleway dashboard which seems totally silly, but whatever. They also said there are no current plans to migrate users away from `console.online.net`. So I guess if they ever change their minds, I can work on a newer Scaleway plugin.

I went ahead and merged the `OnlineNet` plugin to the main branch and I should have it live in a new release soon.

**Comment by rmbolger** [comment]
The new OnlineNet plugin is now live in 4.25.0

**Comment by Freeben666** [comment]
Hi @rmbolger 

Haven't had a chance to test it out yet (I've been away), but thank you. I'll try it out and get back to you :-)
