### ISSUE TITLE
Feature Request: Add DNS Plugin Support for dynv6 in Posh-ACME

### ISSUE THREAD

**Issue by peter1123** [rmbolger/Posh-ACME#563]
Hi Ryan,

I would like to request the addition of a new DNS plugin for the Posh-ACME project to support the DNS provider dynv6 (https://dynv6.com/).

Dynv6 is a popular free DNS service that supports dynamic DNS and is widely used in personal and small-scale projects. Adding support for this provider will make it easier for users to manage DNS-01 challenges for certificates on dynv6.

Thank you for considering this feature request!

**Comment by rmbolger** [comment]
Hi @peter1123, thanks for reaching out. The dynv6 documentation seems to indicate they support RFC2136 based dynamic updates which you can use with the existing [RFC2136 plugin](https://poshac.me/docs/v4/Plugins/RFC2136/).
https://dynv6.com/docs/apis#dns-update

It's a bit more cumbersome to setup than a dedicated REST plugin particularly on Windows. But it should work if you're in a hurry.

**Comment by peter1123** [comment]
Thanks Ryan.

Have a nice day.
