### ISSUE TITLE
Azure Plugin incorrectly evaluates token expiration time

### ISSUE THREAD

**Issue by Cavorter** [rmbolger/Posh-ACME#57]
When using the Azure plugin the expiration for the authentication token is evaluated incorrectly by simply calling `Get-Date` and comparing the localized TimeDate object against the UTC value attached to the token rather than converting the resulting TimeDate object to it's UTC value.

https://github.com/rmbolger/Posh-ACME/blob/55abb2d18832729e7dbebf61ce623fc97f88b9fe/Posh-ACME/DnsPlugins/Azure.ps1#L314

**Comment by Cavorter** [comment]
FYI - I've got a fork up with the fix just taking a look to see if there are any tests around this I can poke at while I'm in here. :-)

**Comment by rmbolger** [comment]
Nice! Thanks for the catch and fix. I'll follow up in the PR.
