### ISSUE TITLE
Domain-name in sub-domain not possible (at least a documentation issue)

### ISSUE THREAD

**Issue by andreashaerter** [rmbolger/Posh-ACME#584]
Hi,

while working on #573, I recognized that there is a problematic code snippet at https://poshac.me/docs/v4/Plugins/Plugin-Development-Guide/#zone-matching:

```ps
$recShort = ($RecordName -ireplace [regex]::Escape($zoneName), [string]::Empty).TrimEnd('.')
```

This snippet will replace *every* occurrence of `$zoneName` while it should *only* replace *the last one*:

```ps
$zoneName = "example.com"
$RecordName = "_acme-challenge.example.com.bar.baz.example.com"

$recShort = ($RecordName -ireplace [regex]::Escape($zoneName), [string]::Empty).TrimEnd('.')
Write-Host $recShort
```

Output: `_acme-challenge..bar.baz` (instead of `_acme-challenge.example.com.bar.baz`).

**I did not check yet if there are plugins using this code.** The impact should be low as most people won't use a subdomain like `exmaple.com.example.com`, but better safe then sorry (plus: who knows which kind of side-effects a too greedy replace action might trigger beside a non-working edge case).

**Comment by andreashaerter** [comment]
Proposal to fix this: Use `LastIndexOf()`

```ps
$recShort = $RecordName.Remove($RecordName.ToLower().LastIndexOf($zoneName.ToLower()), $zoneName.Length).TrimEnd(".");
```

Should work:

```
$zoneName = "Example.com"
$RecordName = "_acme-challenge.eXAmple.com.bar.BAZ.examPLE.com"

$recShort = $RecordName.Remove($RecordName.ToLower().LastIndexOf($zoneName.ToLower()), $zoneName.Length).TrimEnd(".");
Write-Host $recShort


$zoneName = "example.com"
$RecordName = "_acme-challenge.example.com.bar.baz.example.com"

$recShort = $RecordName.Remove($RecordName.ToLower().LastIndexOf($zoneName.ToLower()), $zoneName.Length).TrimEnd(".");
Write-Host $recShort
```

Result:
```
_acme-challenge.eXAmple.com.bar.BAZ
_acme-challenge.example.com.bar.baz
```

**Comment by rmbolger** [comment]
Hah, nice find! This code is actually in quite a few of the plugins. It's even in the plugin development guide as a suggestion for parsing out the short names. I guess it's too much of an edge case for people to have found naturally until now.

I feel like there's a way to tweak it so it still works with the regex based replace while still allowing for the zone name not being part of the string. I'm gonna futz with it a bit as sort of a code golfing challenge.

**Comment by rmbolger** [comment]
The potential trailing `.` on the possible combos of `$RecordName` and `$zoneName` makes things annoying to deal with. But theoretically I could make tweak `Publish-Challenge` and `Unpublish-Challenge` so that at least the incoming `$RecordName` already has any trailing `.` stripped.

Assuming I do that, what about this? In the regex, we
- pre-trim potential zone name `.` before we escape it
- add a conditional `.` prefix clause so we don't have to trim the result
- add the `$` end of line matcher so it only grabs the last instance

```powershell
$recShort = $RecordName -ireplace "\.?$([regex]::Escape($zoneName.TrimEnd('.')))$", ''
```

Here's a mini test suite I setup. It's probably worth adding some additional test cases.

```powershell
$tests = @'
zone,record,expected
example.com,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar.BAZ
Example.com,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar.BAZ
example.com.,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar.BAZ
Example.com.,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar.BAZ
example.net,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com
baz.example.com,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar
baz.Example.com,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar
baz.example.com.,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar
baz.Example.com.,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar
baz.example.net,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com,_acme-challenge.EXAmple.com.bar.BAZ.examPLE.com
example.com,examPLE.com,
Example.com,examPLE.com,
example.com.,examPLE.com,
Example.com.,examPLE.com,
example.net,examPLE.com,examPLE.com
'@ | ConvertFrom-Csv

function parse { [CmdletBinding()] param([Parameter(Position=0)][string]$zoneName,[Parameter(Position=1)][string]$RecordName) try { $RecordName -ireplace "\.?$([regex]::Escape($zoneName.TrimEnd('.')))$", '' } catch { "(exception)" } }

$tests | %{ $recShort = parse $_.zone $_.record; $pass = $recShort -ceq $_.expected; if (-not $pass) { $pass = $recShort }; [pscustomobject]@{zone=$_.zone;record=$_.record;expected=$_.expected;pass=$pass} }
```

And here's the current output:

```
zone             record                                          expected                                        pass
----             ------                                          --------                                        ----
example.com      _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar.BAZ             True
Example.com      _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar.BAZ             True
example.com.     _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar.BAZ             True
Example.com.     _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar.BAZ             True
example.net      _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com True
baz.example.com  _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar                 True
baz.Example.com  _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar                 True
baz.example.com. _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar                 True
baz.Example.com. _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar                 True
baz.example.net  _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com _acme-challenge.EXAmple.com.bar.BAZ.examPLE.com True
example.com      examPLE.com                                                                                     True
Example.com      examPLE.com                                                                                     True
example.com.     examPLE.com                                                                                     True
Example.com.     examPLE.com                                                                                     True
example.net      examPLE.com                                     examPLE.com                                     True
```

**Comment by andreashaerter** [comment]
Good idea, $ asserting the position at the end of a line should do it.

The conditional outside the capture group should also work at the end, 
so closing with would do ist all in regex without a trim if one does not 
want to mix methods (can't test it as I am not at the laptop ATM):

"\.?( ... )\.?$"

**Comment by rmbolger** [comment]
Hah, I got all excited thinking you were right about the capture group at the end instead of the TrimEnd. But it fails for any of the tests where the zone has a trailing dot because the dot still gets escaped by `[regex]::escape`. So the resulting regex ends up with two literal dots before the conditional and end of line match.

```
# this
\.?example\.com\.\.?$
# instead of this
\.?example\.com\.?$
```

Removing the literal dot from after the escape makes it look like things work in the current test cases, but then I think we have another weird edge case where the last letter of the TLD becomes optional so `example.com` would match an `_acme-challenge.example.co` record even though it shouldn't.

I think we're stuck with at least one TrimEnd in there.
