### ISSUE TITLE
Command was found but the module could not be loaded

### ISSUE THREAD

**Issue by iamseanduffy** [rmbolger/Posh-ACME#63]
After running 'Install-Module -Name Posh-ACME' and successfully installing the module, the following error occurs on all servers.

Client Version: v2.5.0
Windows Version: Windows Server 2016

Command: New-PACertificate XXXXXX -AcceptTOS (dns entry masked)
Error:

New-PACertificate : The 'New-PACertificate' command was found in the module 'Posh-ACME', but the module could not be
loaded. For more information, run 'Import-Module Posh-ACME'.
At line:1 char:1
New-PACertificate XXXXXX -AcceptTO ...
CategoryInfo : ObjectNotFound: (New-PACertificate:String) [], CommandNotFoundException
FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by iamseanduffy** [comment]
Command: Set-PAServer LE_STAGE
Error:

Set-PAServer : The 'Set-PAServer' command was found in the module 'Posh-ACME', but the module could not be loaded. For
more information, run 'Import-Module Posh-ACME'.
At line:1 char:1
Set-PAServer LE_STAGE
    CategoryInfo          : ObjectNotFound: (Set-PAServer:String) [], CommandNotFoundException
    FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by rmbolger** [comment]
The module requires .NET 4.7.1 or later to function properly. I believe Windows Server 2016 comes with .NET 4.6.2 by default. The module loading function does a check to verify what version is installed and should be throwing an error if the version is insufficient. But I wonder if the auto-import process doesn't show the error.

Can you try running `Import-Module Posh-ACME` manually?

**Comment by iamseanduffy** [comment]
Thanks for response.  It was the absence of the framework 4.7.1 which was causing the problem and I am now up and running.

However, I am struggling to find the certificates once I have requested them. I used the following command

New-PACertificate *.XXXXXXX -AcceptTOS -contact dotnet@XXXXXXX.com -DnsPlugin
 manual -verbose

The message back said that certificate had been created and a thumbprint was shown, but I am unable to locate the certificate.  Any suggestions? Is there a default location?

**Comment by rmbolger** [comment]
The easiest way to get the path is running `Get-PACertificate | fl`. The paths are actually in the output object that is shown by New-PACertificate, they're just hidden by default. So adding the `Format-List` (alias "fl") to it or Get-PACertificate shows all the values in list mode.

**Comment by iamseanduffy** [comment]
I really do appreciate this help, am I a bit of a n00b when it comes to certificates.  
Final question, when importing the pfx file into server certificates in IIS, where does the password come from?

I fully understand this is outside of the Posh-ACME application, I just wondered if you knew.

Thanks again.

**Comment by rmbolger** [comment]
Everyone was new at some point. It's all good.

The password actually does come from the module. The pfx file itself is sort of like an encrypted zip file and the password is required to basically decrypt and extract. You can set it with the `-PfxPass` parameter. But it defaults to `poshacme` if not set.

**Comment by rmbolger** [comment]
Also, IIS will read certificates from the Local Computer's personal certificate store. They don't need to be imported directly in IIS. So you could also hypothetically use the `-Install` parameter in `New-PACertificate` and then skip the manual import step in your process.
