### ISSUE TITLE
Unnecessary exception in Get-PAOrder

### ISSUE THREAD

**Issue by maybe-hello-world** [rmbolger/Posh-ACME#70]
In Get-PAOrder there's a place (lines 52-58) where cached PAOrder is checked. But if there's no cached PAOrder module throws an exception.
```
    } else {
        throw "Unable to find cached PAOrder info for $MainDomain."
    }
```

As I understood right, cached PAOrder isn't necessary for new-pacertificate due to:
`try { $order = Get-PAOrder $Domain[0] -Refresh } catch {}`

So it's not actually an error but one expected behavior of code. So maybe it's better to change to something like "return $null"? 
Because throwing an Exception will add Error description to $Error variable (list that contains all errors during script execution) and it make scripting and automation harder because since that moment you cannot just check if $Error is null and have to analyze what errors are in there.

Approvement:
```
PS C:\Users\Kell> function invoke-error { throw "error" }
PS C:\Users\Kell> $Error.clear()
PS C:\Users\Kell> $Error
PS C:\Users\Kell> try {invoke-error} catch {}
PS C:\Users\Kell> $Error
error
At line:1 char:25
+ function invoke-error { throw "error" }
+                         ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (error:String) [], RuntimeException
    + FullyQualifiedErrorId : error

PS C:\Users\Kell>

```

Another way is to use "-ErrorAction Ignore" since it does not add error to $Error but due to https://github.com/PowerShell/PowerShell/issues/1759 there are some problems with it that would be solved in PS6.2

**Comment by rmbolger** [comment]
This is a great find! Thanks. I think you're correct about `return $null` instead of throwing the exception. Not only does it make things simpler, it adds consistency with the behavior when you don't supply a domain argument and it tries to return the "current" order.  If there is no current order, it just returns the $null object rather throwing an exception.
