### ISSUE TITLE
Submit-Renewal doesn't have a way to pass in dns plugin params, e.g. a fresh Azure access token

### ISSUE THREAD

**Issue by perbergland** [rmbolger/Posh-ACME#72]
The plugin parameters are saved to disk, but the access token for Azure is short-lived and needs to be sent in again. Adding a pluginArgs parameter like in other places should be enough.

Workaround: Using New-PACertificate after copying some code from Submit-Renewal.ps1

**Comment by rmbolger** [comment]
I appreciate the request, but this is a pretty unique problem specific to the Azure plugin when using the access token option which is more of an advanced scenarior. And `Submit-Renewal` is already just a loose wrapper around `New-PACertificate`. So I feel like adding additional parameters to it just confuses things.

Using the workaround of just calling `New-PACertificate` again is likely the best choice in this scenario.

**Comment by perbergland** [comment]
Fair enough
