### ISSUE TITLE
Add Aliyun (Alibaba Cloud) DNS plugin

### ISSUE THREAD

**Issue by jianbosu** [rmbolger/Posh-ACME#74]
DnsPluginHelp no aliyun cloud api

**Comment by rmbolger** [comment]
I do not recognize aliyun. Is it this? https://www.alibabacloud.com/

**Comment by jianbosu** [comment]
yes

**Comment by rmbolger** [comment]
I have created a trial account for myself. But their DNS service isn't included in the list of trial services. Let me see if I can get them to give me temporary access or some sort of credit.

**Comment by rmbolger** [comment]
I managed to work out enough access to write the plugin. It is now committed to the master branch. Can you install the dev version and test?  Here is the [usage guide](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Aliyun-Readme.md).

**Comment by rmbolger** [comment]
I'm gonna close this for now since the plugin is now live. If you have any more issues, just let me know.

**Comment by jianbosu** [comment]
@rmbolger 
the secret key is only english letter,It doesn't matter with Chinese.

and the your unsecure not work
![1](https://user-images.githubusercontent.com/17507066/46815510-a1a85500-cdad-11e8-8247-64fa24fc5cec.png)
![2](https://user-images.githubusercontent.com/17507066/46815512-a1a85500-cdad-11e8-9967-f7b9ff5bf213.png)

**Comment by jianbosu** [comment]
@rmbolger 
i use the Method windows by input secure Manual not ctrl+v,but also get error.
![3](https://user-images.githubusercontent.com/17507066/46816006-a3bee380-cdae-11e8-8a5c-1cc5a2f124c2.png)

ps:my access key is Sub Account access key
![4](https://user-images.githubusercontent.com/17507066/46816203-0617e400-cdaf-11e8-87b4-29b44415254d.png)

**Comment by rmbolger** [comment]
All of the errors you're getting seem to be related to parameter binding on the functions. Sometimes this can happen because `New-PACertificate` tries to merge previously used plugin parameters with the set you passed in and there's odd combinations due to previous testing that screw things up. Can you try running `Publish-DnsChallenge` separately to see if it works?  Try something like this:

```powershell
Publish-DnsChallenge example.com (Get-PAAccount) 'test value' Aliyun $aliParams
```

If that works properly, try creating a new ACME account and then run `New-PACertificate` again. The new account will prevent any old plugin parameters from screwing things up.

```powershell
New-PAAccount -AcceptTos
New-PACertificate *.example.com -DnsPlugin Aliyun -PluginArgs $aliParams
```

**Comment by jianbosu** [comment]
New-Object : 找不到类型 [Org.BouncyCastle.Security.SecureRandom]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:38 字符: 20
+         $sRandom = New-Object Org.BouncyCastle.Security.SecureRandom
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : 找不到类型 [Org.BouncyCastle.Crypto.Generators.RsaKeyPairGenerator]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:65 字符: 23
+ ...   $rsaGen = New-Object Org.BouncyCastle.Crypto.Generators.RsaKeyPairG ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : 找不到类型 [Org.BouncyCastle.Crypto.KeyGenerationParameters]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:66 字符: 25
+ ... $genParam = New-Object Org.BouncyCastle.Crypto.KeyGenerationParameter ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

不能对 Null 值表达式调用方法。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:67 字符: 13
+             $rsaGen.Init($genParam)
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

不能对 Null 值表达式调用方法。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:68 字符: 13
+             $keyPair = $rsaGen.GenerateKeyPair()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Export-Pem : 无法将参数绑定到参数“InputObject”，因为该参数是空值。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:73 字符: 20
+         Export-Pem $keyPair $keyFile
+                    ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-Pem]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Export-Pem

New-Object : 找不到类型 [Org.BouncyCastle.Asn1.X509.X509Name]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:80 字符: 16
+ ...  $subject = New-Object Org.BouncyCastle.Asn1.X509.X509Name("CN=$($Ord ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : 找不到类型 [Collections.Generic.Dictionary[Org.BouncyCastle.Asn1.DerObjectIdentifier,Org.BouncyCastle.Asn1.X509.X509Extension]]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:83 字符: 16
+ ...  $extDict = New-Object 'Collections.Generic.Dictionary[Org.BouncyCast ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : 找不到类型 [Org.BouncyCastle.Asn1.X509.BasicConstraints]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:86 字符: 134
+ ... OctetString(New-Object Org.BouncyCastle.Asn1.X509.BasicConstraints($f ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

找不到类型 [Org.BouncyCastle.Asn1.X509.KeyUsage]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:87 字符: 172
+ ... stle.Asn1.X509.KeyUsage([Org.BouncyCastle.Asn1.X509.KeyUsage]::Digita ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastle.Asn1.X509.KeyUsage:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

找不到类型 [Org.BouncyCastle.Asn1.X509.KeyPurposeID]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:88 字符: 184
+ ... 09.ExtendedKeyUsage([Org.BouncyCastle.Asn1.X509.KeyPurposeID]::IdKPSe ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastle.Asn1.X509.KeyPurposeID:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

找不到类型 [Org.BouncyCastle.Asn1.X509.GeneralName]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:91 字符: 98
+ ... sn1.X509.GeneralName([Org.BouncyCastle.Asn1.X509.GeneralName]::DnsNam ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastle.Asn1.X509.GeneralName:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

New-Object : 找不到类型 [Org.BouncyCastle.Asn1.X509.GeneralNames]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:92 字符: 122
+ ... OctetString(New-Object Org.BouncyCastle.Asn1.X509.GeneralNames(@(,$ge ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : 找不到类型 [Org.BouncyCastle.X509.Extension.SubjectKeyIdentifierStructure]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:93 字符: 121
+ ... OctetString(New-Object Org.BouncyCastle.X509.Extension.SubjectKeyIden ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

找不到类型 [Org.BouncyCastle.Asn1.X509.X509Extensions]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:96 字符: 18
+     $extDict.Add([Org.BouncyCastle.Asn1.X509.X509Extensions]::BasicCo ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastl....X509Extensions:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

找不到类型 [Org.BouncyCastle.Asn1.X509.X509Extensions]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:97 字符: 18
+     $extDict.Add([Org.BouncyCastle.Asn1.X509.X509Extensions]::KeyUsag ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastl....X509Extensions:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

找不到类型 [Org.BouncyCastle.Asn1.X509.X509Extensions]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:98 字符: 18
+     $extDict.Add([Org.BouncyCastle.Asn1.X509.X509Extensions]::Extende ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastl....X509Extensions:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

找不到类型 [Org.BouncyCastle.Asn1.X509.X509Extensions]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:99 字符: 18
+     $extDict.Add([Org.BouncyCastle.Asn1.X509.X509Extensions]::Subject ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastl....X509Extensions:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

找不到类型 [Org.BouncyCastle.Asn1.X509.X509Extensions]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:100 字符: 18
+     $extDict.Add([Org.BouncyCastle.Asn1.X509.X509Extensions]::Subject ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastl....X509Extensions:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

New-Object : 找不到类型 [Org.BouncyCastle.Asn1.X509.X509Extensions]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:110 字符: 19
+ ... xtensions = New-Object Org.BouncyCastle.Asn1.X509.X509Extensions($ext ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

找不到类型 [Org.BouncyCastle.Asn1.Pkcs.PkcsObjectIdentifiers]。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:111 字符: 110
+ ... tributePkcs([Org.BouncyCastle.Asn1.Pkcs.PkcsObjectIdentifiers]::Pkcs9 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastl...jectIdentifiers:TypeName) []，RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

New-Object : 找不到类型 [Org.BouncyCastle.Pkcs.Pkcs10CertificationRequest]: 请确认加载了包含该类型的程序集。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:114 字符: 12
+     $req = New-Object Org.BouncyCastle.Pkcs.Pkcs10CertificationReques ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

Export-Pem : 无法将参数绑定到参数“InputObject”，因为该参数是空值。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:117 字符: 16
+     Export-Pem $req $reqFile
+                ~~~~
    + CategoryInfo          : InvalidData: (:) [Export-Pem]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Export-Pem

不能对 Null 值表达式调用方法。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\New-Csr.ps1:120 字符: 12
+     return (ConvertTo-Base64Url $req.GetEncoded())
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Error parsing certificate request: asn1: syntax error: sequence truncated
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Private\Invoke-ACME.ps1:135 字符: 9
+         throw [AcmeException]::new($acmeError.detail,$acmeError)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AcmeException
    + FullyQualifiedErrorId : Error parsing certificate request: asn1: syntax error: sequence truncated

**Comment by rmbolger** [comment]
One of your previous screenshots indicated your .NET version is too low to use the module. There's a big multi-line warning when the module loads. You need to upgrade to .NET 4.7.1 or later.

**Comment by jianbosu** [comment]
succeed，thanks！ now the dns method have only one problem，that the secure key must input one by one by hands，cann't paste，


other problem，the http-01 method get error：

PS C:\Users\Administrator> New-PACertificate 'bugs.****.com' -AcceptTOS -Contact admin@***.com
Submit-ChallengeValidation : 无法对参数“DnsPlugin”执行参数验证。该参数为 Null、为空或参数集合的某个元素包含 Null 值。
请提供一个不包含任何 Null 值的集合，然后重试此命令。
所在位置 C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.0\Public\New-PACertificate.ps1:159 字符: 36
+         Submit-ChallengeValidation @chalParams
+                                    ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Submit-ChallengeValidation]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Submit-ChallengeValidation

**Comment by rmbolger** [comment]
I'm not sure what to tell you about the secure key input. I don't have a Chinese localized version of Windows to test things with. If you can't get it to work using any of the workarounds I posed earlier, you may want to just use the `AliSecretInsecure` mode.

For the HTTP stuff, it will probably be easier to open a new issue. But if you already have an account, you just start at the "Create an Order" step.

**Comment by jianbosu** [comment]
ok,close the issue
