### ISSUE TITLE
Question: Using Windows DNS Plugin

### ISSUE THREAD

**Issue by centuryx476** [rmbolger/Posh-ACME#77]
Hello,
First off, please do not ever abandon this project. It has literally saved my life and made production deployment seamless and painless. 

Second: I have an entire windows domain back-end with windows DNS servers in my DMZ facing the internet. 
How exactly does the "Windows" DNS plugin work. I enter in the IP address of the DNS server and it will then give me my "TXT" record ? I then go add that to my domain Registrar ? 
Unfortunately at the moment I cannot do a test but my curiosity is getting the best of me.

Thanks

**Comment by rmbolger** [comment]
Thanks for the kind words. I love that it has helped you out. =)

> How exactly does the "Windows" DNS plugin work. I enter in the IP address of the DNS server and it will then give me my "TXT" record ? I then go add that to my domain Registrar ?

It's basically just like all the other plugins except the Windows DNS server is your "provider". So it's only useful if the domain you're getting a cert for is already configured at the registrar to point its NS records at your Windows DNS servers or your Windows DNS servers are the masters that send zone transfers to other Internet-facing DNS servers).

Put another way, if you add a TXT record on your Windows DNS server, can I (random stranger from the Internet) query something like Google's DNS server (8.8.8.8) and resolve that record? If yes, the Windows plugin should work for you and you can automate everything with no manual steps. If not, it likely means your Windows DNS servers are only hosting "internal" copies of your zones and you have something else (like your registrar) hosting the external copies. So you'd need a plugin that works with that external provider *or* you'd need to use the Manual plugin which is where it tells you what TXT records to add and you manually add them.

**Comment by centuryx476** [comment]
OK,
That makes sense now. 
Thank you very much for the quick reply.
