### ISSUE TITLE
Add wiki page for doing manual dns validation

### ISSUE THREAD

**Issue by mithrandyr** [rmbolger/Posh-ACME#81]
There is a useful page for doing manual HTTP validation -- but nothing for doing manual DNS validation.  There is a "Manual" dns plugin -- but it doesn't allow for programmatic engagement.  If you are wanting to leverage a DNS infrastructure that there isn't a module for, there is no easy way to do this. Please provide an advanced wiki page for DNS validation that matches the http validation. -- below is what I was able to cobble together by stepping through POSH-Acme with the "Manual" DNS plugin.

``` powershell
# Setup your Account
if(-not (Get-PAAccount)) {
    Write-Host "Building account..."
    New-PAAccount -Contact "youremailaddress" -AcceptTOS
}

#Setup the Order
New-PAOrder -Domain "somedomain" -Force -FriendlyName "Friendly Description" 

#Gather the authorization information
$authNeeded = (Get-PAOrder | Get-PAAuthorizations)[0]

#Generate the TXT Value
$keyAuth = Get-KeyAuthorization $authNeeded.challenges[0].token
$keyAuthBytes = [Text.Encoding]::UTF8.GetBytes($keyAuth)
$sha256 = [Security.Cryptography.SHA256]::Create()
$keyAuthHash = $sha256.ComputeHash($keyAuthBytes)
$txtValue = [Convert]::ToBase64String($keyAuthHash).Split("=")[0].Replace('+','-').Replace('/','_')

#Do your own coding for DNS record creation

# Send DNS Challenge Acknowledge (basically, tell LE to check dns now)
Send-ChallengeAck $authNeeded.DNS01Url

#Verify that the challenge happened
$start = (Get-Date)
while((Get-Date) -lt $start.AddSeconds(15)) {
    Start-Sleep -Milliseconds 500
    $authStatus = Get-PAAuthorizations $authNeeded.DNS01Url | Select-Object -ExpandProperty status
    if($authStatus -ne "pending") { break }
}
if($authStatus -ne "valid") { throw "not validated!" }

# Do your own coding to remove DNS record

# Lets get the Certificate (by invoke "New-PACertificate" with the same domain, posh-ACME is smart enough to complete the order for us!
Get-PAOrder -Refresh
$certInfo = New-PACertificate "somedomain"
```

**Comment by rmbolger** [comment]
This is a good idea. I'll see what I can put together.

**Comment by rmbolger** [comment]
[(Advanced) Semi Manual DNS Challenge Validation](https://github.com/rmbolger/Posh-ACME/wiki/(Advanced)-Semi-Manual-DNS-Challenge-Validation) is now a page in the wiki. It is extremely similar to the HTTP one because the steps really aren't *that* different.

Let me know what you think.

**Comment by mithrandyr** [comment]
@rmbolger -- just finished reading through the page -- looks really good.  You also exposed a cmdlet that handles generating the txtValue (Get-KeyAuthorization), going to be updating my scripts to take advantage of that!.  Thanks for putting this together!

**Comment by rmbolger** [comment]
Yeah, I added that function while I was writing the HTTP challenge guide for another user.

I was also thinking of adding a section to both about how to do renewals. But it's basically just some notes about doing everything over again except the account creation and how to check whether it's time to renew yet.
