### ISSUE TITLE
Wildcard certificate DNS

### ISSUE THREAD

**Issue by Buddster** [rmbolger/Posh-ACME#84]
When creating a certificate with wildcard in the DNS name it pushes that wildcard star in the name to the DNS provider. It doesn't seem to matter for us (Cloudflare), it works, but is that really how it should be doing? Cloudflare seems a bit angry with the format and say it's wrong. 

![bild](https://user-images.githubusercontent.com/12795454/45951075-74645480-c002-11e8-89d8-fd2a76a84234.png)

**Comment by rmbolger** [comment]
What command did you use to generate that record? Normal wildcard records like `*.example.com` should be having the `*.` stripped and replaced by the `_acme-challenge` portion.

**Comment by Buddster** [comment]
Ahh sorry, you are completely right. Checked the timestamp now and that was an old record, probably a colleague have tested it before me on another platform. It creates the record _acme-challenge.domain.com as it should so everything good. 

And thnx alot for this awesome module! Soon finished with the setup to replace most of our internal services with LE thanx to your module!

**Comment by rmbolger** [comment]
Not a problem. Glad to hear everything's working!
