### ISSUE TITLE
GANDI v5 (LIVEDNS) Plugin

### ISSUE THREAD

**Issue by llefevere** [rmbolger/Posh-ACME#85]
I'm looking for a DNS Plugin designed or compatible GANDI v5 (LIVEDNS).
Do you if someone is working on ?

**Comment by llefevere** [comment]
Hello and thank’s for reply Ryan

 

Your link is the right one !

I’m afraid, I’ve never seen free trials on their site, but there some promotional offers like extension .pw for 0.60€ :/

 

 

De : Ryan Bolger <notifications@github.com> 
Envoyé : mardi 25 septembre 2018 18:36
À : rmbolger/Posh-ACME <Posh-ACME@noreply.github.com>
Cc : llefevere <l.lefevere@free.fr>; Author <author@noreply.github.com>
Objet : Re: [rmbolger/Posh-ACME] GANDI v5 (LIVEDNS) Plugin (#85)

 

No one has mentioned working on a plugin for Gandi yet. Is this the provider? https://doc.livedns.gandi.net/

I'd be happy to try and write one if I can get an account to work with. Do they offer a free trial?

**Comment by rmbolger** [comment]
I was hoping I could just setup a sub-domain DNS delegation for a domain I already own. But it seems they don't support *just* DNS hosting. So I did go ahead and buy a random `.pw` domain which was super cheap (thanks for the recommendation). Their REST API looks pretty straightforward. So it shouldn't take too long to build the plugin. I'll let you know when I have something ready you can test.

**Comment by llefevere** [comment]
Be aware that Gandi DNS doesn’t accept TTL values lower than 300, so don’t try to set it for other way that testing error message return !

 

De : Ryan Bolger <notifications@github.com> 
Envoyé : mercredi 26 septembre 2018 04:41
À : rmbolger/Posh-ACME <Posh-ACME@noreply.github.com>
Cc : llefevere <l.lefevere@free.fr>; Author <author@noreply.github.com>
Objet : Re: [rmbolger/Posh-ACME] GANDI v5 (LIVEDNS) Plugin (#85)

 

I was hoping I could just setup a sub-domain DNS delegation for a domain I already own. But it seems they don't support just DNS hosting. So I did go ahead and buy a random .pw domain which was super cheap (thanks for the recommendation). Their REST API looks pretty straightforward. So it shouldn't take too long to build the plugin. I'll let you know when I have something ready you can test.

**Comment by rmbolger** [comment]
The Gandi plugin is now in the master branch. It's working for me, but can you test it out on your end as well?

**Comment by llefevere** [comment]
It’s all right for me :

1.       New certificate

2.       Renew certificate

Thank’s again for your quick reply and perfect job !

 

De : Ryan Bolger <notifications@github.com> 
Envoyé : jeudi 27 septembre 2018 09:10
À : rmbolger/Posh-ACME <Posh-ACME@noreply.github.com>
Cc : llefevere <l.lefevere@free.fr>; Author <author@noreply.github.com>
Objet : Re: [rmbolger/Posh-ACME] GANDI v5 (LIVEDNS) Plugin (#85)

 

The Gandi plugin is now in the master branch. It's working for me, but can you test it out on your end as well?
