### ISSUE TITLE
Options for CSR values

### ISSUE THREAD

**Issue by marksu22** [rmbolger/Posh-ACME#89]
I have a device only provide CSR generation and then let me fill the certificate.

It seems I can change the CSR and fill the CSR which I found from the output of Posh-ACME.

But the device will check the value of Country Code which is mandatory to its rule.

So I wonder if I can customize the CSR during the process, or is there an option for CSR values.

Thanks for your great work.

Sincerely Yours,
Mark Su

**Comment by rmbolger** [comment]
Unfortunately, even if I updated the module to allow custom DN values in the CSR like country, Let's Encrypt removes everything except the CN for the final signed certificate. So I don't think you're going to be able to use Let's Encrypt for your device.

Here's a thread from the Let's Encrypt community forums talking about the reasoning behind the policy.
[Maintain Subject Records (Country, etc) in Certificate from CSR](https://community.letsencrypt.org/t/maintain-subject-records-country-etc-in-certificate-from-csr/31185)
