### ISSUE TITLE
Add Register.com to Supported DNS Providers

### ISSUE THREAD

**Issue by atrandem** [rmbolger/Posh-ACME#92]
Would it be possible to add Register.com as DNS provider?

**Comment by rmbolger** [comment]
I looked over their website a bit and it doesn't look like they have an API available to modify DNS records. At least, not one for normal users. Without something like that, I can't really make a plugin.

It's not terribly surprising though. Registrars aren't really in the business of providing DNS services. But it's pretty easy to move your domain's DNS to another DNS provider without having to transfer your domain away from register.com. There are plenty of free ones out there that do have plugins already.

**Comment by atrandem** [comment]
Thanks for looking into it, I'll look to move DNS providers.
