### ISSUE TITLE
SchlundTech Integration

### ISSUE THREAD

**Issue by werner-h** [rmbolger/Posh-ACME#97]
Would it be possible to integrate the german provider SchlundTech?
My PS skills are not that advanced to accomplish this.

In other ACME Clients there are an integration available.
Maybe following links could help you:

https://github.com/tohn/acme.sh/blob/a5d83b47bd54a5b56c95598450a64cbd504ccebe/dnsapi/dns_autodns.sh
https://github.com/Neilpang/acme.sh/pull/976/files
https://github.com/Neilpang/acme.sh/blob/e066fcbbe338eff418ef2111b95d9936e1695d8d/dnsapi/dns_schlundtech.sh

Would be very grateful if you can integrate SchlundTech.

**Comment by rmbolger** [comment]
You linked to two different plugins, autoDNS and an old version of a SchlundTech plugin that no longer appears to be part of acme.sh. Are they the same? Does the autoDNS plugin work against SchlundTech?

**Comment by werner-h** [comment]
InternetX AutoDNS and SchlundTech are using the same XML API, different is only the API Gateway URL for sure :)

**Comment by werner-h** [comment]
Would it be possible for you to add a plugin for both providers?

**Comment by rmbolger** [comment]
Most likely, yes. It may end up being a single plugin with an option for which provider to target.

**Comment by rmbolger** [comment]
@werner-h Do you know the gateway URL for SchlundTech? I'm thinking it might be easiest to just have a default `GatewayURL` parameter that points to `https://gateway.autodns.com` that you can override if you're on a different provider.

**Comment by rmbolger** [comment]
Also, I haven't been able to get an account with AutoDNS or Schlundtech to test things with. But I've got the beginning of a plugin that I was hoping you could test for me. If you're willing to loan me your SchlundTech credentials, I could potentially test that way too. If you want to do that, don't post them here. Just email me at z97y9drumh (at) snkmail.com.

In any case, the work-in-progress plugin file is here:
https://github.com/rmbolger/Posh-ACME/blob/autodns/Posh-ACME/DnsPlugins/AutoDNS.ps1

If you download it and add it to the `DnsPlugins` folder in your local copy of the module, you should be able to run the following to test it. Obviously, change the values to your own credentials, gateway, domain, etc.

```
$DebugPreference = 'Continue'
$pluginParams = @{
    AutoDNSUser='myuser'
    AutoDNSPasswordInsecure='mypass'
    AutoDNSContext=4
    AutoDNSGateway='gateway.autodns.com'
}
Publish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
```

At the moment, all it does is try to find the zone and nameserver associated with the domain. So if it's working, you should get a `DEBUG` message that looks something like, "Found example.com with ns1.autodns.com nameserver."

**Comment by rmbolger** [comment]
Awesome. At least I know I'm on the right track.

Another question. Do you know where the "Context" value comes from? All the examples I've seen seem to have it as 4. But I have no idea why or what it means. I'd like to be able to have an explanation for it in the readme.

**Comment by rmbolger** [comment]
Ok, the plugin file has been updated at the same link as before. It should now actually try to Add/Remove the TXT record values. What I'm not sure about is how AutoDNS handles the case where it's trying to add a record that already exists or remove a record that doesn't exist. The [acme.sh plugin](https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_autodns.sh) I'm basing this on appears to just blindly add and remove the records.

Can you try the following with the same setup as before?

```powershell
# create the record
Publish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
# run it a second time with the same input to see if it throws an error
Publish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
# remove the record
Unpublish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
# run it a second time with the same input to see if it throws an error
Unpublish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
```

Also, I want to verify it handles multiple TXT records for the same name properly. So try this with the same setup and verify you end up with two TXT records with different values "asdf" and "qwer".

```powershell
Publish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
Publish-DnsChallenge example.com (Get-PAAccount) qwer AutoDNS $pluginParams -Verbose
```

**Comment by werner-h** [comment]
> Awesome. At least I know I'm on the right track.
> 
> Another question. Do you know where the "Context" value comes from? All the examples I've seen seem to have it as 4. But I have no idea why or what it means. I'd like to be able to have an explanation for it in the readme.

The context value you get predefined from the provider, on my side I got the context number 10.


> Publish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
```
DEBUG: Loading PAAccount list from disk
DEBUG: Calling AutoDNS plugin to add _acme-challenge.example.com TXT with value FpNUCVMi-Ve-aTZynOdss9p3EI1lo5QwKh8O2vCmQUs
DEBUG: Found example.com with nsa7.schlundtech.de nameserver
AUSFÜHRLICH: Adding a TXT record for _acme-challenge.example.com with value FpNUCVMi-Ve-aTZynOdss9p3EI1lo5QwKh8O2vCmQUs
AUSFÜHRLICH: POST https://gateway.schlundtech.de/ with -1-byte payload
AUSFÜHRLICH: received -1-byte response of content type text/xml
DEBUG: <result><msg><text>Zone wurde erfolgreich auf dem Nameserver aktualisiert.</text><code>S0202</code><type>success</type><object><type>zone</type><value>fette-ernte.d
e</value></object></msg><status><code>S0202001</code><text>Massenaktualisierung fuer Zonen wurde erfolgreich abgeschlossen.</text><type>success</type></status></result>
```
I checked up the record with nslookup and the nameserver is replying the correct record.

> Publish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
```
DEBUG: Loading PAAccount list from disk
DEBUG: Calling AutoDNS plugin to add _acme-challenge.example.com TXT with value FpNUCVMi-Ve-aTZynOdss9p3EI1lo5QwKh8O2vCmQUs
DEBUG: Found example.com with nsa7.schlundtech.de nameserver
AUSFÜHRLICH: Adding a TXT record for _acme-challenge.example.com with value FpNUCVMi-Ve-aTZynOdss9p3EI1lo5QwKh8O2vCmQUs
AUSFÜHRLICH: POST https://gateway.schlundtech.de/ with -1-byte payload
AUSFÜHRLICH: received -1-byte response of content type text/xml
DEBUG: <result><msg><text>Zone wurde erfolgreich auf dem Nameserver aktualisiert.</text><code>S0202</code><type>success</type><msg><text>Doppelter Resource-Record wurde ge
loescht. </text><code>MSG02010</code><type>notice</type><object><type>rr[3]</type><value>_acme-challenge</value></object></msg><object><type>zone</type><value>fette-ernte.
de</value></object></msg><status><code>S0202001</code><text>Massenaktualisierung fuer Zonen wurde erfolgreich abgeschlossen.</text><type>success</type></status></result>
```
At the second time it detects the duplicated record and delete it _<text>Doppelter Resource-Record wurde ge
loescht. </text>_ 

> Unpublish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
```
DEBUG: Loading PAAccount list from disk
DEBUG: Calling AutoDNS plugin to remove _acme-challenge.example.com TXT with value FpNUCVMi-Ve-aTZynOdss9p3EI1lo5QwKh8O2vCmQUs
DEBUG: Found example.com with nsa7.schlundtech.de nameserver
AUSFÜHRLICH: Removing TXT record for _acme-challenge.example.com with value FpNUCVMi-Ve-aTZynOdss9p3EI1lo5QwKh8O2vCmQUs
AUSFÜHRLICH: POST https://gateway.schlundtech.de/ with -1-byte payload
AUSFÜHRLICH: received -1-byte response of content type text/xml
DEBUG: <result><msg><text>Zone wurde erfolgreich auf dem Nameserver aktualisiert.</text><code>S0202</code><type>success</type><object><type>zone</type><value>fette-ernte.d
e</value></object></msg><status><code>S0202001</code><text>Massenaktualisierung fuer Zonen wurde erfolgreich abgeschlossen.</text><type>success</type></status></result>
```
The record was successfully removed.

> Unpublish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
Same result as before.

> Publish-DnsChallenge example.com (Get-PAAccount) asdf AutoDNS $pluginParams -Verbose
```
DEBUG: Loading PAAccount list from disk
DEBUG: Calling AutoDNS plugin to add _acme-challenge.example.com TXT with value FpNUCVMi-Ve-aTZynOdss9p3EI1lo5QwKh8O2vCmQUs
DEBUG: Found example.com with nsa7.schlundtech.de nameserver
AUSFÜHRLICH: Adding a TXT record for _acme-challenge.example.com with value FpNUCVMi-Ve-aTZynOdss9p3EI1lo5QwKh8O2vCmQUs
AUSFÜHRLICH: POST https://gateway.schlundtech.de/ with -1-byte payload
AUSFÜHRLICH: received -1-byte response of content type text/xml
DEBUG: <result><msg><text>Zone wurde erfolgreich auf dem Nameserver aktualisiert.</text><code>S0202</code><type>success</type><object><type>zone</type><value>fette-ernte.d
e</value></object></msg><status><code>S0202001</code><text>Massenaktualisierung fuer Zonen wurde erfolgreich abgeschlossen.</text><type>success</type></status></result>
```

> Publish-DnsChallenge example.com (Get-PAAccount) qwer AutoDNS $pluginParams -Verbose
```
DEBUG: Loading PAAccount list from disk
DEBUG: Calling AutoDNS plugin to add _acme-challenge.example.com TXT with value ijM8nPEsOCPRKsNh-xHzOH8a0GtnDMWUk5pFYv_P7Kc
DEBUG: Found example.com with nsa7.schlundtech.de nameserver
AUSFÜHRLICH: Adding a TXT record for _acme-challenge.example.com with value ijM8nPEsOCPRKsNh-xHzOH8a0GtnDMWUk5pFYv_P7Kc
AUSFÜHRLICH: POST https://gateway.schlundtech.de/ with -1-byte payload
AUSFÜHRLICH: received -1-byte response of content type text/xml
DEBUG: <result><msg><text>Zone wurde erfolgreich auf dem Nameserver aktualisiert.</text><code>S0202</code><type>success</type><object><type>zone</type><value>fette-ernte.d
e</value></object></msg><status><code>S0202001</code><text>Massenaktualisierung fuer Zonen wurde erfolgreich abgeschlossen.</text><type>success</type></status></result>
```
Both records are visible via lookup and webinterface.

Good job 👍

**Comment by rmbolger** [comment]
Excellent. Sounds like this is basically done. I'll tidy up some things, add a readme, and push it to the master branch.

**Comment by mucnet** [comment]
Is there someone who can provide a proper configuration for the usage of AutoDNS with SchlundTech?
I've defined the following parameter but I'm not sure whether to handle them as secure strings and how to parse them to PoshACME in a correct manner.
$SchlundUser = (Read-Host -Prompt 'SchlundTech Username'),
    $SchlundPass = (Read-Host -Prompt "Enter SchlundTech Password" -AsSecureString),
	$AutoDNSContext = (Read-Host -Prompt "Schlund DNS Context is 10" ),
     $AutoDNSGateway = (Read-Host -Prompt "DNS Gateway (gateway.schlundtech.de" ),
	# $DomainName = '*.example.com','example.com'    # only the first name will be used for file and path
	$DomainName = (Read-Host -Prompt 'Enter Domain'),
	$ContactName = (Read-Host -Prompt 'Contact Mail is'),
	$Output4Cert = (Read-Host -Prompt 'Output Directory'),  # define output folder
	$CertPass = (Read-Host -Prompt "Certificate Password" -AsSecureString)

So far it tells me I'm using the wrong username/password but using CertifyTheWeb Utility (utilizes PoshACME) runs successfully with the provided credentials, though.

**Comment by webprofusion-chrisc** [comment]
What does the next part of your script look like when you pass the value to `New-PACertificate`? The example code is this:
```
$pArgs = @{
    AutoDNSUser = 'myusername'
    AutoDNSPassword = (Read-Host -Prompt "Password" -AsSecureString)
    AutoDNSContext = '4'
    AutoDNSGateway = 'gateway.autodns.com'
}
New-PACertificate example.com -Plugin AutoDNS -PluginArgs $pArgs
```
Note that the AutoDNSUser etc argument names are fixed, it's the values that are variable.

**Comment by rmbolger** [comment]
Hi @mucnet. @webprofusion-chrisc has the right idea. When using a Posh-ACME plugin directly, the parameters are passed using a hashtable object with the various parameters as keys. Here's a link to the plugin guide for AutoDNS.

https://poshac.me/docs/v4/Plugins/AutoDNS/
